### ISSUE TITLE
Run iOS C++ unit tests on CI

### ISSUE THREAD

**Issue by louwers** [maplibre/maplibre-native#1001]
Run iOS C++ unit tests via the [iOS UnitTestsRunner App](https://github.com/maplibre/maplibre-gl-native/tree/fc0873a682363ab1b095341b9a406785ccfc7620/test/ios).

This is especially important because we will disable the macOS CI while the Metal backend implementation is underway due to macOS' lacking OpenGL 3.0 support.

The test runner is being run here:

https://github.com/maplibre/maplibre-gl-native/blob/fc0873a682363ab1b095341b9a406785ccfc7620/test/ios/ios_test_runner.cpp#L14

**Comment by ntadej** [comment]
Hmm, is it OK then to move to OpenGL 3.0?

**Comment by louwers** [comment]
@ntadej The other platforms are fine #995
