### ISSUE TITLE
Custom builds with IOS SDK Fail

### ISSUE THREAD

**Issue by hmtriit** [maplibre/maplibre-native#1008]
**Describe the bug**
Hi master I have a issue when Custom builds with IOS SDK 

**To Reproduce**
1. Clone the git repository 
 git clone https://github.com/maplibre/maplibre-gl-native.git
 cd maplibre-gl-native
2. git submodule update --init
4. cd maplibre-gl-native/platform/ios/
5. Run make iframework BUILDTYPE=Release
6. See error

**Expected behavior**
The packaging IOS SDK build success

**Screenshots**
<img width="877" alt="image" src="https://user-images.githubusercontent.com/48192781/231329582-abb680d1-0fbb-4168-9b3a-181c29cf1104.png">

**Platform information:**
 - Platform [iOS]

Please help me solve it
Thanks

**Comment by ovivoda** [comment]
@alexcristici can this be related to the naming changes?

**Comment by louwers** [comment]
@hmtriit Could you try `make style-code`? I forgot to add is to the dependencies of `iframework`.

**Comment by alexcristici** [comment]
> @alexcristici can this be related to the naming changes?

File `MLNLight.h` exists, so probably the include path to this file needs to be investigated.

**Comment by nnhubbard** [comment]
I have this issue as well. I don't see the `MLNLight.h` file anywhere in the project?

**Comment by 1ec5** [comment]
The `iframework` target is missing a `style-code` invocation:

https://github.com/louwers/maplibre-gl-native/blob/4ebb7c59dcda9e59923652728fb2050bda0b8e5d/platform/ios/Makefile#L202C9-L205

/ref https://github.com/maplibre/maplibre-native/pull/844#discussion_r1114646430

**Comment by nnhubbard** [comment]
Any help on getting this fixed? @1ec5

**Comment by 1ec5** [comment]
Pretty sure https://github.com/maplibre/maplibre-native/issues/1008#issuecomment-1558636433 would fix the issue, though I’m a bit too busy to test it out at the moment.

**Comment by louwers** [comment]
#1208 should have fixed it. If not let me know.
