### ISSUE TITLE
Uniform Buffer Object for per-frame logic

### ISSUE THREAD

**Issue by sjg-wdw** [maplibre/maplibre-native#1062]
Everything the main render loops communicates via uniforms right now need to go into a single UBO we can pass to shaders across all the Drawables.

This is stuff like the map scale, the matrix, etc.  But not things specific to the Layers.  They have their own UBOs.

**Comment by sjg-wdw** [comment]
In the end I don't think you ended up doing this, right?  It turned into a per layer UBO?

**Comment by alexcristici** [comment]
The UBOs are owned only by drawables in this moment. From the point of view how often are created or updated, there 3 types: 
- UBOs created each frame and different for each drawable (like matrix).
- UBOs created per layer each frame and shared to all drawables of the same layer group.
- UBOs created/updated per layer only when zoom is changed or other triggers and shared to all drawables in the same layer group.
