### ISSUE TITLE
Background Layer - Textures and Patterns

### ISSUE THREAD

**Issue by sjg-wdw** [maplibre/maplibre-native#1129]

**Comment by sjg-wdw** [comment]
Wire the new texture approach into the background layer for patterns.

**Comment by sjg-wdw** [comment]
Do we have the PR on this one?  It sounds like we're functionally done.

**Comment by TimSylvester** [comment]
It's mostly already merged, just #1200 with some cleanup.

**Comment by sjg-wdw** [comment]
Do we think this is done?

**Comment by TimSylvester** [comment]
Yeah, I think anything left can be called a bug or an optimization.

**Comment by sjg-wdw** [comment]
Still using the old templated program to render to the stencil buffer.

**Comment by TimSylvester** [comment]
> Still using the old templated program to render to the stencil buffer.

That doesn't apply to background, only fill and line.

**Comment by sjg-wdw** [comment]
Typed that into the wrong window.  But closed in any case.
