### ISSUE TITLE
Drawable shaders need integration with existing shader infrastructure

### ISSUE THREAD

**Issue by mwilsnd** [maplibre/maplibre-native#1130]
New shaders for drawables need integration with the code generation system, loading & compiling from generated headers and revised permutation support for supplemental vertex attributes.

**Comment by sjg-wdw** [comment]
One question I had is if we'll continue generating the shaders indefinitely or if we're going to cut that off at some point and just freeze the versions.

**Comment by mwilsnd** [comment]
Closed by #1132
