### ISSUE TITLE
Draft: Android Examples Repo

### ISSUE THREAD

**Issue by louwers** [maplibre/maplibre-native#1151]
I want us to set up a separate repo for Android examples. But I am also open to the idea to keep it in this repository if it is easier for some reason.

Here are some ideas:

- There should be CI that builds and tests the example apps.
- The example apps should consume the MapLibre library in the same way Android end users do (i.e. not compile from source).
- Dependabot should be set up to automatically create PRs to update dependencies (including MapLibre).
- There should be instructions how to add a new example (app).
- Source code should be referenced instead of copy pasted into Markdown files. [Example](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-a-permanent-link-to-a-code-snippet)
- To be decided: write documentation in in-source Markdown files or use a documentation generator and deploy.

If during the implementation a better way of doing things is found for some of these points then we can deviate from them.

This issue is still a draft until the scope has been decided. As with all bounties interested developers can suggest a bounty size before accepting to work on the bounty. I put a tentative M bounty because I think it fits.

**Comment by ntadej** [comment]
I would not clutter the current repo much, but if we eventually split the Android bindings to a separate repo, examples could live there.

**Comment by louwers** [comment]
After talking about it with @fynngodau we want to use the example app part of this repo for end-user examples as well.

This app is already thoroughly tested.

It's probably too much of a maintainer burden to set up and maintain all the necessary tooling for another repo (at least until we may have separate maintainers for each platform).
