### ISSUE TITLE
Un-deprecate Annotations API & integrate Annotations plugin code (Kotlin)

### ISSUE THREAD

**Issue by louwers** [maplibre/maplibre-native#1154]
Pending discussion https://github.com/maplibre/maplibre-native/discussions/1152

and here

https://github.com/maplibre/maplibre-plugins-android/issues/27

**Scope of bounty**

- Port any fixes and functionality from the Annotations plugin at https://github.com/maplibre/maplibre-plugins-android
- Rewrite in Kotlin https://github.com/maplibre/maplibre-native/tree/main/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations
- Port tests and examples from example app (Kotlin) https://github.com/maplibre/maplibre-plugins-android/tree/main/app/src/androidTest/java/com/mapbox/mapboxsdk/plugins/annotation

This would be a bounty towards the Modernization direction https://github.com/maplibre/maplibre/issues/270

**Comment by louwers** [comment]
@fynngodau Let's close this issue and create separate tickets for implementing #1255? If you agree feel free to create a ticket with what you believe would be a good first step.

**Comment by fynngodau** [comment]
Closing in favor of #1491.
