### ISSUE TITLE
Get rid of `mapbox.mapboxsdk` & Mapbox in package names and identifiers

### ISSUE THREAD

**Issue by louwers** [maplibre/maplibre-native#1155]
Scope of this bounty:

- Make sure end-users of the Android library don't need to import packages containing `mapbox` in the name.
- Make sure end-users of the Android library don't need to import any variables with `mapbox` / `Mapbox` in the name.
- CHANGELOG should be updated (including migration guide).
- Tests should pass. The library should be in a releasable state.

E.g.

```kt
import com.mapbox.mapboxsdk.geometry.LatLng
```

Should become (suggested)

```kt
import org.maplibre.native.geometry.LatLng
```

And `import com.mapbox.mapboxsdk.Mapbox` -> `import org.maplibre.native.MapLibre`
`import com.mapbox.mapboxsdk.maps.MapboxMap` -> `import org.maplibre.native.maps.MapLibreMap`

Etc.

I think automated tools can do most of the heavy lifting for this issue, so the M bounty is an estimate. It is negotiable before the ticket has been accepted if you think it is the estimate is off. 

This is a bounty towards the Modernization bounty direction. https://github.com/maplibre/maplibre/issues/270

Relevant discussion https://github.com/maplibre/maplibre-native/discussions/318

**Comment by fynngodau** [comment]
I begun work on this issue this week. Probably because there's so many renamings, the refactorer has unfortunately produced a lot of bad results that I'm fixing manually right now.

**Comment by ovivoda** [comment]
@fynngodau what have you used as the main package of the library?

**Comment by fynngodau** [comment]
@ovivoda Per discussion on Slack, `org.maplibre.android` (`native` is not a valid package name)

**Comment by louwers** [comment]
This bounty can be paid out.

**Comment by fynngodau** [comment]
Invoice: https://opencollective.com/maplibre/expenses/143826
