### ISSUE TITLE
Common crash referencing `MBGLCustomGeometrySourceOptionsFromDictionary`

### ISSUE THREAD

**Issue by naftalibeder** [maplibre/maplibre-native#123]
I am using this library through [react-native-mapbox-gl](https://github.com/react-native-mapbox-gl/maps).

Since switching the base library from [mapbox-gl-native](https://github.com/mapbox/mapbox-gl-native), I am seeing a huge increase in crashes on iOS (from under 1% to over 10%), referencing the line `MBGLCustomGeometrySourceOptionsFromDictionary`. (On Android, there is no increase in crashes.)

This appears to be a method that is used to populate `MGLComputedShapeSource`, and I had previously also experienced many crashes seemingly related to displaying images inside of `ShapeSource` instances, indicating that the original Mapbox library has a similar problem.

What would it take to stabilize this part of the code? Ideally, if an image is unable to be displayed (if that's what the issue here is), there should simply be nothing displayed - I imagine anything is preferable to a hard crash.

Version: 5.11.0 (Unable to upgrade to 5.12.0 due to build errors.)

<details>
<summary>iOS crash log</summary>
OS Version: iOS 14.6 (18F72)
Report Version: 104

Exception Type: EXC_BAD_ACCESS (SIGBUS)
Exception Codes: BUS_NOOP
Crashed Thread: 0

Application Specific Information:
Exception 1, Code 0, Subcode 8 >
Attempted to dereference null pointer.

Thread 0 Crashed:
0   libsystem_platform.dylib        0x3b3f5f684         _platform_memmove
1   AGXMetalA14                     0x3b624dfa0         <redacted>
2   AGXMetalA14                     0x3b624dd1c         <redacted>
3   AppleMetalGLRenderer            0x3b49b099c         gldReadFramebufferData
4   GLEngine                        0x38462061c         glReadPixels_Exec
5   GLKit                           0x381f294e8         -[GLKView snapshot]
6   Mapbox                          0x101750b28         MBGLCustomGeometrySourceOptionsFromDictionary
7   CoreFoundation                  0x31c4aa6d0         __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__
8   CoreFoundation                  0x31c4aa678         ___CFXRegistrationPost_block_invoke
9   CoreFoundation                  0x31c4a9be4         _CFXRegistrationPost
10  CoreFoundation                  0x31c4a95a4         _CFXNotificationPost
11  Foundation                      0x31eb306a8         -[NSNotificationCenter postNotificationName:object:userInfo:]
12  UIKitCore                       0x320e84c6c         -[UIApplication _deactivateForReason:notify:]
13  UIKitCore                       0x3204e2ca4         __101-[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:]_block_invoke_2
14  UIKitCore                       0x320a4af54         _UIScenePerformActionsWithLifecycleActionMask
15  UIKitCore                       0x3204e282c         __101-[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:]_block_invoke
16  UIKitCore                       0x3204e22ec         -[_UISceneLifecycleMultiplexer _performBlock:withApplicationOfDeactivationReasons:fromReasons:]
17  UIKitCore                       0x3204e263c         -[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:]
18  UIKitCore                       0x3204e1e78         -[_UISceneLifecycleMultiplexer uiScene:transitionedFromState:withTransitionContext:]
19  UIKitCore                       0x3204ea3bc         __186-[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:]_block_invoke
20  UIKitCore                       0x32095896c         +[BSAnimationSettings(UIKit) tryAnimatingWithSettings:actions:completion:]
21  UIKitCore                       0x320a63d64         _UISceneSettingsDiffActionPerformChangesWithTransitionContext
22  UIKitCore                       0x3204ea0b4         -[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:]
23  UIKitCore                       0x320311f9c         __64-[UIScene scene:didUpdateWithDiff:transitionContext:completion:]_block_invoke
24  UIKitCore                       0x32031091c         -[UIScene _emitSceneSettingsUpdateResponseForCompletion:afterSceneUpdateWork:]
25  UIKitCore                       0x320311bc4         -[UIScene scene:didUpdateWithDiff:transitionContext:completion:]
26  UIKitCore                       0x32098247c         -[UIApplicationSceneClientAgent scene:handleEvent:withCompletion:]
27  FrontBoardServices              0x33b192eb4         -[FBSScene updater:didUpdateSettings:withDiff:transitionContext:completion:]
28  FrontBoardServices              0x33b1bf4ec         __94-[FBSWorkspaceScenesClient _queue_updateScene:withSettings:diff:transitionContext:completion:]_block_invoke_2
29  FrontBoardServices              0x33b1a16a0         -[FBSWorkspace _calloutQueue_executeCalloutFromSource:withBlock:]
30  FrontBoardServices              0x33b1bf418         __94-[FBSWorkspaceScenesClient _queue_updateScene:withSettings:diff:transitionContext:completion:]_block_invoke
31  libdispatch.dylib               0x31be4e818         _dispatch_client_callout
32  libdispatch.dylib               0x31be52308         _dispatch_block_invoke_direct
33  FrontBoardServices              0x33b1e5f9c         __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__
34  FrontBoardServices              0x33b1e5c2c         -[FBSSerialQueue _targetQueue_performNextIfPossible]
35  FrontBoardServices              0x33b1e6180         -[FBSSerialQueue _performNextFromRunLoopSource]
36  CoreFoundation                  0x31c4c99e4         __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
37  CoreFoundation                  0x31c4c98e0         __CFRunLoopDoSource0
38  CoreFoundation                  0x31c4c8be4         __CFRunLoopDoSources0
39  CoreFoundation                  0x31c4c2bc4         __CFRunLoopRun
40  CoreFoundation                  0x31c4c235c         CFRunLoopRunSpecific
41  GraphicsServices                0x34b1d7730         GSEventRunModal
42  UIKitCore                       0x320e8a580         -[UIApplication _run]
43  UIKitCore                       0x320e8fdf0         UIApplicationMain
44  TruckMap                        0x200d7fed0         <redacted>
45  libdyld.dylib                   0x31bed5cf4         start

Thread 0 Crashed:
0   libsystem_platform.dylib        0x3b3f5f684         _platform_memmove
1   AGXMetalA14                     0x3b624dfa0         <redacted>
2   AGXMetalA14                     0x3b624dd1c         <redacted>
3   AppleMetalGLRenderer            0x3b49b099c         gldReadFramebufferData
4   GLEngine                        0x38462061c         glReadPixels_Exec
5   GLKit                           0x381f294e8         -[GLKView snapshot]
6   Mapbox                          0x101750b28         MBGLCustomGeometrySourceOptionsFromDictionary
7   CoreFoundation                  0x31c4aa6d0         __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__
8   CoreFoundation                  0x31c4aa678         ___CFXRegistrationPost_block_invoke
9   CoreFoundation                  0x31c4a9be4         _CFXRegistrationPost
10  CoreFoundation                  0x31c4a95a4         _CFXNotificationPost
11  Foundation                      0x31eb306a8         -[NSNotificationCenter postNotificationName:object:userInfo:]
12  UIKitCore                       0x320e84c6c         -[UIApplication _deactivateForReason:notify:]
13  UIKitCore                       0x3204e2ca4         __101-[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:]_block_invoke_2
14  UIKitCore                       0x320a4af54         _UIScenePerformActionsWithLifecycleActionMask
15  UIKitCore                       0x3204e282c         __101-[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:]_block_invoke
16  UIKitCore                       0x3204e22ec         -[_UISceneLifecycleMultiplexer _performBlock:withApplicationOfDeactivationReasons:fromReasons:]
17  UIKitCore                       0x3204e263c         -[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:]
18  UIKitCore                       0x3204e1e78         -[_UISceneLifecycleMultiplexer uiScene:transitionedFromState:withTransitionContext:]
19  UIKitCore                       0x3204ea3bc         __186-[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:]_block_invoke
20  UIKitCore                       0x32095896c         +[BSAnimationSettings(UIKit) tryAnimatingWithSettings:actions:completion:]
21  UIKitCore                       0x320a63d64         _UISceneSettingsDiffActionPerformChangesWithTransitionContext
22  UIKitCore                       0x3204ea0b4         -[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:]
23  UIKitCore                       0x320311f9c         __64-[UIScene scene:didUpdateWithDiff:transitionContext:completion:]_block_invoke
24  UIKitCore                       0x32031091c         -[UIScene _emitSceneSettingsUpdateResponseForCompletion:afterSceneUpdateWork:]
25  UIKitCore                       0x320311bc4         -[UIScene scene:didUpdateWithDiff:transitionContext:completion:]
26  UIKitCore                       0x32098247c         -[UIApplicationSceneClientAgent scene:handleEvent:withCompletion:]
27  FrontBoardServices              0x33b192eb4         -[FBSScene updater:didUpdateSettings:withDiff:transitionContext:completion:]
28  FrontBoardServices              0x33b1bf4ec         __94-[FBSWorkspaceScenesClient _queue_updateScene:withSettings:diff:transitionContext:completion:]_block_invoke_2
29  FrontBoardServices              0x33b1a16a0         -[FBSWorkspace _calloutQueue_executeCalloutFromSource:withBlock:]
30  FrontBoardServices              0x33b1bf418         __94-[FBSWorkspaceScenesClient _queue_updateScene:withSettings:diff:transitionContext:completion:]_block_invoke
31  libdispatch.dylib               0x31be4e818         _dispatch_client_callout
32  libdispatch.dylib               0x31be52308         _dispatch_block_invoke_direct
33  FrontBoardServices              0x33b1e5f9c         __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__
34  FrontBoardServices              0x33b1e5c2c         -[FBSSerialQueue _targetQueue_performNextIfPossible]
35  FrontBoardServices              0x33b1e6180         -[FBSSerialQueue _performNextFromRunLoopSource]
36  CoreFoundation                  0x31c4c99e4         __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
37  CoreFoundation                  0x31c4c98e0         __CFRunLoopDoSource0
38  CoreFoundation                  0x31c4c8be4         __CFRunLoopDoSources0
39  CoreFoundation                  0x31c4c2bc4         __CFRunLoopRun
40  CoreFoundation                  0x31c4c235c         CFRunLoopRunSpecific
41  GraphicsServices                0x34b1d7730         GSEventRunModal
42  UIKitCore                       0x320e8a580         -[UIApplication _run]
43  UIKitCore                       0x320e8fdf0         UIApplicationMain
44  TruckMap                        0x200d7fed0         <redacted>
45  libdyld.dylib                   0x31bed5cf4         start

Thread 1
0   libsystem_kernel.dylib          0x378ab20a4         __workq_kernreturn
1   libsystem_pthread.dylib         0x3b3f6d7ec         _pthread_wqthread

Thread 2
0   libsystem_kernel.dylib          0x378ab20a4         __workq_kernreturn
1   libsystem_pthread.dylib         0x3b3f6d7ec         _pthread_wqthread

Thread 3
0   libsystem_kernel.dylib          0x378ab20a4         __workq_kernreturn
1   libsystem_pthread.dylib         0x3b3f6d7ec         _pthread_wqthread

Thread 4
0   libsystem_kernel.dylib          0x378ab20a4         __workq_kernreturn
1   libsystem_pthread.dylib         0x3b3f6d7ec         _pthread_wqthread

Thread 5 name: com.apple.uikit.eventfetch-thread
0   libsystem_kernel.dylib          0x378a8c4fc         mach_msg_trap
1   libsystem_kernel.dylib          0x378a8b880         mach_msg
2   CoreFoundation                  0x31c4c8eac         __CFRunLoopServiceMachPort
3   CoreFoundation                  0x31c4c2d4c         __CFRunLoopRun
4   CoreFoundation                  0x31c4c235c         CFRunLoopRunSpecific
5   Foundation                      0x31eb31fd8         -[NSRunLoop(NSRunLoop) runMode:beforeDate:]
6   Foundation                      0x31eb31ea4         -[NSRunLoop(NSRunLoop) runUntilDate:]
7   UIKitCore                       0x320f3f128         -[UIEventFetcher threadMain]
8   Foundation                      0x31eca3328         __NSThread__start__
9   libsystem_pthread.dylib         0x3b3f6bbf8         _pthread_start

Thread 6 name: com.facebook.react.JavaScript
0   libsystem_kernel.dylib          0x378a8c4fc         mach_msg_trap
1   libsystem_kernel.dylib          0x378a8b880         mach_msg
2   CoreFoundation                  0x31c4c8eac         __CFRunLoopServiceMachPort
3   CoreFoundation                  0x31c4c2d4c         __CFRunLoopRun
4   CoreFoundation                  0x31c4c235c         CFRunLoopRunSpecific
5   TruckMap                        0x200de5f6c         facebook::react::JSIExecutor::defaultTimeoutInvoker
6   Foundation                      0x31eca3328         __NSThread__start__
7   libsystem_pthread.dylib         0x3b3f6bbf8         _pthread_start

Thread 7 name: JavaScriptCore bmalloc scavenger
0   libsystem_kernel.dylib          0x378ab10cc         __psynch_cvwait
1   libsystem_pthread.dylib         0x3b3f6f430         _pthread_cond_wait
2   libc++.1.dylib                  0x345cf3ef8         std::__1::condition_variable::wait
3   JavaScriptCore                  0x32fe4ec38         std::__1::condition_variable_any::wait<T>
4   JavaScriptCore                  0x32fe53080         bmalloc::Scavenger::threadRunLoop
5   JavaScriptCore                  0x32fe52c8c         bmalloc::Scavenger::threadEntryPoint
6   JavaScriptCore                  0x32fe541a0         std::__1::__thread_proxy<T>
7   libsystem_pthread.dylib         0x3b3f6bbf8         _pthread_start

Thread 8 name: com.mapbox.mbgl.AssetFileSource
0   libsystem_kernel.dylib          0x378a8c4fc         mach_msg_trap
1   libsystem_kernel.dylib          0x378a8b880         mach_msg
2   CoreFoundation                  0x31c4c8eac         __CFRunLoopServiceMachPort
3   CoreFoundation                  0x31c4c2d4c         __CFRunLoopRun
4   CoreFoundation                  0x31c4c235c         CFRunLoopRunSpecific
5   CoreFoundation                  0x31c4c3448         CFRunLoopRun
6   Mapbox                          0x1013f3588         mbgl::resourceURL
7   Mapbox                          0x1013f33cc         mbgl::resourceURL
8   libsystem_pthread.dylib         0x3b3f6bbf8         _pthread_start

Thread 9 name: com.mapbox.mbgl.OnlineFileSource
0   libsystem_kernel.dylib          0x378a8c4fc         mach_msg_trap
1   libsystem_kernel.dylib          0x378a8b880         mach_msg
2   CoreFoundation                  0x31c4c8eac         __CFRunLoopServiceMachPort
3   CoreFoundation                  0x31c4c2d4c         __CFRunLoopRun
4   CoreFoundation                  0x31c4c235c         CFRunLoopRunSpecific
5   CoreFoundation                  0x31c4c3448         CFRunLoopRun
6   Mapbox                          0x10142904c         mbgl::resourceURL
7   Mapbox                          0x101428f0c         mbgl::resourceURL
8   libsystem_pthread.dylib         0x3b3f6bbf8         _pthread_start

Thread 10 name: com.mapbox.mbgl.DatabaseFileSource
0   libsystem_kernel.dylib          0x378a8c4fc         mach_msg_trap
1   libsystem_kernel.dylib          0x378a8b880         mach_msg
2   CoreFoundation                  0x31c4c8eac         __CFRunLoopServiceMachPort
3   CoreFoundation                  0x31c4c2d4c         __CFRunLoopRun
4   CoreFoundation                  0x31c4c235c         CFRunLoopRunSpecific
5   CoreFoundation                  0x31c4c3448         CFRunLoopRun
6   Mapbox                          0x1013f997c         mbgl::resourceURL
7   Mapbox                          0x1013f98b8         mbgl::resourceURL
8   libsystem_pthread.dylib         0x3b3f6bbf8         _pthread_start

Thread 11 name: com.mapbox.mbgl.LocalFileSource
0   libsystem_kernel.dylib          0x378a8c4fc         mach_msg_trap
1   libsystem_kernel.dylib          0x378a8b880         mach_msg
2   CoreFoundation                  0x31c4c8eac         __CFRunLoopServiceMachPort
3   CoreFoundation                  0x31c4c2d4c         __CFRunLoopRun
4   CoreFoundation                  0x31c4c235c         CFRunLoopRunSpecific
5   CoreFoundation                  0x31c4c3448         CFRunLoopRun
6   Mapbox                          0x10140078c         mbgl::resourceURL
7   Mapbox                          0x101400634         mbgl::resourceURL
8   libsystem_pthread.dylib         0x3b3f6bbf8         _pthread_start

Thread 12 name: com.mapbox.mbgl.MaptilerFileSource
0   libsystem_kernel.dylib          0x378a8c4fc         mach_msg_trap
1   libsystem_kernel.dylib          0x378a8b880         mach_msg
2   CoreFoundation                  0x31c4c8eac         __CFRunLoopServiceMachPort
3   CoreFoundation                  0x31c4c2d4c         __CFRunLoopRun
4   CoreFoundation                  0x31c4c235c         CFRunLoopRunSpecific
5   CoreFoundation                  0x31c4c3448         CFRunLoopRun
6   Mapbox                          0x101410a6c         mbgl::resourceURL
7   Mapbox                          0x1014108f0         mbgl::resourceURL
8   libsystem_pthread.dylib         0x3b3f6bbf8         _pthread_start

Thread 13 name: com.mapbox.mbgl.ResourceLoaderThread
0   libsystem_kernel.dylib          0x378a8c4fc         mach_msg_trap
1   libsystem_kernel.dylib          0x378a8b880         mach_msg
2   CoreFoundation                  0x31c4c8eac         __CFRunLoopServiceMachPort
3   CoreFoundation                  0x31c4c2d4c         __CFRunLoopRun
4   CoreFoundation                  0x31c4c235c         CFRunLoopRunSpecific
5   CoreFoundation                  0x31c4c3448         CFRunLoopRun
6   Mapbox                          0x1014061f4         mbgl::resourceURL
7   Mapbox                          0x101406078         mbgl::resourceURL
8   libsystem_pthread.dylib         0x3b3f6bbf8         _pthread_start

Thread 14 name: com.apple.NSURLConnectionLoader
0   libsystem_kernel.dylib          0x378a8c4fc         mach_msg_trap
1   libsystem_kernel.dylib          0x378a8b880         mach_msg
2   CoreFoundation                  0x31c4c8eac         __CFRunLoopServiceMachPort
3   CoreFoundation                  0x31c4c2d4c         __CFRunLoopRun
4   CoreFoundation                  0x31c4c235c         CFRunLoopRunSpecific
5   CFNetwork                       0x31d4cdb34         _CFURLStorageSessionCopyCache
6   Foundation                      0x31eca3328         __NSThread__start__
7   libsystem_pthread.dylib         0x3b3f6bbf8         _pthread_start

Thread 15 name: AVAudioSession Notify Thread
0   libsystem_kernel.dylib          0x378a8c4fc         mach_msg_trap
1   libsystem_kernel.dylib          0x378a8b880         mach_msg
2   CoreFoundation                  0x31c4c8eac         __CFRunLoopServiceMachPort
3   CoreFoundation                  0x31c4c2d4c         __CFRunLoopRun
4   CoreFoundation                  0x31c4c235c         CFRunLoopRunSpecific
5   AudioSession                    0x32ba82f1c         GenericRunLoopThread::Entry
6   AudioSession                    0x32ba850d4         CAPThread::Entry
7   libsystem_pthread.dylib         0x3b3f6bbf8         _pthread_start

Thread 16 name: com.squareup.SocketRocket.NetworkThread
0   libsystem_kernel.dylib          0x378a8c4fc         mach_msg_trap
1   libsystem_kernel.dylib          0x378a8b880         mach_msg
2   CoreFoundation                  0x31c4c8eac         __CFRunLoopServiceMachPort
3   CoreFoundation                  0x31c4c2d4c         __CFRunLoopRun
4   CoreFoundation                  0x31c4c235c         CFRunLoopRunSpecific
5   Foundation                      0x31eb31fd8         -[NSRunLoop(NSRunLoop) runMode:beforeDate:]
6   TruckMap                        0x200e22514         facebook::react::JSIExecutor::defaultTimeoutInvoker
7   Foundation                      0x31eca3328         __NSThread__start__
8   libsystem_pthread.dylib         0x3b3f6bbf8         _pthread_start

Thread 17
0   libsystem_kernel.dylib          0x378ab20a4         __workq_kernreturn
1   libsystem_pthread.dylib         0x3b3f6d7ec         _pthread_wqthread

Thread 18
0   libsystem_kernel.dylib          0x378ab1734         __semwait_signal
1   libsystem_c.dylib               0x32ed5aa30         nanosleep
2   libsystem_c.dylib               0x32ed5a814         sleep
3   TruckMap                        0x200ed3a38         facebook::react::JSIExecutor::defaultTimeoutInvoker
4   libsystem_pthread.dylib         0x3b3f6bbf8         _pthread_start

Thread 19 name: SentryCrash Exception Handler (Secondary)
0   libsystem_kernel.dylib          0x378a8c4fc         mach_msg_trap
1   libsystem_kernel.dylib          0x378a8b880         mach_msg
2   TruckMap                        0x200edfe40         __cxa_throw
3   libsystem_pthread.dylib         0x3b3f6bbf8         _pthread_start

Thread 21 name: com.mapbox.mbgl.Worker 1
0   libsystem_kernel.dylib          0x378ab10cc         __psynch_cvwait
1   libsystem_pthread.dylib         0x3b3f6f430         _pthread_cond_wait
2   libc++.1.dylib                  0x345cf3ef8         std::__1::condition_variable::wait
3   Mapbox                          0x1016d80f8         mbgl::resourceURL
4   libsystem_pthread.dylib         0x3b3f6bbf8         _pthread_start

Thread 22 name: com.mapbox.mbgl.Worker 2
0   libsystem_kernel.dylib          0x378ab10cc         __psynch_cvwait
1   libsystem_pthread.dylib         0x3b3f6f430         _pthread_cond_wait
2   libc++.1.dylib                  0x345cf3ef8         std::__1::condition_variable::wait
3   Mapbox                          0x1016d80f8         mbgl::resourceURL
4   libsystem_pthread.dylib         0x3b3f6bbf8         _pthread_start

Thread 23 name: com.mapbox.mbgl.Worker 3
0   libsystem_kernel.dylib          0x378ab10cc         __psynch_cvwait
1   libsystem_pthread.dylib         0x3b3f6f430         _pthread_cond_wait
2   libc++.1.dylib                  0x345cf3ef8         std::__1::condition_variable::wait
3   Mapbox                          0x1016d80f8         mbgl::resourceURL
4   libsystem_pthread.dylib         0x3b3f6bbf8         _pthread_start

Thread 24 name: com.mapbox.mbgl.Worker 4
0   libsystem_kernel.dylib          0x378ab10cc         __psynch_cvwait
1   libsystem_pthread.dylib         0x3b3f6f430         _pthread_cond_wait
2   libc++.1.dylib                  0x345cf3ef8         std::__1::condition_variable::wait
3   Mapbox                          0x1016d80f8         mbgl::resourceURL
4   libsystem_pthread.dylib         0x3b3f6bbf8         _pthread_start

Thread 25 name: com.mapbox.mbgl.Worker 1
0   libsystem_kernel.dylib          0x378ab10cc         __psynch_cvwait
1   libsystem_pthread.dylib         0x3b3f6f430         _pthread_cond_wait
2   libc++.1.dylib                  0x345cf3ef8         std::__1::condition_variable::wait
3   Mapbox                          0x1016d80f8         mbgl::resourceURL
4   libsystem_pthread.dylib         0x3b3f6bbf8         _pthread_start

Thread 26 name: com.mapbox.mbgl.Worker 1
0   libsystem_kernel.dylib          0x378ab10cc         __psynch_cvwait
1   libsystem_pthread.dylib         0x3b3f6f430         _pthread_cond_wait
2   libc++.1.dylib                  0x345cf3ef8         std::__1::condition_variable::wait
3   Mapbox                          0x1016d80f8         mbgl::resourceURL
4   libsystem_pthread.dylib         0x3b3f6bbf8         _pthread_start

Thread 27
0   libsystem_kernel.dylib          0x378ab20a4         __workq_kernreturn
1   libsystem_pthread.dylib         0x3b3f6d7ec         _pthread_wqthread

Thread 28
0   libsystem_kernel.dylib          0x378ab20a4         __workq_kernreturn
1   libsystem_pthread.dylib         0x3b3f6d7ec         _pthread_wqthread

Thread 29
0   libsystem_kernel.dylib          0x378ab1e7c         __ulock_wait
1   libdispatch.dylib               0x31be4f1f8         _dlock_wait
2   libdispatch.dylib               0x31be4eed8         _dispatch_wait_on_address
3   libdispatch.dylib               0x31be4f5a0         _dispatch_group_wait_slow
4   TruckMap                        0x200f6aeac         __cxa_throw
5   libdispatch.dylib               0x31be4ca80         _dispatch_call_block_and_release
6   libdispatch.dylib               0x31be4e818         _dispatch_client_callout
7   libdispatch.dylib               0x31be51964         _dispatch_queue_override_invoke
8   libdispatch.dylib               0x31be5ffdc         _dispatch_root_queue_drain
9   libdispatch.dylib               0x31be607d4         _dispatch_worker_thread2
10  libsystem_pthread.dylib         0x3b3f6d764         _pthread_wqthread

Thread 30
0   libsystem_kernel.dylib          0x378ab20a4         __workq_kernreturn
1   libsystem_pthread.dylib         0x3b3f6d7ec         _pthread_wqthread

Thread 31
0   libsystem_kernel.dylib          0x378ab20a4         __workq_kernreturn
1   libsystem_pthread.dylib         0x3b3f6d7ec         _pthread_wqthread

Thread 32
0   libsystem_kernel.dylib          0x378ab20a4         __workq_kernreturn
1   libsystem_pthread.dylib         0x3b3f6d7ec         _pthread_wqthread

Thread 33
0   libsystem_kernel.dylib          0x378ab10cc         __psynch_cvwait
1   libsystem_pthread.dylib         0x3b3f6f430         _pthread_cond_wait
2   JavaScriptCore                  0x32fdd9a34         WTF::ParkingLot::parkConditionallyImpl
3   JavaScriptCore                  0x32f614fd8         WTF::Condition::waitUntil<T>
4   JavaScriptCore                  0x32fda6334         WTF::Detail::CallableWrapper<T>::call
5   JavaScriptCore                  0x32fdfd908         WTF::Thread::entryPoint
6   JavaScriptCore                  0x32fe000c8         WTF::wtfThreadEntryPoint
7   libsystem_pthread.dylib         0x3b3f6bbf8         _pthread_start

Thread 34
0   libsystem_kernel.dylib          0x378ab10cc         __psynch_cvwait
1   libsystem_pthread.dylib         0x3b3f6f430         _pthread_cond_wait
2   JavaScriptCore                  0x32fdd9a34         WTF::ParkingLot::parkConditionallyImpl
3   JavaScriptCore                  0x32f614fd8         WTF::Condition::waitUntil<T>
4   JavaScriptCore                  0x32fda6334         WTF::Detail::CallableWrapper<T>::call
5   JavaScriptCore                  0x32fdfd908         WTF::Thread::entryPoint
6   JavaScriptCore                  0x32fe000c8         WTF::wtfThreadEntryPoint
7   libsystem_pthread.dylib         0x3b3f6bbf8         _pthread_start

Thread 35
0   libsystem_kernel.dylib          0x378ab10cc         __psynch_cvwait
1   libsystem_pthread.dylib         0x3b3f6f430         _pthread_cond_wait
2   JavaScriptCore                  0x32fdd9a34         WTF::ParkingLot::parkConditionallyImpl
3   JavaScriptCore                  0x32f614fd8         WTF::Condition::waitUntil<T>
4   JavaScriptCore                  0x32fda6334         WTF::Detail::CallableWrapper<T>::call
5   JavaScriptCore                  0x32fdfd908         WTF::Thread::entryPoint
6   JavaScriptCore                  0x32fe000c8         WTF::wtfThreadEntryPoint
7   libsystem_pthread.dylib         0x3b3f6bbf8         _pthread_start

Thread 36
0   libsystem_kernel.dylib          0x378ab10cc         __psynch_cvwait
1   libsystem_pthread.dylib         0x3b3f6f430         _pthread_cond_wait
2   JavaScriptCore                  0x32fdd9a34         WTF::ParkingLot::parkConditionallyImpl
3   JavaScriptCore                  0x32f614fd8         WTF::Condition::waitUntil<T>
4   JavaScriptCore                  0x32fda6334         WTF::Detail::CallableWrapper<T>::call
5   JavaScriptCore                  0x32fdfd908         WTF::Thread::entryPoint
6   JavaScriptCore                  0x32fe000c8         WTF::wtfThreadEntryPoint
7   libsystem_pthread.dylib         0x3b3f6bbf8         _pthread_start

Thread 37
0   libsystem_kernel.dylib          0x378ab10cc         __psynch_cvwait
1   libsystem_pthread.dylib         0x3b3f6f430         _pthread_cond_wait
2   JavaScriptCore                  0x32fdd9a34         WTF::ParkingLot::parkConditionallyImpl
3   JavaScriptCore                  0x32f614fd8         WTF::Condition::waitUntil<T>
4   JavaScriptCore                  0x32fda6334         WTF::Detail::CallableWrapper<T>::call
5   JavaScriptCore                  0x32fdfd908         WTF::Thread::entryPoint
6   JavaScriptCore                  0x32fe000c8         WTF::wtfThreadEntryPoint
7   libsystem_pthread.dylib         0x3b3f6bbf8         _pthread_start

Thread 38
0   libsystem_kernel.dylib          0x378ab10cc         __psynch_cvwait
1   libsystem_pthread.dylib         0x3b3f6f430         _pthread_cond_wait
2   JavaScriptCore                  0x32fdd9a34         WTF::ParkingLot::parkConditionallyImpl
3   JavaScriptCore                  0x32f614fd8         WTF::Condition::waitUntil<T>
4   JavaScriptCore                  0x32fda6334         WTF::Detail::CallableWrapper<T>::call
5   JavaScriptCore                  0x32fdfd908         WTF::Thread::entryPoint
6   JavaScriptCore                  0x32fe000c8         WTF::wtfThreadEntryPoint
7   libsystem_pthread.dylib         0x3b3f6bbf8         _pthread_start

EOF
</details>

**Comment by mvanroon** [comment]
I believe this issue was fixed in https://github.com/maplibre/maplibre-gl-native/issues/70
However I too am not able to upgrade due to the build errors as mentioned in https://github.com/react-native-mapbox-gl/maps/issues/1472

@naftalibeder Have you found a solution?

**Comment by naftalibeder** [comment]
@mvanroon I have not, unfortunately. (I haven’t tried in a month or so.) If you end up getting it to work, I think we would all appreciate a write-up, and I’ll do the same. :)

**Comment by louwers** [comment]
I am closing this, please re-open if someone has the same problem still.
