### ISSUE TITLE
Architecture Document

### ISSUE THREAD

**Issue by sjg-wdw** [maplibre/maplibre-native#1244]
We need a document describing the architecture we built in comparison to the one we designed.

**Comment by sjg-wdw** [comment]
Needs some figures

**Comment by wipfli** [comment]
Cool! Can you also give a talk about the new architecture at some point?

**Comment by sjg-wdw** [comment]
Yes, as a part of the Mega Merge we will do that.

**Comment by sjg-wdw** [comment]
Still needs figures.
