### ISSUE TITLE
Is MapLibre Gl Native 9.6.0 provides support for download the maps offline ? If yes then please provide documentation for that so we can use it. Thanks 

### ISSUE THREAD

**Issue by NisargHB1831** [maplibre/maplibre-native#1270]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by louwers** [comment]
Yes, it is supported.

No, there is not really good documentation for it right now.

Please feel free to add your ideas to this discussion: https://github.com/maplibre/maplibre-native/discussions/814

**Comment by NisargHB1831** [comment]
> Yes, it is supported.
> 
> No, there is not really good documentation for it right now.
> 
> Please feel free to add your ideas to this discussion: #814

Could you please tell me how to download the offline maps and how to integrate with android. I am more happy if you have sample code regarding this.

**Comment by louwers** [comment]
@NisargHB1831 You can check out the example app: https://github.com/maplibre/maplibre-native/tree/main/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/org/maplibre/android/testapp/activity/offline

The issue tracker is not for Q&A, please use GitHub discussions: https://github.com/maplibre/maplibre-native/discussions/categories/q-a
