### ISSUE TITLE
Is MapLibre Gl Native 9.6.0 provides support for download the maps offline ?  If yes then please provide documentation for that so we can use it.  OR if you have any example for android source code please share with me. Thanks in advance.

### ISSUE THREAD

**Issue by NisargHB1831** [maplibre/maplibre-native#1278]
Is MapLibre Gl Native 9.6.0 provides support for download the maps offline ? 
If yes then please provide documentation for that so we can use it.  OR if you have any example for android source code please share with me.
Thanks in advance.

**Comment by louwers** [comment]
#1270
