### ISSUE TITLE
Handle style changes better

### ISSUE THREAD

**Issue by stefankarschti** [maplibre/maplibre-native#1296]
When the style changes but the same layer ID appears in both, the `RenderLayer` is reused and may see the old buckets after being notified of the change.

**Comment by stefankarschti** [comment]
at style change some layers remain and they should not. Like `geolines` layer from Maplibre Basic style carries over to whatever style comes next

**Comment by sjg-wdw** [comment]
May only apply to things with asynchronous layout (e.g. labels).

**Comment by TimSylvester** [comment]
So you start up with Basic, and then switch to another style that doesn't have these layers, but the `RenderLayer` instances aren't removed?

**Comment by stefankarschti** [comment]
Yes, actually the `TileLayerGroup`s aren't. 
The output above reflects the Translucent pass, I'm still investigating.

**Comment by stefankarschti** [comment]
that is because `RenderLayer::layerRemoved` does not emit a `RemoveLayerGroupRequest` change request.
