### ISSUE TITLE
Using glyphs locally without Tileserver-gl and etc

### ISSUE THREAD

**Issue by wecand0** [maplibre/maplibre-native#1327]
Hello, there is no answer how to use glyphs locally without server, I have managed to use mbtiles locally, like this

```
  "sources": {
    "openmaptiles": {
      "tiles": ["mbtiles:///home/user/planet.mbtiles"],
      "type": "vector"
    }
  }
```

Maps are working, all great, but I STUCKED with glyphs.. How to open it from local storage, I tried like this:

`  "glyphs": "asset://data/glyphs/{fontstack}/{range}.pbf"`

I tried also with full path:

`  "glyphs": "asset:///home/app/data/glyphs/{fontstack}/{range}.pbf"`

Files *.pbf are correct I checked it with tileserver-gl, all fine. But I do not need to user server.
The sample of error:
`Failed to load glyph range 64256-64511 for font stack Open Sans Semibold,Noto Sans Bold:`
I would be very happy if someone helps how to resolve this issue...

**Comment by louwers** [comment]
This was resolved on Slack (font was not available on that location).

Feel free to create a help thread here if you need more assistance: https://github.com/maplibre/maplibre-native/discussions/categories/q-a
