### ISSUE TITLE
CONTRIBUTING.md still refers to mapbox

### ISSUE THREAD

**Issue by xabbu42** [maplibre/maplibre-native#134]
This file is linked when opening a pull request against this repository and is therefore a rather high priority to overwork for maplibre. As I don't know what the contents of that file should be I can't do that myself.

**Comment by matkoniecz** [comment]
file link https://github.com/maplibre/maplibre-gl-native/blob/master/CONTRIBUTING.md

next step would be

>  Mapbox Maps SDK for iOS
>  Mapbox Maps SDK for macOS

as initial step I submitted https://github.com/maplibre/maplibre-gl-native/pull/189
