### ISSUE TITLE
Metal Line Pattern Shader

### ISSUE THREAD

**Issue by alexcristici** [maplibre/maplibre-native#1479]

**Comment by sjg-wdw** [comment]
@alexcristici can you check if this one is working.  I saw it was merged into main.

**Comment by alexcristici** [comment]
Line pattern shader was implemented in this PR https://github.com/maplibre/maplibre-native/pull/1669. I create a style with line patters: https://api.maptiler.com/maps/2f4c4899-e695-4c8b-a4ef-92fa9d2740ff/style.json?key=G4MQXsYbLiUxOu3SV4lh and seems to work correctly.

**Comment by sjg-wdw** [comment]
Thanks!
