### ISSUE TITLE
Android Annotations: copy existing classes & Kotlinify manager classes

### ISSUE THREAD

**Issue by fynngodau** [maplibre/maplibre-native#1492]
[Android annotations API proposal](https://github.com/maplibre/maplibre-native/blob/main/design-proposals/2023-06-17-android-annotations.md) implementation issue as a part of https://github.com/maplibre/maplibre-native/issues/1491

---

First, it makes sense to copy the existing classes into `maplibre-native`, to fix imports, etc., so that we can then continue with modifications. In the same turn, we can Kotlinify the manager classes, as they will not require much attention overall per the proposal.

* Copy existing classes from maplibre annotations plugin
* Resolve problems
* Kotlinify manager classes

**Comment by louwers** [comment]
This ticket is in scope of the Modernization bounty direction. https://github.com/maplibre/maplibre/issues/270

**Comment by louwers** [comment]
@fynngodau Hi Fynn thanks for taking the time to split this up and for working on this.

If you could, for the record, please leave a comment in this ticket and the other tickets that you want to work on these bounties.  🙂

**Comment by fynngodau** [comment]
@louwers Thanks for assigning the bounties, I'll gladly start working on this issue :slightly_smiling_face:

**Comment by louwers** [comment]
This bounty can be paid out.

**Comment by fynngodau** [comment]
Included in this invoice: https://opencollective.com/maplibre/expenses/157775
