### ISSUE TITLE
Android Annotations: add new classes (1)

### ISSUE THREAD

**Issue by fynngodau** [maplibre/maplibre-native#1493]
[Android annotations API proposal](https://github.com/maplibre/maplibre-native/blob/main/design-proposals/2023-06-17-android-annotations.md) implementation issue as a part of https://github.com/maplibre/maplibre-native/issues/1491

---

Implement the new classes (and required additional classes) specified in the proposal for `Symbol`.

* These classes should be implemented and should be usable.
* At this point, only one manager per type needs to be created; automatic grouping will be implemented in a later issue (#1494).
* For the same reason, only data driven properties should be added to the classes. Non data-driven properties will be added later on.
* `CollisionGroup` and `ClusterGroup` are added in later issues (#1495, #1496).
* Dragging and click listeners will be added in a later issue (#1634).

**Comment by louwers** [comment]
This ticket is in scope of the Modernization bounty direction. https://github.com/maplibre/maplibre/issues/270

**Comment by fynngodau** [comment]
@louwers After the first issue is solved, I'll gladly start working on this one.

**Comment by fynngodau** [comment]
@louwers This issue has turned out to be more work than anticipated. For this reason, I propose to move the following sub-tasks to new issues with the following bounty sizes:

* Click, drag, long-click listeners (S)
* `Line`, `Circle`, `Fill` (M)

The following sub-tasks should be moved to existing issue:

* Cleaning up no longer needed bitmaps → https://github.com/maplibre/maplibre-native/issues/1494; the trivial implementation would cause bugs as soon as multiple managers are required.

Passing tests based on `SymbolManagerTest` will still part of the scope of this issue.

**Comment by louwers** [comment]
Thanks for making a suggestion for this @fynngodau.

Please create / update the issues like you suggest and update #1491, I can assign the bounties.

**Comment by louwers** [comment]
This bounty can be paid out.

**Comment by fynngodau** [comment]
Is included in this invoice: https://opencollective.com/maplibre/expenses/162741
