### ISSUE TITLE
Android Annotations: automatic grouping

### ISSUE THREAD

**Issue by fynngodau** [maplibre/maplibre-native#1494]
[Android annotations API proposal](https://github.com/maplibre/maplibre-native/blob/main/design-proposals/2023-06-17-android-annotations.md) implementation issue as a part of https://github.com/maplibre/maplibre-native/issues/1491

---

Add automatic grouping by non data-driven properties and by Z layer. For this, the non data-driven properties themselves need to be added in the first place.

* Add non data-driven properties
* Add automatic grouping into manager objects by Z layer and by non data-driven properties as specified in the proposal
* Grouping should run in O(n log n) with n as the amount of annotations
* Add support for cleaning up no longer needed bitmaps

**Comment by louwers** [comment]
This ticket is in scope of the Modernization bounty direction. https://github.com/maplibre/maplibre/issues/270

**Comment by fynngodau** [comment]
On second thought, adding the grouping algorithm that I had in mind adds a large amount of code for possibly little benefit, as the grouping algorithm in Kotlin's `groupBy` method has a bad runtime only if there _lots_ of different groups are spawned. I think we should probably delay asymptotically more efficient grouping until all things are in place.

This would that assigning a different z layer value to each symbol is not a supported use case at first. What do you think @louwers?

**Comment by louwers** [comment]
Sure. We can always swap out the algorithm later.

**Comment by louwers** [comment]
This bounty can be paid out.

**Comment by fynngodau** [comment]
Included in https://opencollective.com/maplibre/expenses/193947.
