### ISSUE TITLE
make ios error: WorkspaceSettings.xcsettings

### ISSUE THREAD

**Issue by sunny0092** [maplibre/maplibre-native#1542]
**Describe the bug**
I used the make ios command, and this error appeared, it seems that in ios there is no platform folder like before.

**To Reproduce**
cd platform/ios
make ios
Error: make: *** No rule to make target `platform/ios/WorkspaceSettings.xcsettings', needed by `platform/ios/ios.xcworkspace/xcuserdata/sangnguyen.xcuserdatad/WorkspaceSettings.xcsettings'.  Stop.

**Comment by louwers** [comment]
Please follow the updated build instructions: https://github.com/maplibre/maplibre-native/blob/main/platform/ios/README.md#developing
