### ISSUE TITLE
Missing instructions to build MapLibre iOS App

### ISSUE THREAD

**Issue by JuLink** [maplibre/maplibre-native#1544]
**Describe the bug**
[The documentation](https://github.com/maplibre/maplibre-native/blob/main/platform/ios/README.md) to build the MapLibre iOS app directly from the repo is missing some steps.

**To Reproduce**
Follow the documentation up until the instruction "Try to run the example App in the simulator and on a device to confirm your setup works.".
In my case the build was failing first because it was missing `node` (`/bin/bash: node: command not found`). After installing node via `brew` the build was failing again saying I was missing the module `argparse` (`Error: Cannot find module 'argparse'`).

**Expected behavior**
The app should build without any other steps and/or they should be indicated in the README.md file.

**Screenshots**
<img width="1437" alt="missing_node" src="https://github.com/maplibre/maplibre-native/assets/1457215/96239d49-fd3f-494e-aec2-f720cac557da">
<img width="1454" alt="missing_argparse" src="https://github.com/maplibre/maplibre-native/assets/1457215/9d4a9b77-7f7c-4014-8fc1-9951f2e63d96">

**Platform information (please complete the following information):**
 - OS: iOS
 - Platform iOS
 - Version `main` branch

**Additional context**
I've solved the issue by installing node via `brew install node` and executing `npm install` or `npm ci --ignore-scripts` from the directory `platform/ios`  (I did both and the first one failed but I'm not sure it did not do anything).

I'm not familiar enough with Basel and Node (I've never used them), I assume the steps should be added in the Basel configuration somewhere but I can't find where exactly that is why I did not open a PR.

**Comment by louwers** [comment]
Good catch, Node.js indeed needs to be installed.

**Comment by JuLink** [comment]
Yes, I did make it run using this command 👍🏻

Should it be added in the documentation or is it something that should be added in the bazel config ?

**Comment by louwers** [comment]
Ideally Bazel takes care of all dependencies. In the case of Node.js we could use https://github.com/bazelbuild/rules_nodejs

But support is not first class so I think it's OK to just require manual install for now.

**Comment by boscojwho** [comment]
I've encountered a similar issue after following the same documentation:
- I was able to get past the `argparse` error after running `npm install --ignore-scripts` in the root directory.
- But I can't get past this `Cannot find module 'node:path'` error, even though `path 0.12.7` is installed in `node_modules` (I also have it installed globally):
<img width="1138" alt="Screenshot 2023-09-01 at 3 42 59 PM" src="https://github.com/maplibre/maplibre-native/assets/2549615/21092388-67f7-479f-8cf1-2c8a3f095c76">

- I've also tried running `rm -rf node_modules` before running `npm install --ignore-scripts`.

Appreciate any help (never used Bazel before/not the most familiar with Node).

**Comment by louwers** [comment]
@boscojwho What version of Node.js do you have installed?

You need Node.js 16 or above for `node:path`.

**Comment by boscojwho** [comment]
> @boscojwho What version of Node.js do you have installed?
> 
> You need Node.js 16 or above for `node:path`.

Why, of course =P (runs off back to iOS land) Not sure if my other machine has node.js 16, but I got it past this issue on another machine that has it.

**Comment by boscojwho** [comment]
After following the setup instructions, project is missing Info-app/Info-benchmark plist files, and fails to build.
<img width="1792" alt="Screenshot 2023-09-01 at 9 03 25 PM" src="https://github.com/maplibre/maplibre-native/assets/2549615/370c2702-b943-4b8c-8c13-35105fba2e5b">

Also, none of the expected simulator options appear in Xcode 14.
<img width="319" alt="Screenshot 2023-09-01 at 9 07 06 PM" src="https://github.com/maplibre/maplibre-native/assets/2549615/a6952cb2-a485-4778-87b7-3bc9f9fbb325">

Will see if I can figure it out another time, lol

**Comment by louwers** [comment]
@boscojwho The benchmark app is a relatively recent addition to the build config. We'll have a look at it. Try the test app in the meantime.
