### ISSUE TITLE
Can XCode include the GLSL files for perusal.

### ISSUE THREAD

**Issue by sjg-wdw** [maplibre/maplibre-native#1549]
Right now we can't see them in the Xcode project and it would be convenient for developers.

**Comment by louwers** [comment]
Files can be added to the `extra_files` filegroup to show up in Xcode.

https://github.com/maplibre/maplibre-native/blob/d82f722a68030a7d3fd6b2ef702b4a62cc6fc037/platform/ios/BUILD.bazel#L243-L254

Closing this because I don't think GLSL files are still relevant.
