### ISSUE TITLE
Visual glitches on the map when run in iOS Simulator

### ISSUE THREAD

**Issue by r3econ** [maplibre/maplibre-native#1558]
**Describe the bug**

When `MGLMapView` is used in a SwiftUI project and run on iOS simulator, visual glitches make debugging hard or impossible.

**To Reproduce**

1. Create a SwiftUI project 
2. Add `MGLMapView` to view hierarchy wrapping it using `UIViewRepresentable`
3. Run it on the iOS Simulator
4. You will see visual glitches, especially when panning or zooming

**Expected behavior**
- `MGLMapView` should not show visual glitches in iOS Simulator

**Screenshots**

<img width="382" alt="SCR-20230823-pmqy" src="https://github.com/maplibre/maplibre-native/assets/505054/5c8655e1-089a-4d44-9853-7648a499968a">

**Platform information:**
 - OS: iOS 16.4
 - Platform: iOS Simulator
 - Version iOS 16.4, maplibre-gl-native-distribution v5.0, Xcode Version 14.3.1 (14E300c)

**Comment by louwers** [comment]
This is a known problem. Apple is not going to fix this because they deprecated OpenGL.

By the end of the year we will use Metal as a rendering backend on iOS, and using a simulator for development should be good again. Please use an iOS device for debugging/development in the meantime.
