### ISSUE TITLE
Remove spaces from glyph file names metrics

### ISSUE THREAD

**Issue by louwers** [maplibre/maplibre-native#1599]
The file `metrics/integration/glyphs/Open Sans Semibold,Arial Unicode MS Bold/0-255.pbf` contains spaces. We should get rid of them. When the Linux render test with Bazel this results in the following error (Bazel does not support runfiles with spaces):

`/home/runner/.cache/bazel/_bazel_runner/install/edecd2b1233e0abfae42ec33ee10b762/build-runfiles (args bazel-out/k8-fastbuild/bin/render-test/render-test.runfiles_manifest bazel-out/k8-fastbuild/bin/render-test/render-test.runfiles): link or target filename contains space on line 669: 'Maplibre/metrics/integration/glyphs/Open Sans Semibold,Arial Unicode MS Bold/0-255.pbf /home/runner/work/maplibre-native/maplibre-native/metrics/integration/glyphs/Open Sans Semibold,Arial Unicode MS Bold/0-255.pbf'`

**Comment by wipfli** [comment]
Isn't that the default font name? In case yes, then you would probably have to change some styles, right?

**Comment by louwers** [comment]
@wipfli Yes I think so. Yes we have to add the font explicitly in a bunch of places I think.
