### ISSUE TITLE
Fix 454 deprecation warnings when compiling UI Tests

### ISSUE THREAD

**Issue by louwers** [maplibre/maplibre-native#1607]
```
cd platform/android
make android-ui-test-arm-v8
```

Results in 454 deprecation warnings: https://gist.githubusercontent.com/louwers/96d0a493e96304606caa1d4c798515f5/raw/15e688aa85321c808688f50e9feb05f9864606ab/deprecations.md

**Comment by tarkvara** [comment]
I @louwers, I'm going to be working on this as my first issue.

**Comment by louwers** [comment]
This bounty can be paid out. Bounty direction: https://github.com/maplibre/maplibre/issues/270
