### ISSUE TITLE
Modularized Renderer: Android Beta Testing

### ISSUE THREAD

**Issue by louwers** [maplibre/maplibre-native#1608]
The internals of MapLibre Native have received a big [redesign](https://github.com/maplibre/maplibre-native/blob/main/design-proposals/2022-10-27-rendering-modularization.md). This brings many advantages to the project, most notably that it allows for other rendering backends, but aside from that we expect performance gains, and much better extendibility. 

This is the future of MapLibre. Eventually, the code of the legacy renderer will be removed. Therefore it is very important that all users of MapLibre Native pitch in to test the pre-releases of MapLibre Native that will include this new renderer.

Is the functionality that is important for you still working? Are there any problems with the styles that you use? Do you see any performance regressions? We have a lot of tests, but the real test is trying it out in real projects.

The pre-release for MapLibre Native Android 11.0.0 is [out now](https://github.com/maplibre/maplibre-native/releases/tag/android-v11.0.0-pre0)!

```gradle
dependencies {
        implementation("org.maplibre.gl:android-sdk:11.0.0-pre4")
}
```

## Reporting Issues

When [report an issue](https://github.com/maplibre/maplibre-native/issues/new), the following are required:

- Style: If your style is public or can be made available, that will help a lot.
- Lat / Long / Zoom: Where exactly does the issue occur?
- Screenshot
- Android version
- Device

When available:

- Stack Trace / Metal Error / Core Dump
- Minimal style: Can you provide a minimal style that reproduces the issue?

**Comment by louwers** [comment]
@mtpdog Please subscribe to this thread (you should be now that you left a message). I will post a message here to notify you once it is released.

If you want to build it yourself ahead of the pre-release:

```
cd platform/android
./gradlew assembleDrawable
```

**Comment by louwers** [comment]
The MapLibre Native Android 11.0.0 pre-release is out now. Please see the [changelog](https://github.com/maplibre/maplibre-native/releases/tag/android-v11.0.0-pre0).

There have been changes to the internal rendering architecture, so please check if your application / style still works correctly and report any issues you enounter. Instructions for reporting issues are in the [first post](https://github.com/maplibre/maplibre-native/issues/1608#issue-1882485128).

**Comment by michalgwo** [comment]
Do you plan to update also [maplibre-plugins-android](https://github.com/maplibre/maplibre-plugins-android) and [maplibre-navigation-android](https://github.com/maplibre/maplibre-navigation-android)? I'm not able to run the new maplibre-native version with old versions of these libraries, as they require classes from `com.mapbox.mapboxsdk` package. 

For example in the annotation plugin to create SymbolManager `SymbolManager(b.mapView, map, style)`, all parameters requires `com.mapbox.mapboxsdk` package, which is not available in the new MapLibre version.

One example in maplibre-navigation-android would be creating LocationComponentActivationOptions:
```
LocationComponentActivationOptions.builder(this, style)
    .locationComponentOptions(locationComponentOptionsBuilder.build())
    .locationEngine(LocationEngineProvider.getBestLocationEngine(this))
    .locationEngineRequest(locationEngineRequest)
    .build()
```

`.locationEngine()` requires maplibre package, but `LocationEngineProvider.getBestLocationEngine(this)` returns mapbox package

**Comment by louwers** [comment]
@michalgwo Absolutely. I created two issues:

https://github.com/maplibre/maplibre-navigation-android/issues/104

https://github.com/maplibre/maplibre-plugins-android/issues/49

I'll have a look at it before the final release if no-one else picks it up.

**Comment by louwers** [comment]
`org.maplibre.gl:android-sdk:11.0.0-pre2` was released which includes the Asynchronous GeometryTile deletion (#2051) PR.

**Comment by louwers** [comment]
Please use `org.maplibre.gl:android-sdk:11.0.0-pre3` from [Maven Central](https://central.sonatype.com/artifact/org.maplibre.gl/android-sdk/versions) as `11.0.0-pre2` was a Debug build by accident (still fixing the automated release pipeline).

**Comment by westnordost** [comment]
I found something peculiar in 11.0.0-pre4. Didn't test if it is reproducible in 10.x

Occurs quite rarely, maybe if the tile just loaded?

Buildings in the style used fade out at a certain zoom level. You see in the video that this works, but the color is missing (so it is black):

https://github.com/maplibre/maplibre-native/assets/4661658/3e0df631-6260-4674-bbb7-e29b0f584b60

**Comment by louwers** [comment]
@westnordost That doesn't look right. Also when you zoom in to new areas I see it getting darker for a split second until the tiles are loaded.

Another issue with the location layer popped up:

https://github.com/maplibre/maplibre-native/issues/2216

So it looks like we need to hold off on the 11.0.0 release for a bit longer.

**Comment by louwers** [comment]
@westnordost Does this look kind of similar? https://github.com/maplibre/maplibre-native/issues/2217

**Comment by westnordost** [comment]
Hm, it looks a bit similar, but this issue I can only reproduce when zooming out. #2217 I have not seen yet at all.

Might be style-specific?

In case it is relevant, the style used in the app is https://github.com/streetcomplete/maplibre-streetcomplete-style

The app adds some additional layers, but e.g. the layer with the rendering bug is not modified by the app in any way.

**Comment by louwers** [comment]
@westnordost Could you try [the new pre-release](https://github.com/maplibre/maplibre-native/releases/tag/android-v11.0.0-pre6) and check if the zooming issue has been fixed?

**Comment by louwers** [comment]
The 11.0.0 release is out. https://github.com/maplibre/maplibre-native/releases/tag/android-v11.0.0

Thanks to everyone that helped with testing.
