### ISSUE TITLE
Metal Renderer: iOS & macOS Early Access

### ISSUE THREAD

**Issue by louwers** [maplibre/maplibre-native#1609]
>**Warning**
> Metal on iOS is not production-ready yet. But we are interested to hear your feedback!

<p align="center">
  <img width="30%" src="https://maplibre.org/news/2023-03-23-metal-project-team-started/screenshot.png">
</p>

Long-awaited Metal support MapLibre Native has landed! You can download a [pre-release](https://github.com/maplibre/maplibre-native/releases) (in the form of an XCFramework) and use it in your project. More details [below](https://github.com/maplibre/maplibre-native/issues/1609#issuecomment-1729586249).  We are working on an automated release to the Swift Package Index and to Cocoapods.

This thread is used to coordinate testing.

## Changes

- The internal rendering architecture of MapLibre Native has been overhauled. Please refer to the following documents for more details:
  - [Rendering Modularization Design Proposal](https://github.com/maplibre/maplibre-native/blob/main/design-proposals/2022-10-27-rendering-modularization.md)
  - [Metal Port Design Proposal](https://github.com/maplibre/maplibre-native/blob/main/design-proposals/2022-11-29-metal-port.md)
  - [Rendering Modularization Design Results](https://docs.google.com/document/d/1QtsUgDyD-Rt1McvJFz7HbHvEKli3tRVfxdW7fLDF-g8/edit#heading=h.dwpgby211stb) (recent)
- The prefix `MGL` has been changed to `MLN`. See the example below.
- The iOS SDK has received very little changes otherwise, with the exception that (custom) OpenGL layers are (obviously) no longer supported. A new way to write custom layers is in the works (https://github.com/maplibre/maplibre-native/issues/1272).

## Usage Instructions

See [this comment](https://github.com/maplibre/maplibre-native/issues/1609#issuecomment-1729586249).

## Known Issues

- 4 render tests are failing. https://github.com/maplibre/maplibre-native/issues/1899
- Snapshotter functionality still needs to be implemented. https://github.com/maplibre/maplibre-native/issues/1862 

[All issues with metal + bug labels](https://github.com/maplibre/maplibre-native/issues?q=is%3Aopen+is%3Aissue+label%3Ametal+label%3Abug+)

## Reporting Issues

When [report an issue](https://github.com/maplibre/maplibre-native/issues/new), the following are required:

- Style: If your style is public or can be made available, that will help a lot.
- Lat / Long / Zoom: Where exactly does the issue occur?
- Screenshot
- iOS version
- MapLibre Native version
- Device

When available:

- Stack Trace / Metal Error / Core Dump
- Minimal style: Can you provide a minimal style that reproduces the issue?

**Comment by sjg-wdw** [comment]
I still think "early access" sounds cooler.

**Comment by louwers** [comment]
@sjg-wdw Fixed. 😄

**Comment by ianthetechie** [comment]
✌️

**Comment by georgbachmann** [comment]
Sweet

**Comment by nnhubbard** [comment]
Sounds good!

**Comment by birkskyum** [comment]
When trying to build myself, in the `bazel build` step I get these two errors:

```sh
ERROR: /Users/admin/repos/maplibre-native/BUILD.bazel:89:11: Compiling src/mbgl/util/http_header.cpp failed: (Exit 1): wrapped_clang_pp failed: error executing command (from target //:mbgl-core) external/local_config_cc/wrapped_clang_pp '-D_FORTIFY_SOURCE=1' -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -O0 -DDEBUG '-std=c++11' ... 

vendor/boost/include/boost/container_hash/hash.hpp:130:33: error: no template named 'unary_function' in namespace 'std'; did you mean '__unary_function'?
        struct hash_base : std::unary_function<T, std::size_t> {};
                           ~~~~~^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS17.0.sdk/usr/include/c++/v1/__functional/unary_function.h:46:1: note: '__unary_function' declared here
using __unary_function = __unary_function_keep_layout_base<_Arg, _Result>;
^
```

**Comment by louwers** [comment]
@birkskyum Ah yes. Known issue with Xcode 15 right now.

We are in the process of updating Boost, which will resolve this issue. In the meantime, you can use an older Xcode version or go to the file where it errors and change `unary_function` to `__unary_function` as a quickfix.

**Comment by birkskyum** [comment]
@louwers , sound good. Do you have a tip for the `bazel run` issue as well?

**Comment by louwers** [comment]
@birkskyum Command had a typo. Try again.

**Comment by ianthetechie** [comment]
Hey, hey! Big thanks to everyone who made this possible! 🚀 

A few notes from me to any other devs wanting to hack on this. The instructions from @louwers are absolutely applicable to most cases, but if you're weird like me and happen to be developing an Swift package (not an app target but a library for redistribution) that itself depends on MapLibre, here's how to get it into your Swift package:

1. Download a pre-release as noted.
2. Compute its checksum: `swift package compute-checksum Downloads/MapLibre.dynamic.xcframework.zip`. Suggestion: could we auto-compute this checksum in release pipelines? The only reason a Swift packager needs to do steps 1-2 is to get this.
3. In your `Package.swift` file, add a binary target to your `targets` list like so, using the URL of the XCFramework from the GitHub release and the checksum you computed in step 2:

```swift
.binaryTarget(name: "MapLibre",
                      url: "https://github.com/maplibre/maplibre-native/releases/download/ios-v6.0.0-predd74d1e84a781a41691cfd0de592d153c8795b65/MapLibre.dynamic.xcframework.zip",
                      checksum: "0a9c5a898f699e4acaa1650761f8908213fb5d638c389ed714a2f784349dd3b8")
```

4. Make sure to add `.target(name: "MapLibre"),` to the dependencies of any targets in your package that need MapLibre.

For a complete working example, I've updated the [MapLibre SwiftUI DSL](https://github.com/stadiamaps/maplibre-swiftui-dsl-playground). The process took less than 10 minutes ;) Big thanks again for all the work that went into the release process!

**Comment by username0x0a** [comment]
Tried in our full-fledged app 👀 the performance's not great (at least in the Simulator) when compared to our `MetalANGLE`-wrapped package, but that's understandable as it's WIP, yet the integration was flawless (except for some calls to downstream changes we do in the library), looking for further progress! 🙌 🎉

**Comment by halset** [comment]
Thank you for the good work on Metal Renderer. It looks correct here in the Simulator on a pretty complex vector tile map. The hill shade in this map is a raster layer with PNGs with pre-rendered hill shade. The hill shade laggs a bit when panning the map with the Metal Renderer, but the vector map is not laggy. This looks like a very good start from my perspective at least. Promising!
![Simulator Screenshot - iPad mini (6th generation) - 2023-09-22 at 13 39 57](https://github.com/maplibre/maplibre-native/assets/445229/04e94582-a6d1-442a-a626-add6609d5514)

**Comment by georgbachmann** [comment]
It looks very promising! After a certain zoom level it seems not render everything any more, but with my map (also a raster hillshade-layer and a LOT of layers) renders ok. Performance is not as it used to be, but I'd say good start! Awesome work!!!

![Screenshot 2023-09-22 at 13 50 03](https://github.com/maplibre/maplibre-native/assets/893113/b4dc5215-5fd5-48a7-b1b5-c054319b25ab)

**Comment by birkskyum** [comment]
Does the Bazel scripts need a refactor before this can be used with macOS?

**Comment by JesseCrocker** [comment]
There seems to be some significant issues with annotations.

After adding MLNPolyline Annotations it takes about 2 seconds to show up.

Point annotations show up faster, but when panning the map it seems to take a second before the map starts to move, then moves smoothly, but the annotation seems to wander a little bit.

I dont have a test project for this, but can come up with one if needed.

**Comment by sjg-wdw** [comment]
> There seems to be some significant issues with annotations.
> 
> After adding MLNPolyline Annotations it takes about 2 seconds to show up.
> 
> Point annotations show up faster, but when panning the map it seems to take a second before the map starts to move, then moves smoothly, but the annotation seems to wander a little bit.
> 
> I dont have a test project for this, but can come up with one if needed.

I'm not sure how much testing we do with annotations.  @stefankarschti does one of our test cases cover that?

**Comment by stefankarschti** [comment]
I don't think any of the cases covered annotation performance specifically, but I'm looking into it.

**Comment by stefankarschti** [comment]
> There seems to be some significant issues with annotations.
> 
> After adding MLNPolyline Annotations it takes about 2 seconds to show up.
> 
> Point annotations show up faster, but when panning the map it seems to take a second before the map starts to move, then moves smoothly, but the annotation seems to wander a little bit.
> 
> I dont have a test project for this, but can come up with one if needed.

@JesseCrocker : about how many polylines / points are you adding?

**Comment by JesseCrocker** [comment]
2 point annotations and 1 line with 2 points on top of the openmaptiles default style.

I can post a sample project tomorrow to verify the issue.

**Comment by stefankarschti** [comment]
Thanks!
I'm using the "Add Test Shapes" function from "App" to add a various set of annotations.

**Comment by tomasharkema** [comment]
Awesome! In conjunction with the porting of MapLibre Navigation iOS library for Flitsmeister, I took the liberty to open a branch using this metal implementation.

https://github.com/maplibre/maplibre-navigation-ios/tree/feature/spm-metal

**Comment by sjg-wdw** [comment]
Quick update on the Metal support.

We've got a version that's pretty close to OpenGL performance.
If the last version you grabbed was 3x or 4x, this one is closer to 1x, so give it a look and let us know what you find.

We're continuing to pursue performance improvements, but we'd love to find the corner cases if you have one.

**Comment by username0x0a** [comment]
@sjg-wdw I'll try it on an app that relies on & utilises custom annotations quite a lot 👍 I think the stress options in the example app were quite useful 😁 and I'll cross-test it against a `MetalANGLE`-routed fork we use right now. 👀 Just waiting for another build. 🙏

**Comment by louwers** [comment]
@username0x0a The latest build is 3 days old and contains the most recent changes for iOS. 🍞 

https://github.com/maplibre/maplibre-native/releases?q=ios&expanded=true

**Comment by username0x0a** [comment]
Okay, I did a quick test in the Simulator ('cause that's the most usable for actual performance comparison) and [I made some recordings](https://drive.google.com/drive/folders/17kkElIuCPo_PuuOlcft1JUafNtOecvTC?usp=share_link) of both the Metal Native & MetalANGLE binaries.

With the **Metal Native** one, I'm experiencing tearing, when navigating around it occasionally freezes for up to a second (during swipe-moving around), also there's some visual glitching/tearing what seems to be around the tile boundaries. 🤔 FPS definitely still lower as well.

The **MetalANGLE** is really swifty, that's why we've settled with it for quite some time even in production.

The annotations alone are not part of the tiles data & are loaded asynchronously (from an API serving sorta-tiled Places infos – that is, ID, name + coords), usually 4–16 tiles (up to 64 annotations each, not all added to the map) are fetched (if not cached already), there's also an animation of the annotation as well as fade-in of a thumbnail image over the icon-font symbol layer once it's loaded. 😄 So quite a good case for a production app benchmark.

Hope you find this quick info useful. 👍

You can also try our [MetalANGLE XCFramework binary](https://sygic-travel-dist.s3.amazonaws.com/ios/libs/Mapbox-5.9.0.zip) just to have it side-by-side as a comparison, it's basically what used to be here in the obsoleted [Metal support PR](https://github.com/maplibre/maplibre-native/pull/369) – should be replaceable in a testing project linking the `xcframework` with no changes needed.

**Comment by ianthetechie** [comment]
Good work @sjg-wdw! I'll do some more extensive testing over the coming days, but so far it looks like the rendering accuracy problems I had with the initial releases are solved!

**Comment by acalcutt** [comment]
I would love any suggestions on getting to node macos build working. I was seeing if I could get this to work in the cmake based process in https://github.com/maplibre/maplibre-native/pull/1793 by setting the options for metal rendering and restoring the macos cmake file that builds the node libs, but it doesn't quite build.

Other than restoring the existing cmake process, could this bazel build generate the node lib files, do what https://github.com/maplibre/maplibre-native/blob/main/platform/node/CMakeLists.txt does after building the macos components?

**Comment by sjg-wdw** [comment]
We're just starting to look at reviving the MacOS version.  Give us a week or two and see where it's at.

**Comment by username0x0a** [comment]
@sjg-wdw

I've uploaded another pair of vids from the device (prefixed `device-*`). 👍

The syncing issue is probably an important one here, indeed. Tearing & frame drops can be seen in zooming (quite a lot) as well as swiping around, often the map (I guess?) finishes the transition where annotations are a bit slower, sometimes resulting in tearing.

The tile glyphs aren't present on the device (maybe some occasional flashing of the whole map layer), curiously.

Clear map performance is better on sight, but the tearing issues are still there, most notably when zooming in & out extensively.

`MetalANGLE` stats: FPS almost constant 60, CPU topping around 50%
`Metal Native` stats: FPS between 35–55-60, CPU topping around 75% with higher mean average

I'd definitely concentrate on the Simulator, too. For once, it's visibly more prone to performance issues, plus imagine that devs usually better spend their time during development day in the Simulator. 😅 Which is luckily way speedier than before when using Metal top-to-bottom.

Also I believe there are many projects utilising annotations, annotation clusters, custom shapes, etc. as by far not all data (if any even, if one uses external tiles provider) can be served via tiles, might not be even usable if the presented data are very dynamic/needs complex local filters and more.

**Comment by sjg-wdw** [comment]
Thanks!  Those are excellent examples.

**Comment by georgbachmann** [comment]
May I ask about the state of macOS? I am building a little internal analysis tool and would love to try it out. The pre-release versions seem not to contain macOS slices yet?

**Comment by sjg-wdw** [comment]
We haven't put MacOS support back yet, but soon.

**Comment by halset** [comment]
Will it be possible to hook in to the Metal Renderer to draw custom dynamic non-tiled data by code?

**Comment by sjg-wdw** [comment]
That's the intent of the Custom Layer support.

**Comment by ianthetechie** [comment]
@sjg-wdw just curious if there's any movement on macOS support yet ;)

**Comment by sjg-wdw** [comment]
January now it looks like.

**Comment by louwers** [comment]
I set up automated releases to Swift Package Index and CocoaPods.

If you use the Swift Package Manager, maybe someone can test the pre-release that was made. I don't think it is possible to depend on a pre-release with Xcode, but if you use a `Package.swift` file you can add:

```
    dependencies: [
        .package(url: "https://github.com/maplibre/maplibre-gl-native-distribution.git", from: "6.0.0-pre9599200f2529de44ba62d4662cddb445dc19397d")
    ],
```

For CocoaPods the pre-release version available is `6.0.0-pre1811e91e3d40d14c860e9ff4e53d95fae68945c7`. If any CocoaPods user could try it out and report back that would be great.

**Comment by ianthetechie** [comment]
Thanks @louwers! I just tested it out with our Swift package and it appears to be working.

**Comment by r3econ** [comment]
I followed the steps to include the framework in my iOS app. I used this [prerelease]([ios-v6.0.0-preab83392d13e3b4259e8faa9db56ab17671aa112e](https://github.com/maplibre/maplibre-native/releases/tag/ios-v6.0.0-preab83392d13e3b4259e8faa9db56ab17671aa112e)).

I'm getting an error:

> There is no Info.plist found at '..../MapLibre.dynamic.xcframework/Info.plist'.

Is there something I'm missing to make it work?

**Comment by louwers** [comment]
@r3econ The .zip is called MapLibre.dynamic.xcframework.zip. This contains a directory called MapLibre.dynamic.xcframework, the actual .xcframework is indide this directory. This is a bit confusing... Please try to use the .xframework inside the directory, and it should work. Let us know.

**Comment by louwers** [comment]
Thanks for trying out the pre-releases everyone!

We are planning on making the official  release of MapLibre Native for iOS with Metal support [tomorrow](https://github.com/maplibre/maplibre-native/issues/2021).

**Comment by louwers** [comment]
@georgbachmann If you want to work on it, pull request welcome. But it's not something I plan to work on.
