### ISSUE TITLE
Android Annotations: add click and drag listeners

### ISSUE THREAD

**Issue by fynngodau** [maplibre/maplibre-native#1634]
[Android annotations API proposal](https://github.com/maplibre/maplibre-native/blob/main/design-proposals/2023-06-17-android-annotations.md) implementation issue as a part of https://github.com/maplibre/maplibre-native/issues/1491

---

Add click, drag, and long-click listeners.

* Kotlinify `DraggableAnnotationController`.
* Items should be draggable if `draggable` is set to `true`.
* The click and long-click listeners addable to the individual markers should work.
* Tests for `DraggableAnnotationListener` should pass.

**Comment by louwers** [comment]
This ticket is in scope of the Modernization bounty direction. https://github.com/maplibre/maplibre/issues/270

**Comment by louwers** [comment]
This bounty can be paid out.

**Comment by fynngodau** [comment]
Included in https://opencollective.com/maplibre/expenses/193947.
