### ISSUE TITLE
Android Annotations: add new classes (2)

### ISSUE THREAD

**Issue by fynngodau** [maplibre/maplibre-native#1635]
[Android annotations API proposal](https://github.com/maplibre/maplibre-native/blob/main/design-proposals/2023-06-17-android-annotations.md) implementation issue as a part of https://github.com/maplibre/maplibre-native/issues/1491

---

Implement the new classes (and required additional classes) specified in the proposal for `Fill`, `Circle`, `Line`.

* These classes should be implemented and should be usable.
* At this point, only one manager per type needs to be created; automatic grouping will be implemented in a later issue (#1494).
* For the same reason, only data driven properties should be added to the classes. Non data-driven properties will be added later on.

**Comment by louwers** [comment]
This ticket is in scope of the Modernization bounty direction. https://github.com/maplibre/maplibre/issues/270

**Comment by louwers** [comment]
This bounty can be paid out.

**Comment by fynngodau** [comment]
Included in https://opencollective.com/maplibre/expenses/162741.
