### ISSUE TITLE
Metal Data Driven GPU Shader Calculations

### ISSUE THREAD

**Issue by sjg-wdw** [maplibre/maplibre-native#1652]
This is an exploration task.  What data driven calculations can we practically do on the GPU?

Let's start with the basic ones, like a linear or exponential calculation with zoom or another single values as input.
Can we figure out when that's happening from the expression hairball?
Can we encode that logically for the shader the figure out?
Which ones will work and which ones are too much effort?

**Comment by alanchenboy** [comment]
Line data is fixed in the current workflow, zoom parameters mostly come from uniform. unless the zoom value depends on features, like the line match expression.

```
        auto lineLayer = std::make_unique<mbgl::style::LineLayer>("line", "lineCustom");
        using namespace mbgl::style::expression::dsl;
        mbgl::style::expression::Match<std::string>::Branches expMaps;
        expMaps["aa"] = literal(2.0);
        expMaps["cc"] = literal(1.0);
        auto match = std::make_unique< mbgl::style::expression::Match<std::string>>(mbgl::style::expression::type::Number, get("name"), expMaps, literal(20.0));
        lineLayer->setLineWidth(mbgl::style::PropertyExpression<float>(interpolate(exponential(1.2), zoom(), 0.0, std::move(match), 10.0, literal(100.0))));
```
This is an example for line width, a_width will be stored in vertex, cause it is not a unique one for the layer, it depends on the features' properties.

All the data will be calculated at the worker thread. I think the whole line triangulation may be an entry point for Shader Calculations.

**Comment by TimSylvester** [comment]
Is the `get("name")` there matching against a per-feature property?  Anything where the value could change per feature will be excluded from this feature and fall back on the existing attribute method.

We'll only be affecting very simple expressions, initially just zoom steps and/or linear interpolation.  Expanding to other cases like allowing use of pitch, min/max, sin/cos/sqrt, multiplication operators, etc., should be based on an analysis of usage.  And the size of the expression will be strictly limited to fit in a small fixed number of elements in a UBO.

**Comment by sjg-wdw** [comment]
That's an interesting case.  So they did think a little bit about this when they implemented it.

**Comment by sjg-wdw** [comment]
We got our results on this one.
