### ISSUE TITLE
Replace Boost Locale

### ISSUE THREAD

**Issue by mwilsnd** [maplibre/maplibre-native#1675]
Boost locale isn't header only and fails to link as a result on Windows, we either need to vendor Boost in a different way or replace it with something else.

**Comment by mwilsnd** [comment]
One possible replacement: https://github.com/nemtrif/utfcpp

**Comment by SiarheiFedartsou** [comment]
May be use `<codecvt>` from STL? Yes, it is deprecated and we even have an [issue](https://github.com/maplibre/maplibre-native/issues/1269) to get rid of it, but it is still supported and this way we won't need any dependencies.

**Comment by SiarheiFedartsou** [comment]
> May be use `<codecvt>` from STL? Yes, it is deprecated and we even have an [issue](https://github.com/maplibre/maplibre-native/issues/1269) to get rid of it, but it is still supported and this way we won't need any dependencies.

Or may be even use ICU 🤔

**Comment by louwers** [comment]
@SiarheiFedartsou Yes we switched to ICU in #1660.

However, we are not using ICU on iOS so we'd need a platform implementation (using NSString?). And there is a linker error on Android due to the vendored dependency not including the necessary source files.

**Comment by louwers** [comment]
> May be use `<codecvt>` from STL? Yes, it is deprecated and we even have an [issue](https://github.com/maplibre/maplibre-native/issues/1269) to get rid of it, but it is still supported and this way we won't need any dependencies.

This seemed like a reasonable temporary solution to me.
