### ISSUE TITLE
Refactor `expression.test.cpp` to use std::filesystem

### ISSUE THREAD

**Issue by louwers** [maplibre/maplibre-native#1693]
This file is a bit ugly. Instead of using platform-specific APIs to instantiate the test names in `INSTANTIATE_TEST_SUITE_P` we can probably use std::filesystem instead.

https://github.com/maplibre/maplibre-native/blob/main/test/style/expression/expression.test.cpp

**Comment by bilal614** [comment]
@louwers : I can give this Issue a go. Created PR https://github.com/maplibre/maplibre-native/pull/2649
