### ISSUE TITLE
Try to use GitHub macOS GitHub runner

### ISSUE THREAD

**Issue by louwers** [maplibre/maplibre-native#1726]
The free (Intel-based) GitHub macOS runners are notoriously slow. That is why we are using a self-hosted macOS runner with an  Amazon EC2 Mac Instance right now. They are fast but:

1. Require some manual setup and maintenance. Setup is automated as much as possible, but installing Xcode and configuring certificates are still manual. 
2. Only run one job at a time. You can run multiple runners on the same machine, but since the CPU load is shared between jobs then the job runs slower and is a bit more unstable (especially when running tests in the simulator). So the iOS CI tends to be a bottleneck.
3. Self-hosted runners are [not recommended for public repositories](https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/about-self-hosted-runners#self-hosted-runner-security) because arbitrary code from third parties can be run on them. This does not make for a very secure environment. 
4. Right now, the runner went down and I cannot connect to it anymore...

Since we use Bazel the iOS CI is running through much quicker. Maybe it is performant enough to give the GitHub macOS runners a try again...

**Comment by louwers** [comment]
I don't think there is a way to securely include a signing certificate in a PR workflow run...

**Comment by ntadej** [comment]
I think there's a rist of exposing secrets in any PR workflow, regardless where it is hosted. The main question is, what implication does it have? If we have dedicated iOS certificates just for CI I think they are hard to abuse without also the access to the Apple account associated to them (but maybe I'm wrong).

**Comment by wipfli** [comment]
One reason we switched to the AWS mac minis is that they were apple silicon while the github mac were intel. Does github have apple silicon now (m1, m2, etc..)?

**Comment by louwers** [comment]
@ntadej Secrets are not available to workflows running in the context of a fork (usually the case for PRs).

@wipfli Since two days actually (paid).  https://github.blog/2023-10-02-introducing-the-new-apple-silicon-powered-m1-macos-larger-runner-for-github-actions/

**Comment by ntadej** [comment]
So `GITHUB_TOKEN` is the only secret exposed. What we could try to push either to a staging repo or a staging branch in this repo to run the CI with secrets, maybe after a comment from one of the repo members (to avoid security issues).

This will be of course much more cumbersome but workflows that do not require secrets could still run by default.

**Comment by louwers** [comment]
We're now using it for the iOS release. Will be shifting as much workload off the self-hosted runner.
