### ISSUE TITLE
Android FPS Test

### ISSUE THREAD

**Issue by sjg-wdw** [maplibre/maplibre-native#1759]
We need a proper frame time test for Android.  Something that can load a style, warm it up, and render for a defined period and measure the frame rate.

**Comment by louwers** [comment]
The Kotlin has a setOnFpsChangedListener callback that makes this relatively uncomplicated. I'll run it while doing a tour. I want to calculate average FPS and 1% low. Feedback welcome.

**Comment by louwers** [comment]
The render test FPS probes might also be interesting to revive.  https://github.com/maplibre/maplibre-native/blob/f0490ac7852c929d9fcf7927351aa6cf7b73f9e7/render-test/parser.cpp#L1185C53-L1185C63
