### ISSUE TITLE
Annotations not rendered and positioned properly on iOS

### ISSUE THREAD

**Issue by osca** [maplibre/maplibre-native#178]
Annotations/Markers are not rendered and positioned properly on iOS in version 5.12.1. I tested version 5.12.0 where everything seems to work fine.

Screenshot of correct version @ 5.12.0:
![IMG_5307](https://user-images.githubusercontent.com/148895/138849259-e0b86677-b7d5-4293-8d9e-9d947a3eb5a6.PNG)

Video of buggy version @ 5.12.1:
https://user-images.githubusercontent.com/148895/138849436-16a6a7a6-0a6e-41bb-9228-91ef76a75c24.mp4

Amount and position of markers are wrong. Also the rendering is kind of broken, because the markers only appear while zooming.

Steps to reproduce in a fresh project:
1. Setup a new sample iOS project
2. Add exact version of Maplibre iOS 5.12.1
3. Use this sample code:
```
import UIKit
import Mapbox

class ViewController: UIViewController {
    override func viewDidLoad() {
        super.viewDidLoad()
        
        let mapView = MGLMapView(frame: view.bounds)
        mapView.styleURL = URL(string: "[SOME_STYLE_URL]")
        mapView.autoresizingMask = [.flexibleWidth, .flexibleHeight]
        mapView.setCenter(CLLocationCoordinate2D(latitude: 51.572276, longitude: 8.108391), zoomLevel: 9, animated: false)
        view.addSubview(mapView)
        
        let annotation = MGLPointAnnotation()
        annotation.coordinate = CLLocationCoordinate2D(latitude: 51.572276, longitude: 8.108391)
        annotation.title = "Big city"
        annotation.subtitle = "Some nice city description"
        mapView.addAnnotation(annotation)
    }
}
```
4. Replace style URL
5. Zoom out and in to see some markers somewhere sometimes

**Comment by chchrn** [comment]
I met this problem too

**Comment by louwers** [comment]
Please try the latest iOS release.
