### ISSUE TITLE
Metal Stats

### ISSUE THREAD

**Issue by sjg-wdw** [maplibre/maplibre-native#1798]
The GL context tracks the number of allocated textures and the size of requested texture memory. [Here](https://github.com/maplibre/maplibre-native/blob/b792309d6adc0ec1d3aad6f292f1e08df96061e2/include/mbgl/gfx/rendering_stats.hpp#L10-L18) is everything the renderer tracks.

**Comment by TimSylvester** [comment]
Resolved by #1781
