### ISSUE TITLE
Eyeball test of Android OpenGL performance

### ISSUE THREAD

**Issue by sjg-wdw** [maplibre/maplibre-native#1823]
Run the new and old versions to make sure we haven't done something horrible to the Android performance.

**Comment by louwers** [comment]
Just eyeballing is quite difficult to see a difference.

Tried the TextureView animation on Samsung S10 with n=5 runs each

legacyRelease avg. 367 fps (σ=37.3)
drawableRelease avg. 274 fps (σ=11.9)

**Comment by sjg-wdw** [comment]
So we didn't make it horribly slow.  That should clear the way to turning off the old renderer.

**Comment by louwers** [comment]
Or at least making a pre-release for Android as well!

**Comment by louwers** [comment]
Closing, we have a benchmark now.
