### ISSUE TITLE
Drawable Renderer: Observed Label Transformation Issue

### ISSUE THREAD

**Issue by mwilsnd** [maplibre/maplibre-native#1844]
Observed on the drawable renderer, iOS devices. While rotating the map, labels can render with incorrect transformations during zoom transitions.

https://github.com/maplibre/maplibre-native/assets/53413200/3f0701f8-1290-4756-be7e-f026c1870bd0

**Comment by TimSylvester** [comment]
This seems to be fixed with #1849, can you confirm?

**Comment by mwilsnd** [comment]
This one does look to be fixed, Thanks! Closing as complete.
