### ISSUE TITLE
Metal Renderer: Incorrect Feature Visibility

### ISSUE THREAD

**Issue by mwilsnd** [maplibre/maplibre-native#1846]
Seen on the Metal renderer, features that should render at certain zoom levels are failing to do so beyond a single frame.

https://github.com/maplibre/maplibre-native/assets/53413200/56b69e36-866f-4baf-9054-cdf8672a0c9c

**Comment by TimSylvester** [comment]
I'm not seeing quite the same thing on main, but I suspect this may be the same problem as #1845, and it would make sense that it would happen with a different layer, and #1871 seems to resolve it.

<img src="https://github.com/maplibre/maplibre-native/assets/71895881/83676d20-635f-4785-a894-aae008a2b46a" width="300"/>

<img src="https://github.com/maplibre/maplibre-native/assets/71895881/a30290dd-9551-40a7-aa69-1441a72bf5bc" width="300"/>
