### ISSUE TITLE
Reevaluate Metal triangulated fill outlines performance impact

### ISSUE THREAD

**Issue by stefankarschti** [maplibre/maplibre-native#1869]
#1780 introduced the `MLN_TRIANGULATE_FILL_OUTLINES` in `fill_bucket.hpp` switch to turn triangulated fill outlines on and off.

TODO: Reevaluate performance after Metal shader variations have beed implemented and decide what the `MLN_TRIANGULATE_FILL_OUTLINES` flag value should be.

**Comment by sjg-wdw** [comment]
Happy with where it is now.
