### ISSUE TITLE
Remove dependency on globally installed Node to build iOS

### ISSUE THREAD

**Issue by bsudekum** [maplibre/maplibre-native#1910]
Currently, to build iOS, there is a requirement that the caller has node installed globally:

https://github.com/maplibre/maplibre-native/blob/454efb64ac0aa549883d8401858687ef419b8d54/BUILD.bazel#L37

Ideally, we could remove this dependency or at least update the workspace to include it.

**Comment by louwers** [comment]
Yes, we could use https://github.com/bazelbuild/rules_nodejs instead.
