### ISSUE TITLE
[ANDROID] Suggest an Android Emulator Device for Testing

### ISSUE THREAD

**Issue by abebeos** [maplibre/maplibre-native#1915]
**Is your feature request related to a problem? Please describe.**

The Android Studio based project setup is quite easy, until it comes to testing.

It is unclear what Android Device to pick in the Device Manager, in order to have a good foundation to run the tests.

**Describe the solution you'd like**

* Suggest an Android Emulator Device.
  * within https://github.com/maplibre/maplibre-native/blob/main/platform/android/DEVELOPING.md

**Comment by louwers** [comment]
I use a real device.

**Comment by abebeos** [comment]
> I use a real device.

So, text could be like this:

"You can use a real android device for testing. If you prefer not to use a real device, use `Tools->Device Manager` to select an emulated one (or multiple ones). As an example, the device `xyz' can be used"

(I get strange errors on my side, not sure what's wrong, device choice or something else. It would be nice to have a reference-device suggested)

**Comment by louwers** [comment]
What kind of errors?

**Comment by abebeos** [comment]
> What kind of errors?

Please see #1916
