### ISSUE TITLE
[ANDROID] androidTest Instrumentation Tests Fail on Local Machine

### ISSUE THREAD

**Issue by abebeos** [maplibre/maplibre-native#1969]
The instrumentation tests (`AndroidSDKTestApp...androidTest`) do not work correctly locally (many fail and the test-run aborts at some point due to crashes).

Both, on Win10 and Ubuntu22

This seems like a known issue (see https://github.com/maplibre/maplibre-native/issues/1920#issuecomment-1842841044)

### Reproduce

* select a device and run the androidTest
  * emulated/real device
 
On my side, on android10/api29 real device, and on several emulated devices, the behavior is nearly the same

152 fail, 37 passes, 5 skipped (from 637 total tests)

DrawableRelease x86_64 (or x86), started via IDE context menu on `androidTest`

### Some example failures:

```
12-18 17:20:47.409  8113  8814 I TestRunner: finished: testLatLngBoundsTiltedRotated(org.maplibre.android.camera.CameraUpdateFactoryTest)

java.lang.NoSuchMethodError: No static method newLatLngBounds(Lorg/maplibre/android/geometry/LatLngBounds;I)Lq3/b; in class Lorg/maplibre/android/camera/a; or its super classes (declaration of 'org.maplibre.android.camera.a' appears in /data/app/org.maplibre.testapp-vV4WJT_J-Gh47AX9Eb8G1A==/base.apk)
at org.maplibre.android.camera.CameraUpdateFactoryTest.testLatLngBoundsTiltedRotated(CameraUpdateFactoryTest.kt:109)

#

12-18 17:22:13.188  8113  8814 E TestRunner: failed: scrollViewPager(org.maplibre.android.integration.ViewPagerScrollTest)
12-18 17:22:13.188  8113  8814 E TestRunner: ----- begin exception -----
12-18 17:22:13.188  8113  8814 E TestRunner: androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[TEXT=Page 1]
12-18 17:22:13.188  8113  8814 E TestRunner: 	at androidx.test.uiautomator.UiObject.click(UiObject.java:416)

#

12-18 17:22:17.929  8113  8814 E TestRunner: failed: lifecycle_keepsDisabledWhenStoppedAndStarted(org.maplibre.android.location.LocationComponentTest)
12-18 17:22:17.929  8113  8814 E TestRunner: ----- begin exception -----
12-18 17:22:17.929  8113  8814 E TestRunner: java.lang.NoSuchMethodError: No virtual method isLocationComponentEnabled()Z in class Lorg/maplibre/android/location/k; or its super classes (declaration of 'org.maplibre.android.location.k' appears in /data/app/org.maplibre.testapp-vV4WJT_J-Gh47AX9Eb8G1A==/base.apk)
12-18 17:22:17.929  8113  8814 E TestRunner: 	at org.maplibre.android.location.LocationComponentTest$lifecycle_keepsDisabledWhenStoppedAndStarted$componentAction$1.onLocationComponentAction(LocationComponentTest.kt:768)




```

### Expected

* Tests work on a local machine
* Tests which are not able to run on a local machine are excluded (e.g. by cli argument)

### Suggested Solution

- [ ] provide a mechanism to disable tests selectively (e.g. cli argument)
- [ ] exclude all tests that fail locally
- [ ] fix/enable the tests as time allows

**Comment by louwers** [comment]
Thanks for creating an issue for this.

Debug builds of the drawable renderer are expected to fail due to https://github.com/maplibre/maplibre-native/issues/1833.

The three instrumentation tests failures (of the legacy renderer) are likely due to https://github.com/maplibre/maplibre-native/pull/1660. I will take a look.

**Comment by louwers** [comment]
I digged in the failing instrumentation tests (`BootstrapTest.kt`)

```
std::u16string convertUTF8ToUTF16(const std::string& str) {
    std::wstring_convert<std::codecvt_utf8_utf16<char16_t>, char16_t> conv;

    return conv.from_bytes(str);
}
```

The value of `str` is `https://maptiler.org` when entering the function and after executing the first line of the function, it is

```
"H\U00000014\U0000000f\xbdr\0\0\0\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\U00000010\0\0\0\0\0"
```

Which looks like garbage to me.

Probably an issue with a dangling reference here

```
jni::Local<jni::String> FileSource::getAPIBaseUrl(jni::JNIEnv& env) {
    if (auto* url = onlineSource->getProperty(mbgl::API_BASE_URL_KEY).getString()) {
        return jni::Make<jni::String>(env, *url);
    }
```

**Comment by abebeos** [comment]
@louwers , could you please check on your side how many tests pass/fail with:

- a real device
- an emulated device

I've updated the original issue with more data.

**Comment by abebeos** [comment]
@louwers , it is standard-procedure to await the confirmation of the issue author.

I cannot reopen myself => the tests still fail.

I run the tests within Android Studio, using the context-menu within `MapboxGLAndoridSDKTestApp/kotlin+java/org.maplibre.android(androidTest)`

**Comment by louwers** [comment]
A debug build should work. Let me know if it doesn't, I can re-open.

```
./gradlew connectedLegacyDebugAndroidTest
```

From CLI.

To run it from Android Studio you may need to set `testBuildType` to `debug` in `platform/android/MapboxGLAndroidSDKTestApp/build.gradle`.

**Comment by abebeos** [comment]
`/gradlew connectedLegacyDebugAndroidTest` seems to build, but no test output is shown.

But this issue is about that an Android Studio Project should allow to run the tests right from within the IDE.

> To run it from Android Studio you may need to set `testBuildType` to `debug` in `platform/android/MapboxGLAndroidSDKTestApp/build.gradle`.

this does not work.

(note that I am off-code here: I do not go into debugging the problems)

(this should be really fixed, build-test-debug should run out-of-the-box within Android-Studio, thus devs can focus on the tasks at hand.)

**Comment by louwers** [comment]
I changed the default back to `debug` with #1976 so it should work again with Android Studio out of the box.

**Comment by abebeos** [comment]
Thanks, works now, a follow-up: #1977
