### ISSUE TITLE
[iOS] Metal-Prerelease: Map Snapshotter fails on simulator

### ISSUE THREAD

**Issue by hactar** [maplibre/maplibre-native#1979]
**Describe the bug**
When using the metal prerelease, for example `ios-v6.0.0-pre8820165ccafb4f3db109b0b4ae91739d577d7ece` you cannot use `MLNMapSnapshotter` on the iOS simulator, for example an iPhone Pro 15 (17.2) simulator. The code builds and runs fine, but during snapshotting, the app crashes with the following message:

```
-[MTLTextureDescriptorInternal validateWithDevice:]:1357: failed assertion `Texture Descriptor Validation
MTLTextureDescriptor: Depth, Stencil, DepthStencil textures cannot be allocated with MTLStorageModeShared on this device.
```

On real devices, for example my iPhone 12 Pro Max running iOS 17.1 the snapshotter works fine.

**To Reproduce**
- Build and run the attached project on the simulator. 
- Hit the "Generate Map Snapshot"

**Expected behavior**
A UIImage of the map should be generated. Instead the app crashes as described above.

**Screenshots**
On device, this works, the final result being this:

<img src="https://github.com/maplibre/maplibre-native/assets/645674/60fb0495-045f-48d7-a300-3718a3387f05" width=40% height=40%>

**Platform information (please complete the following information):**
 - iOS 17.2 Simulator
 - Version ios-v6.0.0-pre8820165ccafb4f3db109b0b4ae91739d577d7ece

**Example App**
[MapLibreSnapshotterExample.zip](https://github.com/maplibre/maplibre-native/files/13728911/MapLibreSnapshotterExample.zip)

**Comment by louwers** [comment]
Thanks for the report! This is expected. The Snapshotter still needs to be implemented for Metal. https://github.com/maplibre/maplibre-native/issues/1862

**Comment by louwers** [comment]
I updated the pre-release overview thread. #1609

Please let us know if you come across anything else!
