### ISSUE TITLE
Polyline won't update

### ISSUE THREAD

**Issue by tvaknin** [maplibre/maplibre-native#1988]
**Describe the bug**
Trying to update an existing polyline won't update
sdk:10.2.0, os: Andorid

**To Reproduce**
1. addPolyline(polylineOptions)
2. update the polyline of polylineOptions with some LatLng
3. call updatePolyline with the updated polyline

```
polylineOptions = PolylineOptions()
                .width(5f) // Change to your desired width
                .alpha(0.8f) // Change to your desired alpha value
                .add(LatLng(0.0, 0.0))
                .add(LatLng(32.0912145,34.8063))
            polyline = m_mapboxMap?.addPolyline(polylineOptions)
            polyline.addPoint(LatLng(32.091,34.80))
            m_mapboxMap?.updatePolyline(polyline!!)
```

**Expected behavior**
The Polyline disappears from the map, expected behavior -> the polyline being updated according to the new LatLng.

**Comment by fynngodau** [comment]
@louwers I can't assert from the top of my head whether I have used the `Polyline.addPoint` method in the past, unfortunately.

**Comment by tvaknin** [comment]
@louwers @fynngodau I'm curious if I'm approaching this task correctly. Is it essential to continuously update a polyline, or are there alternative methods available? For instance, I need it to track my current location.

**Comment by louwers** [comment]
@tvaknin They were deprecated before the fork. However we decided to move annotations support back into the main toolkit, instead of delegating it to a separate plugin. More details can be found here: https://github.com/maplibre/maplibre-native/blob/main/design-proposals/2023-06-17-android-annotations.md

Would deleting and creating a new polyline be a workaround?

**Comment by tvaknin** [comment]
@louwers it didn't work, it seems broken.

**Comment by louwers** [comment]
@tvaknin I'll have a look and try reproduce it.

**Comment by tvaknin** [comment]
That was my mistake, I left some mapboxMap.clear() in the code. sorry for that.
the code provided in the ticket is correct and can be used to update the existing polyline. 

Thanks for your help.

**Comment by louwers** [comment]
@tvaknin Glad you were able to solve it!
