### ISSUE TITLE
Warnings: "Umbrella header for module 'MapLibre' does not include header ..."

### ISSUE THREAD

**Issue by louwers** [maplibre/maplibre-native#2009]
The latest pre-release gives these warnings in Xcode.

Bazel is generating an umbrella header, maybe we need to manually create one. https://github.com/bazelbuild/rules_apple/blob/master/doc/rules-apple.md#apple_xcframework 

<details>
<sumary>
Warnings...
</summary>

/Users/bart/Library/Developer/Xcode/DerivedData/TryoutApp-ayqoxpunjladrnfianyomqldtalb/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/MapLibre/MapLibre.framework/Headers/Mapbox.h:84:1: Umbrella header for module 'MapLibre' does not include header 'NSDictionary+MLNAdditions.h'

/Users/bart/Library/Developer/Xcode/DerivedData/TryoutApp-ayqoxpunjladrnfianyomqldtalb/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/MapLibre/MapLibre.framework/Headers/Mapbox.h:84:1: Umbrella header for module 'MapLibre' does not include header 'MLNStyleLayerManager.h'

/Users/bart/Library/Developer/Xcode/DerivedData/TryoutApp-ayqoxpunjladrnfianyomqldtalb/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/MapLibre/MapLibre.framework/Headers/Mapbox.h:84:1: Umbrella header for module 'MapLibre' does not include header 'NSBundle+MLNAdditions.h'

/Users/bart/Library/Developer/Xcode/DerivedData/TryoutApp-ayqoxpunjladrnfianyomqldtalb/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/MapLibre/MapLibre.framework/Headers/Mapbox.h:84:1: Umbrella header for module 'MapLibre' does not include header 'NSArray+MLNAdditions.h'

/Users/bart/Library/Developer/Xcode/DerivedData/TryoutApp-ayqoxpunjladrnfianyomqldtalb/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/MapLibre/MapLibre.framework/Headers/Mapbox.h:84:1: Umbrella header for module 'MapLibre' does not include header 'MLNMapAccessibilityElement.h'

/Users/bart/Library/Developer/Xcode/DerivedData/TryoutApp-ayqoxpunjladrnfianyomqldtalb/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/MapLibre/MapLibre.framework/Headers/Mapbox.h:84:1: Umbrella header for module 'MapLibre' does not include header 'UIDevice+MLNAdditions.h'

/Users/bart/Library/Developer/Xcode/DerivedData/TryoutApp-ayqoxpunjladrnfianyomqldtalb/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/MapLibre/MapLibre.framework/Headers/Mapbox.h:84:1: Umbrella header for module 'MapLibre' does not include header 'MLNConversion.h'

/Users/bart/Library/Developer/Xcode/DerivedData/TryoutApp-ayqoxpunjladrnfianyomqldtalb/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/MapLibre/MapLibre.framework/Headers/Mapbox.h:84:1: Umbrella header for module 'MapLibre' does not include header 'MLNRendererConfiguration.h'

/Users/bart/Library/Developer/Xcode/DerivedData/TryoutApp-ayqoxpunjladrnfianyomqldtalb/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/MapLibre/MapLibre.framework/Headers/Mapbox.h:84:1: Umbrella header for module 'MapLibre' does not include header 'MLNValueEvaluator.h'

/Users/bart/Library/Developer/Xcode/DerivedData/TryoutApp-ayqoxpunjladrnfianyomqldtalb/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/MapLibre/MapLibre.framework/Headers/Mapbox.h:84:1: Umbrella header for module 'MapLibre' does not include header 'MLNUserLocationHeadingIndicator.h'

/Users/bart/Library/Developer/Xcode/DerivedData/TryoutApp-ayqoxpunjladrnfianyomqldtalb/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/MapLibre/MapLibre.framework/Headers/Mapbox.h:84:1: Umbrella header for module 'MapLibre' does not include header 'MLNRendererFrontend.h'

/Users/bart/Library/Developer/Xcode/DerivedData/TryoutApp-ayqoxpunjladrnfianyomqldtalb/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/MapLibre/MapLibre.framework/Headers/Mapbox.h:84:1: Umbrella header for module 'MapLibre' does not include header 'NSException+MLNAdditions.h'

/Users/bart/Library/Developer/Xcode/DerivedData/TryoutApp-ayqoxpunjladrnfianyomqldtalb/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/MapLibre/MapLibre.framework/Headers/Mapbox.h:84:1: Umbrella header for module 'MapLibre' does not include header 'MLNUserLocationHeadingArrowLayer.h'

/Users/bart/Library/Developer/Xcode/DerivedData/TryoutApp-ayqoxpunjladrnfianyomqldtalb/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/MapLibre/MapLibre.framework/Headers/Mapbox.h:84:1: Umbrella header for module 'MapLibre' does not include header 'NSURL+MLNAdditions.h'

/Users/bart/Library/Developer/Xcode/DerivedData/TryoutApp-ayqoxpunjladrnfianyomqldtalb/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/MapLibre/MapLibre.framework/Headers/Mapbox.h:84:1: Umbrella header for module 'MapLibre' does not include header 'UIImage+MLNAdditions.h'

/Users/bart/Library/Developer/Xcode/DerivedData/TryoutApp-ayqoxpunjladrnfianyomqldtalb/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/MapLibre/MapLibre.framework/Headers/Mapbox.h:84:1: Umbrella header for module 'MapLibre' does not include header 'MLNMapView+Metal.h'

/Users/bart/Library/Developer/Xcode/DerivedData/TryoutApp-ayqoxpunjladrnfianyomqldtalb/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/MapLibre/MapLibre.framework/Headers/Mapbox.h:84:1: Umbrella header for module 'MapLibre' does not include header 'UIColor+MLNAdditions.h'

/Users/bart/Library/Developer/Xcode/DerivedData/TryoutApp-ayqoxpunjladrnfianyomqldtalb/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/MapLibre/MapLibre.framework/Headers/Mapbox.h:84:1: Umbrella header for module 'MapLibre' does not include header 'NSOrthography+MLNAdditions.h'

/Users/bart/Library/Developer/Xcode/DerivedData/TryoutApp-ayqoxpunjladrnfianyomqldtalb/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/MapLibre/MapLibre.framework/Headers/Mapbox.h:84:1: Umbrella header for module 'MapLibre' does not include header 'NSComparisonPredicate+MLNAdditions.h'

/Users/bart/Library/Developer/Xcode/DerivedData/TryoutApp-ayqoxpunjladrnfianyomqldtalb/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/MapLibre/MapLibre.framework/Headers/Mapbox.h:84:1: Umbrella header for module 'MapLibre' does not include header 'MLNCompactCalloutView.h'

/Users/bart/Library/Developer/Xcode/DerivedData/TryoutApp-ayqoxpunjladrnfianyomqldtalb/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/MapLibre/MapLibre.framework/Headers/Mapbox.h:84:1: Umbrella header for module 'MapLibre' does not include header 'MLNMapView+OpenGL.h'

/Users/bart/Library/Developer/Xcode/DerivedData/TryoutApp-ayqoxpunjladrnfianyomqldtalb/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/MapLibre/MapLibre.framework/Headers/Mapbox.h:84:1: Umbrella header for module 'MapLibre' does not include header 'MLNMapView+Impl.h'

/Users/bart/Library/Developer/Xcode/DerivedData/TryoutApp-ayqoxpunjladrnfianyomqldtalb/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/MapLibre/MapLibre.framework/Headers/Mapbox.h:84:1: Umbrella header for module 'MapLibre' does not include header 'MLNAnnotationContainerView.h'

/Users/bart/Library/Developer/Xcode/DerivedData/TryoutApp-ayqoxpunjladrnfianyomqldtalb/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/MapLibre/MapLibre.framework/Headers/Mapbox.h:84:1: Umbrella header for module 'MapLibre' does not include header 'NSCompoundPredicate+MLNAdditions.h'

/Users/bart/Library/Developer/Xcode/DerivedData/TryoutApp-ayqoxpunjladrnfianyomqldtalb/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/MapLibre/MapLibre.framework/Headers/Mapbox.h:84:1: Umbrella header for module 'MapLibre' does not include header 'NSValue+MLNStyleAttributeAdditions.h'

/Users/bart/Library/Developer/Xcode/DerivedData/TryoutApp-ayqoxpunjladrnfianyomqldtalb/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/MapLibre/MapLibre.framework/Headers/Mapbox.h:84:1: Umbrella header for module 'MapLibre' does not include header 'NSString+MLNAdditions.h'

/Users/bart/Library/Developer/Xcode/DerivedData/TryoutApp-ayqoxpunjladrnfianyomqldtalb/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/MapLibre/MapLibre.framework/Headers/Mapbox.h:84:1: Umbrella header for module 'MapLibre' does not include header 'UIViewController+MLNAdditions.h'

/Users/bart/Library/Developer/Xcode/DerivedData/TryoutApp-ayqoxpunjladrnfianyomqldtalb/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/MapLibre/MapLibre.framework/Headers/Mapbox.h:84:1: Umbrella header for module 'MapLibre' does not include header 'UIView+MLNAdditions.h'

/Users/bart/Library/Developer/Xcode/DerivedData/TryoutApp-ayqoxpunjladrnfianyomqldtalb/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/MapLibre/MapLibre.framework/Headers/Mapbox.h:84:1: Umbrella header for module 'MapLibre' does not include header 'MLNReachability.h'

/Users/bart/Library/Developer/Xcode/DerivedData/TryoutApp-ayqoxpunjladrnfianyomqldtalb/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/MapLibre/MapLibre.framework/Headers/Mapbox.h:84:1: Umbrella header for module 'MapLibre' does not include header 'NSCoder+MLNAdditions.h'

/Users/bart/Library/Developer/Xcode/DerivedData/TryoutApp-ayqoxpunjladrnfianyomqldtalb/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/MapLibre/MapLibre.framework/Headers/Mapbox.h:84:1: Umbrella header for module 'MapLibre' does not include header 'MLNScaleBar.h'

/Users/bart/Library/Developer/Xcode/DerivedData/TryoutApp-ayqoxpunjladrnfianyomqldtalb/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/MapLibre/MapLibre.framework/Headers/Mapbox.h:84:1: Umbrella header for module 'MapLibre' does not include header 'MLNFaux3DUserLocationAnnotationView.h'

/Users/bart/Library/Developer/Xcode/DerivedData/TryoutApp-ayqoxpunjladrnfianyomqldtalb/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/MapLibre/MapLibre.framework/Headers/Mapbox.h:84:1: Umbrella header for module 'MapLibre' does not include header 'MLNUserLocationHeadingBeamLayer.h'

/Users/bart/Library/Developer/Xcode/DerivedData/TryoutApp-ayqoxpunjladrnfianyomqldtalb/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/MapLibre/MapLibre.framework/Headers/Mapbox.h:84:1: Umbrella header for module 'MapLibre' does not include header 'NSDate+MLNAdditions.h'
<.details>

**Comment by louwers** [comment]
Forgot we already do, just need to update it I think.

**Comment by keith** [comment]
I think long term it might just be nice to let bazel generate this

**Comment by keith** [comment]
I was able to get generation working with [`471a8dd` (#1948)](https://github.com/maplibre/maplibre-native/pull/1948/commits/471a8ddbbee3c933f4ef3a041db4acce45e54bf4) + your change, right now it still uses the Mapbox.h since a lot of things depend on that, but the umbrella header just ends up including that
