### ISSUE TITLE
Wayland build: Could NOT find OpenGL (missing: GLX)

### ISSUE THREAD

**Issue by JonasVautherin** [maplibre/maplibre-native#2019]
*Note: opening an issue here under the advice of @louwers [on Slack](https://osmus.slack.com/archives/C02B2CBSNBU/p1705321862741179?thread_ts=1705082964.200539&cid=C02B2CBSNBU), hoping to get insights from @jwinarske.*

Trying to build maplibre-native on Wayland, I get the following error in the CMake configuration step:

```
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find OpenGL (missing: GLX)
```

I am running on Alpine 3.19 with Wayland.

I saw [this issue](https://github.com/maplibre/maplibre-native/pull/1018) and tried different things to remove the need for GLX (my understanding being that I don't need GLX on Wayland), like this:

```
cmake -DMBGL_WITH_EGL=ON -DMLN_WITH_WAYLAND=ON -DMLN_WITH_ELG=ON -DMBGL_WITH_WAYLAND=ON -Bbuild -S.
```

But it does not change the GLX error I get. Am I missing something to build with Wayland?

**Comment by acalcutt** [comment]
If you are doing this on a headless system, maybe throwing 'xvfb-run --auto-servernum' before the command will allow it to work? I've never had to use that on cmake,

Also, Is this node binaries that you are building? I'd check out the node workflow steps at
https://github.com/maplibre/maplibre-native/blob/main/.github/workflows/node-ci.yml#L206-L216
and
https://github.com/maplibre/maplibre-native/blob/main/.github/workflows/node-ci.yml#L236-L243

Node needs the `DMLN_WITH_NODE=ON` now, which I you would then add the `DMLN_WITH_ELG=ON` to have it build in egl mode. I'm not familiar with that DMLN_WITH_WAYLAND flag.

**Comment by acalcutt** [comment]
I remember seeing this old converation that makes me think xvfb is needed with EGL
https://github.com/maplibre/maplibre-native/pull/217#issuecomment-1132215477

Btw, I just noticed you have a type. the option is [DMLN_WITH_EGL](https://github.com/maplibre/maplibre-native/blob/main/CMakeLists.txt#L11) , not DMLN_WITH_ELG

**Comment by JonasVautherin** [comment]
Thanks for the quick answer!

> If you are doing this on a headless system

No, that's my main Desktop machine :see_no_evil:.

> Btw, I just noticed you have a typo. the option is [DMLN_WITH_EGL](https://github.com/maplibre/maplibre-native/blob/main/CMakeLists.txt#L11) , not DMLN_WITH_ELG

:man_facepalming: you are right, and this one actually makes a difference, though it still gives an error for OpenGL (not sure if it fails earlier or later, though):

```
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find OpenGL (missing: OPENGL_opengl_LIBRARY)
```

**Comment by acalcutt** [comment]
I'd still give xvfb a try even if you aren't on a headless system. with non-egl node binaries, i have seen cases where the users video card driver does not support opengl, and gets opengl related errors. xvfb should allow it to emulate opengl if that was the case.

**Comment by JonasVautherin** [comment]
Right, let me try. Also I am not building for node. I want to build C++ for Linux (so I'm running CMake from the root CMakeLists.txt, I assumed that was correct :thinking:) and then for Android. I would like to contribute to Android, but I think I need to compile the C++ for that :+1:.

**Comment by acalcutt** [comment]
If you aren't building node I would assume you would just omit the `DMLN_WITH_NODE=ON` , should pretty much be the same build commands. I'm not familiar with wayland, but usually follow these instructions for linux ( https://github.com/maplibre/maplibre-native/tree/main/platform/linux ). Node is pretty much the same linux c++ build but adds a few binaries.

I was thinking another thing you could try is if the [opengl-2](https://github.com/maplibre/maplibre-native/tree/opengl-2) branch behave differently. The opengl level has been raised in main, so maybe that branch would build differently?

**Comment by JonasVautherin** [comment]
In the CMake module, it adds the `OPENGL_opengl_LIBRARY` component under those conditions:

```
  # now we append the libraries as appropriate.  The complicated logic
  # basically comes down to "use libOpenGL when we can, and add in specific
  # context mechanisms when requested, or we need them to preserve the previous
  # default where glx is always available."
  if((NOT OPENGL_USE_EGL AND
      NOT OPENGL_opengl_LIBRARY AND
          OPENGL_glx_LIBRARY AND
      NOT OPENGL_gl_LIBRARY) OR
     (NOT OPENGL_USE_EGL AND
      NOT OPENGL_USE_GLES3 AND
      NOT OPENGL_USE_GLES2 AND
      NOT OPENGL_glx_LIBRARY AND
      NOT OPENGL_gl_LIBRARY) OR
     (NOT OPENGL_USE_EGL AND
          OPENGL_opengl_LIBRARY AND
          OPENGL_glx_LIBRARY) OR
     (NOT OPENGL_USE_GLES3 AND
      NOT OPENGL_USE_GLES2 AND
          OPENGL_USE_EGL))
    list(APPEND _OpenGL_REQUIRED_VARS OPENGL_opengl_LIBRARY)
  endif()
```

Because I set `-DMLN_WITH_EGL=ON`, it gets [here](https://github.com/maplibre/maplibre-native/blob/main/platform/linux/linux.cmake#L64):

```
    find_package(OpenGL REQUIRED EGL)
```

And this fails to find `OPENGL_opengl_LIBRARY`, which I don't have because (I believe) it is an X11 thing. So I tried with `-DOPENGL_USE_GLES3` (which required me to `apk add glfw-dev`), and I go further:

```
-- Found OpenGL: /usr/lib/libEGL.so  found components: EGL 
-- Looking for strerror_r
-- Looking for strerror_r - not found
-- Found OpenGL: /usr/lib/libEGL.so   
-- Checking for one of the modules 'glfw3'
-- Configuring done (1.1s)
CMake Error at vendor/benchmark.cmake:5 (add_library):
  Cannot find source file:

    /tmp/maplibre-native/vendor/benchmark/src/sleep.cc

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm
  .ccm .cxxm .c++m .h .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90
  .f95 .f03 .hip .ispc
Call Stack (most recent call first):
  benchmark/CMakeLists.txt:27 (include)


CMake Error at vendor/benchmark.cmake:5 (add_library):
  No SOURCES given to target: mbgl-vendor-benchmark
Call Stack (most recent call first):
  benchmark/CMakeLists.txt:27 (include)
```

Feels like progress :see_no_evil:.

**Comment by jwinarske** [comment]
I haven't read through entirely, but something to keep in mind is the wayland support is intended to be mutually exclusive with x11/xcb.  Opposed to being additive.  So you would need to disable all the x11/xcb support.  I can take a look tomorrow

**Comment by JonasVautherin** [comment]
I managed to pass the configure step with:

```
cmake -DMLN_WITH_EGL=ON -DMLN_WITH_NODE=OFF -DMLN_WITH_WAYLAND=ON -DOPENGL_USE_GLES3=ON -Bbuild -S.
```

I worked around the last error (about the path to sleep.cc being wrong) by commenting out [benchmarks](https://github.com/maplibre/maplibre-native/blob/main/CMakeLists.txt#L1433). It is now building :crossed_fingers:.

**Comment by JonasVautherin** [comment]
I got it to build! I'll close this issue and will follow-up with a small PR meant to start a discussion about how the CMake configuration could be improved for Wayland.

Thanks all for the help!

**Comment by acalcutt** [comment]
> I worked around the last error (about the path to sleep.cc being wrong) by commenting out [benchmarks](https://github.com/maplibre/maplibre-native/blob/main/CMakeLists.txt#L1433) (EDIT: my bad, it was a submodule issue).

I wonder if you add `-DCMAKE_BUILD_TYPE=Release` to your options if it would skip building those lines you had to comment out. I know it builds more in debug mode.
