### ISSUE TITLE
MapLibre Native iOS 6.0.0 (with Metal) Release

### ISSUE THREAD

**Issue by louwers** [maplibre/maplibre-native#2021]
We have had a long period of pre-releases, testing, benchmarking and patches for the Metal backend for MapLibre Native. The stability and conformance is now at a level where I personally am confident it is time to make a release.

Nothing is perfect, there might still be some bugs, but making a release is the best way to bring them to the surface (and fixed with patch releases). This is a major release which includes a large refactor of the rendering internals. Despite having extensive tests in place, as a FOSS project we have limited QA testing capabilities. Also due to the powerful style language of MapLibre, regressions cannot be ruled out. Users are therefore encouraged to also do their own (internal) testing of this major release before doing a full rollout to mission-critical applications. 

That said, [feedback](https://github.com/maplibre/maplibre-native/issues/1609) so far has been very positive and no crashes have been reported so far. If despite that there are any blockers for the MapLibre Native iOS 6.0.0 'Metal' release (not listed below), please comment here and I will add them to the list.

The 16th of January 2024 has been set as a target release date.

Release Checklist

- [x] Merge https://github.com/maplibre/maplibre-native/pull/2013
- [x] Update changelog
- [x] Update version in `.plist` ([thanks](https://github.com/maplibre/maplibre-gl-native-distribution/pull/24#issuecomment-1881580752) @roblabs)
- [x] Run release workflow to make release (debug any issues, this is the first time we are using it)
- [x] Try out released XCFramework from GitHub, Swift Package Manager & CocoaPods, ask community to do the same

After release

- [x] https://github.com/maplibre/maplibre.github.io/issues/293

Delayed for later release

- https://github.com/maplibre/maplibre-native/issues/1862

**Comment by louwers** [comment]
- [x] GItHub release. The release notes did not get extracted, so I added them manually for now. Have to check that awk script later.
- [x] CocoaPods release. Looks good. https://github.com/CocoaPods/Specs/blob/master/Specs/b/0/0/MapLibre/6.0.0/MapLibre.podspec.json
- [ ] Swift Package Index release. Need to make some changes.
  - [ ] When this is merged I'll try to run it manually to make the release. https://github.com/maplibre/maplibre-gl-native-distribution/pull/25

**Comment by halset** [comment]
Very glad to see all the good work you & co have done here. Tested now in my app. 
* Everything works. Good.
* All layers move in the same speed when pan/zoom. Good. (was a issue earlier, bit not anymore)
* Performance can improve. Would be nice to have same speed as v5.
* `#import <Maplibre/Mapbox.h>` should probably change to `#import <Maplibre/Maplibre.h>`?

**Comment by louwers** [comment]
@halset Thanks for trying it out and happy it works. 

Performance is an area of continious concern.

There is an issue to rename the umbrella header. https://github.com/maplibre/maplibre-native/issues/2020 We will probably do that in a minor release (while keeping the old umbrella header around).

**Comment by louwers** [comment]
@r3econ Yes.
