### ISSUE TITLE
Missing node-v120-win32-x64-Release.tar.gz file

### ISSUE THREAD

**Issue by donnyv** [maplibre/maplibre-native#2048]
**Describe the bug**
When installing npm install -g tileserver-gl
Install throws a 404 on the url https://github.com/maplibre/maplibre-native/releases/download/node-v5.3.0/node-v120-win32-x64-Release.tar.gz

**Screenshots**
![image](https://github.com/maplibre/maplibre-native/assets/2224189/c8eb161b-263d-4fa6-a111-fa5941a95a43)

**Platform information (please complete the following information):**
 - OS: Windows 10
 - Platform Node.js
 - Version 22H2

**Comment by acalcutt** [comment]
We are only publishing binaries for node LTS releases. The latest release has binaries for node 16, 18, and 20
https://github.com/maplibre/maplibre-native/tree/main/platform/node#installing

**Comment by acalcutt** [comment]
In tileserver-gl we support node 18 and 20 
https://maptiler-tileserver.readthedocs.io/en/latest/installation.html#npm
