### ISSUE TITLE
Prune automated iOS release tags

### ISSUE THREAD

**Issue by wipfli** [maplibre/maplibre-native#2061]
We have a lot of automated tags for iOS pre-releases based on each commit to main.

Do we prune  or delete them in some way automatically?

**Comment by louwers** [comment]
@wipfli I thought about it, but it's a bad practice to retract releases.

Although I doubt anyone is relying on these pre-releases...

**Comment by louwers** [comment]
They are gone.

For future reference:

```
gh release list | awk '{ print $1 }' | grep ios-v6.0.0-pre | xargs -n 1 -I {} gh release delete {}
```

Use with care!
