### ISSUE TITLE
New gray scale logo for map overlay

### ISSUE THREAD

**Issue by wipfli** [maplibre/maplibre-native#2064]
Once https://github.com/maplibre/maplibre-gl-js/pull/3631 is merged, I think MapLibre Native should also include the new grayscale logo. Thanks!

**Comment by ntadej** [comment]
We should clarify if it's required or not as people are periodically asking.

Note that AFAIK Mapbox required it more to attribute the maps themselves and not the SDK.

**Comment by wipfli** [comment]
The logo is not required for using MapLibre, but it is nice to spread the word...

**Comment by ntadej** [comment]
This I knew but I think it's not documented anywhere.
