### ISSUE TITLE
[Android] Symbols are not displayed over an MBTile package

### ISSUE THREAD

**Issue by ysmaherzi** [maplibre/maplibre-native#2079]
When I display an offline map using an mbtile package, I can display lines over it but I can't display symbols. 
Tried with AnnotationManager and GeojsonSource, in both cases the lines lines showw but not the symbols. The same code works when I use an online map.
It works though if I remove the text from the symbol.

MapStyle : 
> {
      "version": 8,
      "name": "test",
      "sources": {
        "mbtilesSource": {
          "type": "raster",
          "tileSize": 256,
          "url": "mbtiles:///___FILE_URI___"
        }
      },
      "layers": [
        {
          "id": "mbtilesOverlay", 
          "type": "raster", 
          "source": "mbtilesSource"}
      ]
    }

How I add the graphics :
> val symbols = SymbolManager(mapView, map, style)
        style.addImage(markerName, BitmapUtils.getDrawableFromRes(this, R.drawable.ic_eye)!!)
        symbols.create(SymbolOptions()
            .withLatLng(LatLng(48.8790745, 2.367481))
            .withIconImage(markerName)
            .withTextField("M")
            .withTextColor("#FFFFFF"))
        val lines = LineManager(mapView, map, style)
        lines.create(LineOptions()
            .withLatLngs(listOf(
                LatLng(48.87918157548796, 2.3671592860542603),
                LatLng(48.87919594460422, 2.3689363559815035),
                LatLng(48.878405637088264, 2.3683245778103412),
                LatLng(48.878602017697574, 2.3671228706865577)))
            .withLineColor("#FFFFFF")
            .withLineWidth(2f)
        )

 - OS: Android
 - Version 10.2.0

**Comment by louwers** [comment]
Glad you managed to fix the problem @ysmaherzi .
