### ISSUE TITLE
Annotation view desynchronization on Metal while multiple frames in flight

### ISSUE THREAD

**Issue by stefankarschti** [maplibre/maplibre-native#2082]
Annotation Views desynchronize from the map on Metal.

ref #2053

**Comment by louwers** [comment]
@stefankarschti Can this one be closed now that https://github.com/maplibre/maplibre-native/commit/9614b566d8e497cf8afffc3d26b004a1518baefe is merged?

**Comment by stefankarschti** [comment]
fixed by #2334
