### ISSUE TITLE
maplibre-gl@4.0.0 doesn't display contents if open as a local file

### ISSUE THREAD

**Issue by kkdd** [maplibre/maplibre-native#2097]
**Describe the bug**

**To Reproduce**
1. Go to 'https://maplibre.org/maplibre-gl-js/docs/examples/simple-map/'
2. Save the source as a local file.
3. Open it by a web browser.
4. No contents are displayed (see a screenshot below).

**Expected behavior**
Displaying as in https://maplibre.org/maplibre-gl-js/docs/examples/simple-map/.

**Screenshots**
![スクリーンショット 2024-02-09 14 40 09](https://github.com/maplibre/maplibre-native/assets/5372642/15c15d8e-ea2b-41f6-8566-126e5e244b7d)

**Platform information (please complete the following information):**
 - OS: macOS 14.3
 - Google Chrome 121.0.6167.160（Official Build） （x86_64）

**Additional context**
It works if using ```maplibre-gl@3.6.2```:

```
    <link rel='stylesheet' href='https://unpkg.com/maplibre-gl@3.6.2/dist/maplibre-gl.css' />
    <script src='https://unpkg.com/maplibre-gl@3.6.2/dist/maplibre-gl.js'></script>
<!--    <link rel='stylesheet' href='https://unpkg.com/maplibre-gl@4.0.0/dist/maplibre-gl.css' />
    <script src='https://unpkg.com/maplibre-gl@4.0.0/dist/maplibre-gl.js'></script>-->
```

**Comment by louwers** [comment]
Wrong project, this is MapLibre Native.

Please create an issue over at https://maplibre.org/maplibre-gl-js
