### ISSUE TITLE
Adding a single `MLNAnnotationView` to an `MLNMapView` results in laggy map rendering

### ISSUE THREAD

**Issue by cgalvan** [maplibre/maplibre-native#2117]
**Describe the bug**
Adding a single `MLNAnnotationView` to an `MLNMapView` results in laggy map rendering.

**To Reproduce**

1. Run the attached sample app on iOS 15.
2. Try swiping on the map to pan.
3. Note the slow response to touch. Sometimes it will freeze for more than a second.

**Expected behavior**
The map should not freeze or be laggy with a single `UIView` annotation.

**Screenshots**
Sample application and video attached.

**Platform information (please complete the following information):**
Version: ios-v6.0.0
OS: iOS 15
Platform: iOS 15 running on iPhone 12

**Additional context**
Upgraded the iPhone 12 to iOS 17, and the issue is not reproducible.

**Comment by cgalvan** [comment]
[HelloMapLibre.zip](https://github.com/maplibre/maplibre-native/files/14303007/HelloMapLibre.zip)

https://github.com/maplibre/maplibre-native/assets/7519264/16a8d847-78e2-408d-b359-e706ccd17e2e

**Comment by sjg-wdw** [comment]
Wow, that's weird.  But it almost looks like a gesture delay to me.

**Comment by stefankarschti** [comment]
[This issue](https://github.com/mapbox/mapbox-gl-native-ios/issues/350) seems to be related

**Comment by funclosure** [comment]
Encounter this issue as well,
seems like it's related to `https://github.com/mapbox/mapbox-gl-native-ios/issues/350`

adding
`mapView.preferredFramesPerSecond = .lowPower` helps
https://github.com/mapbox/mapbox-gl-native-ios/issues/350#issuecomment-682022165

**Comment by louwers** [comment]
@stefankarschti Do we have an issue for the potential follow-up?

What new construct would be needed again? Sorry, I forgot the name.
