### ISSUE TITLE
Qt workflow failing:  404  Not Found

### ISSUE THREAD

**Issue by louwers** [maplibre/maplibre-native#2118]
https://github.com/maplibre/maplibre-native/actions/runs/7931770057/job/21659977297?pr=1908

There's an issue downloading dependencies on Ubuntu with the Qt workflow.

> E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/m/mesa/libegl-mesa0_23.0.4-0ubuntu1%7e22.04.1_amd64.deb  404  Not Found [IP: 20.106.104.242 80]

@ntadej If you have time, maybe you could have a look.

**Comment by louwers** [comment]
Maybe there is an outage and this will resolve itself.

**Comment by acalcutt** [comment]
It does seem more like an ubuntu apt failure than a real issue.
