### ISSUE TITLE
[iOS - Metal - v6.1.0] - lineDashPattern with steps disappears

### ISSUE THREAD

**Issue by nitrag** [maplibre/maplibre-native#2130]
**Describe the bug**
A line with a dash pattern + steps (forMLNStepping) will disappear or fail to render at certain zooms. Video compares iOS 5.13 and v6. 

**To Reproduce**
```swift
let styleLayer = MLNLineStyleLayer(identifier: layer.title, source: publishedVector)
styleLayer.sourceLayerIdentifier = "title"
styleLayer.minimumZoomLevel = 4
styleLayer.maximumZoomLevel = 18
styleLayer.lineColor = NSExpression(forConstantValue: UIColor.green)
styleLayer.lineWidth = NSExpression(forMLNInterpolating: .zoomLevelVariable,
                                   curveType: .linear,
                                   parameters: NSExpression(forConstantValue: 1),
                                   stops: NSExpression(forConstantValue: [4: 4,
                                                                          12: 5,
                                                                          15: 6]))
styleLayer.lineCap = NSExpression(forConstantValue: "round")
styleLayer.lineJoin = NSExpression(forConstantValue: "round")
styleLayer.lineDashPattern = NSExpression(forMLNStepping: .zoomLevelVariable,
                                          from: NSExpression(forConstantValue: [0.25, 1.5]),
                                          stops: NSExpression(forConstantValue: [
					                        9: NSExpression(forConstantValue: [1.0, 2.0]),
					                        16: NSExpression(forConstantValue: [2.0, 2.0])
					                      ]))
style.addLayer(styleLayer)
```

**Expected behavior**
The line renders correctly without disappearing.

**Screenshots**

v5

https://github.com/maplibre/maplibre-native/assets/197010/393cd4db-ab54-45a8-bd7c-ee54489ead8f

v6

https://github.com/maplibre/maplibre-native/assets/197010/63a2d713-0291-4439-b7dd-14d38d7ed882

**Platform information (please complete the following information):**
 - OS: iOS
 - Platform: iOS
 - Version v6.1

**Comment by louwers** [comment]
Thanks for the detailed bug report!

Is there any chance you can share the style used? Or another style that replicates the problem? This would help with debugging.

**Comment by nitrag** [comment]
Here is a minimal reproducible sample app using MapLibre v6.1, XCode 15.2, latest Swift v5, and iOS 17.2.

[MapLibreBugDashArray_v6_1.zip](https://github.com/maplibre/maplibre-native/files/14374777/MapLibreBugDashArray_v6_1.zip)

**Comment by matthiaskmt** [comment]
I'm also experiencing this issue with our style implementation. Is there any update on this issue?

**Comment by louwers** [comment]
@matthiaskmt Could you try the latest version just to make sure the bug is still present?

@sjg-wdw What do you think?

**Comment by matthiaskmt** [comment]
I'm currently using 6.8.0
