### ISSUE TITLE
icon halo does not work

### ISSUE THREAD

**Issue by westnordost** [maplibre/maplibre-native#2175]
Just like for text, on sdf icons, one can add a halo using the style properties [`icon-halo-color`](https://maplibre.org/maplibre-style-spec/layers/#paint-symbol-icon-halo-color), [`icon-halo-width`](https://maplibre.org/maplibre-style-spec/layers/#paint-symbol-icon-halo-width) etc.

Unlike for text, the halo for icons is not displayed correctly.

### Observations

This style definition

```kotlin
SymbolLayer("overlay-symbols", "overlay-source")
    .withProperties(
        textField(get("label")),
        textAnchor(Property.TEXT_ANCHOR_LEFT),
        textOffset(arrayOf(1.5f, 0f)),
        textMaxWidth(5f),
        textHaloColor("white"),
        textHaloWidth(1.5f),
        iconImage(get("icon")),
        iconColor("black"),
        iconHaloColor("white"),
        iconHaloWidth(1.5f),
    )
```

produces this render result:

![Screenshot_20240305_190828](https://github.com/maplibre/maplibre-native/assets/4661658/618ba770-7d5f-4803-b323-d9653317edee)

The displayed halo width seems to always be ~0 regardless of what is set.

Even when removing the halo, the SDF icon looks like the anti-aliasing does not work correctly:

![Screenshot_20240305_191043](https://github.com/maplibre/maplibre-native/assets/4661658/d46a1442-17aa-421a-a0a0-b7ddda0025fd)

It very much looks like the halo does only fill the pixels that would otherwise be half transparent.

When setting the `icon-halo-width` to 6 or above, the whole icon is filled with the halo color. (This might be different bug related to https://github.com/mapbox/mapbox-gl-js/issues/7204 ):

![Screenshot_20240305_192637](https://github.com/maplibre/maplibre-native/assets/4661658/2120f52c-9681-49e8-945c-1ff7bf6a62b2)

---

For comparison, this is how the icon looks like when it is not an SDF icon. Halos don't work on non-SDF icons, of course:

![Screenshot_20240305_191500](https://github.com/maplibre/maplibre-native/assets/4661658/405af3fc-e48d-47a3-aa06-01c3ecaf80c4)

### Platform information
 - OS: Tested on Android 13, Android 9
 - MapLibre: org.maplibre.gl:android-sdk:10.0.2

### Additional information

The lower the display density, the more visible is the halo issue.

The above screenshots were made on a device with 438 ppi display density (x3), the below screenshot was made on a device with 256 ppi display density (x1.5):

![310207361-275ea8c2-3761-4be4-a8cc-459f815d4389](https://github.com/maplibre/maplibre-native/assets/4661658/17c49af5-e847-4626-9a56-4a92c8e58e87)

**Comment by louwers** [comment]
Thanks for the report!

Can you share the sprite?
We do have render tests covering this feature. Maybe we can create a (failing) render test and go from there.

**Comment by westnordost** [comment]
Sure. The issue appears for all sprites. I am using the sprites from iD editor presets. This particular sprite can be found here:

https://raw.githubusercontent.com/mapbox/maki/main/icons/restaurant.svg

**Comment by louwers** [comment]
@westnordost A sprite is all the different icons.

**Comment by westnordost** [comment]
But that means that maybe the issue is also not in the rendering of the halo per se, but in the conversion of the Android bitmap to whatever MapLibre uses internally.

**Comment by louwers** [comment]
Yeah probably, because we have this pretty well covered by tests.

Could you try using a sprite?

```
  "sprite": "https://openmaptiles.github.io/osm-bright-gl-style/sprite",
```

**Comment by westnordost** [comment]
Can a PNG be a SDF? It's a raster graphic, after all.

**Comment by westnordost** [comment]
Anyway, the icon is really small, but it looks like this. Does that help?

![image](https://github.com/maplibre/maplibre-native/assets/4661658/bf96c42e-d9ac-4e2d-8d8b-b4a805b817cd)

**Comment by westnordost** [comment]
Also, here is a video of the effect. It is much better visible on a dark background:

https://github.com/maplibre/maplibre-native/assets/4661658/04047462-d9e8-41e4-bc60-b06a8931b776

Also tested with org.maplibre.gl:android-sdk:11.0.0-pre4, same issue.

**Comment by wipfli** [comment]
> Can a PNG be a SDF? It's a raster graphic, after all.

I think so. Signed distance fields are also raster graphics. Each pixel encodes the distance to the nearest edge.

**Comment by louwers** [comment]
@westnordost I tried OSM Bright (hosted by MapTiler), which has these labels and they seem to be working fine.

![Screenshot_20240416-143817_MapLibre Native Android TestApp](https://github.com/maplibre/maplibre-native/assets/649392/d0dd35a0-af2e-4819-a4e2-59bdd3b99c69)

**Comment by louwers** [comment]
@westnordost Can you share the PNG that you use?

**Comment by louwers** [comment]
Looking at your code, you seem to be adding an SVG. Please re-open if I misunderstood.

If you want halo to work you need to convert your image to a SDF.

You can use this tool to convert images: https://www.npmjs.com/package/@elastic/spritezero

**Comment by westnordost** [comment]
Yes, correct, it is an SVG. However, before passing it to MapLibre, it is rasterized, so as far as MapLibre is concerned, it is a bitmap. So, using `SDF` only works if the source graphic already is an SDF? In that case, it may be worth making this clear in the documentation.

**Comment by westnordost** [comment]
I've looked in the codebase to maybe create a PR for that, but found that the documentation is sufficient, so, I misunderstood it. Sorry for the noise!

**Comment by louwers** [comment]
No problem, I also didn't know, this issue is now part of the documentation. 🙂
