### ISSUE TITLE
No `Feature`s in android-v11.0.0-pre0

### ISSUE THREAD

**Issue by Helium314** [maplibre/maplibre-native#2176]
**Describe the bug**
There is no `Feature` class, and nothing related to that is mentioned in the release notes.

**To Reproduce**
1. Have an app using MapLibre 10.0.2
2. Upgrade to android-v11.0.0-pre0 (use .aar file directly)
3. Do the necessary renames
4. Notice there is no replacement for `Feature` and related classes, also Android Studio does not suggest any import with that name

**Expected behavior**
Either I can continue setting `Feature`s in `GeoJsonSource`s, or release notes state what has changed here.
(I guess creating a json string and setting that might work, didn't try)

**Platform information (please complete the following information):**
irrelevant (app does not compile)

**Comment by louwers** [comment]
Please import it from

```
import com.mapbox.geojson.Feature
```

this class is part of the https://github.com/maplibre/maplibre-java package which is not updated yet.
