### ISSUE TITLE
mbgl::ActorRef is not safe if the bind Actor is destroyed after  ActorRef be created

### ISSUE THREAD

**Issue by vinsentli** [maplibre/maplibre-native#2203]
in the ActorRef document , it marks "sending a message to a   `Ref` whose `Actor` has died is a no-op", but actually is not safe.

<img width="478" alt="image" src="https://github.com/maplibre/maplibre-native/assets/7352338/3ea9b418-f4ff-4223-aa54-69607cb38e11">

<img width="902" alt="image" src="https://github.com/maplibre/maplibre-native/assets/7352338/522524d3-8393-40f4-ae23-10f710877aa3">

**Comment by louwers** [comment]
You are right that it is only safe when the lifetime of the mailbox and the object match.

**Comment by vinsentli** [comment]
Would it be better to replace it with (std::shared_ptr<Object>)?

**Comment by sjg-wdw** [comment]
Might want @mwilsnd to comment on this.
