### ISSUE TITLE
Color problem on buildings at high zoom levels in Metal

### ISSUE THREAD

**Issue by sjg-wdw** [maplibre/maplibre-native#2215]
A user is seeing a problem with zoom based color interpolation on buildings.  The app is proprietary so we can't get a video, but having seen it it looks like a tweaker calculating zoom based colors that's either running off the end of the range of just stopping.  I can share a style that replicates it and we can start from there.

**Comment by louwers** [comment]
May be related to https://github.com/maplibre/maplibre-native/issues/2217 which does have a video.
