### ISSUE TITLE
The user location icon not shown for MapLibre Native 11-pre

### ISSUE THREAD

**Issue by hy9be** [maplibre/maplibre-native#2216]
**Description**
In certain cases the user location icon (puck) is not shown. This happens with both regular icon as well as custom icons.

**Reproducing steps**
1. Launch Maplibre Native Test app for version 11.0.0-pre4
2. Scroll down to the "Location" section
3. Go to LocationModesActivity
4. Note that user location icon is not visible.

This seems a regression from version 10.x

**Expected behavior**
User location icon is shown.

**Platform information**
Android

**Additional context**
The user location icon appears if you change from:
``useSpecializedLocationLayer(true)``
to
``useSpecializedLocationLayer(false)``

Other tests pass, because useSpecializedLocationLayer is not called. If it is set to false in other tests they also break.

**Comment by louwers** [comment]
I can reproduce this problem with the Drawable renderer, but not with the Legacy renderer.

**Comment by louwers** [comment]
Fixed by #2356

Follow-up https://github.com/maplibre/maplibre-native/issues/1654
