### ISSUE TITLE
Strange Parser::parseLayers segfault on MacOS ARM64

### ISSUE THREAD

**Issue by AustinEvansWX** [maplibre/maplibre-native#2218]
**Describe the bug**
Segfault while parsing style layer.

**To Reproduce**
1. Follow build steps from [maplibre-native-qt](https://github.com/maplibre/maplibre-native-qt/) to build Qt Widgets example app.
2. Run app.

**Expected behavior**
The app to parse styles and run as usual.

**Screenshots**
Attached video of behavior below

https://github.com/maplibre/maplibre-native/assets/63173186/de599d0f-3c3f-4833-ab99-72f74b6c352c

**Platform information:**
 - OS: MacOS Sonoma Version 14.3.1
 - Platform: Qt
 - Version: 3.0.0

**Additional context:**
I tracked down the segfault to a [line of code in parser.cpp](https://github.com/maplibre/maplibre-native/blob/main/src/mbgl/style/parser.cpp#L221) fetching the "id" property of the parsed JSON for a given layer.
If I change the code from:
```c++
const JSValue& id = layerValue["id"];
```
To:
```c++
const JSValue& id = layerValue.FindMember("id")->value;
```
The segfault goes away. 

The strange part is that I placed a log prior to the layer id access and with the existing code it doesn't log before it segfaults even though it should be called prior. 

I tested taking all of the code from within the loop and putting it outside and just running it on layer 0 and it works just fine. It's only when it's inside the loop that it segfaults. 

Since the log prior isn't being logged and it only happens inside of the loop, it makes me think that there may be some compiler optimizations being done that breaks it. My knowledge on that is very sparse though. Let me know what y'all think!

**Comment by louwers** [comment]
Did you flush the log buffer?

**Comment by louwers** [comment]
Out of curiosity, how did you track down the crash? What does your workflow look like? Did you use cmake to generate an Xcode config that allows you to step through the main library?

Any chance you could make a PR with this fix? 🙂 

cc @ntadej

**Comment by ntadej** [comment]
Note that Qt currently uses OpenGL 2 branch by default so the fix should also be backported there.

**Comment by AustinEvansWX** [comment]
I created two PRs for main and opengl-2.

> Out of curiosity, how did you track down the crash? What does your workflow look like? Did you use cmake to generate an Xcode config that allows you to step through the main library?

Apple's crash report told me it was coming from Parser::parse so I started there then I basically just binary searched with printf to narrow it down haha.

**Comment by AustinEvansWX** [comment]
Closing since the PRs were merged. Thanks guys!
