### ISSUE TITLE
Could not find com.mapbox.mapboxsdk:mapbox-android-accounts:0.7.0.

### ISSUE THREAD

**Issue by mvnh** [maplibre/maplibre-native#2222]
**Describe the bug**
After implementing "com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.9.0", which I need to use SymbolManager so I can create a custom marker, app stops building with the following error:

Could not resolve all files for configuration ':app:debugCompileClasspath'.
   Could not find com.mapbox.mapboxsdk:mapbox-android-accounts:0.7.0.
   Required by:
       project :app > com.mapbox.mapboxsdk:mapbox-android-sdk:9.2.0

Just in case, I note that I have no implementation of "com.mapbox.mapboxsdk:mapbox-android-sdk:9.2.0", only "org.maplibre.gl:android-sdk:10.3.0"

**To Reproduce**
1. Go to "build.gradle.kts (Module :app)"
2. Implement "com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.9.0"
3. Sync Gradle project

**Expected behavior**
The application will build and run

**Screenshots**
-

**Platform information (please complete the following information):**
 - OS: Windows 11 Home Single Language
 - Platform Android, Java
 - Version | SDK 34, Gradle 8.7

**Additional context**
If needed, repository with my application code is pinned in my profile

**Comment by louwers** [comment]
Could you try this one? https://central.sonatype.com/artifact/org.maplibre.gl/android-plugin-annotation-v9

Sorry for the confusion.

**Comment by mvnh** [comment]
> Could you try this one? The Mapbox Annotations plugin does not work with MapLibre Native. https://central.sonatype.com/artifact/org.maplibre.gl/android-plugin-annotation-v9
> 
> Sorry for the confusion.

I'll try today, thanks!

**Comment by louwers** [comment]
OK feel free to open an issue [here](https://github.com/maplibre/maplibre-plugins-android) if you have problems with it.

**Comment by mvnh** [comment]
> Could you try this one? The Mapbox Annotations plugin does not work with MapLibre Native. https://central.sonatype.com/artifact/org.maplibre.gl/android-plugin-annotation-v9
> 
> Sorry for the confusion.

It worked. Thanks a lot!

**Comment by turcandan** [comment]
> Could you try this one? The Mapbox Annotations plugin does not work with MapLibre Native. https://central.sonatype.com/artifact/org.maplibre.gl/android-plugin-annotation-v9
> 
> Sorry for the confusion.

What exactly is to be tried here? What should I do with this XML code?

**Comment by mvnh** [comment]
> > Could you try this one? The Mapbox Annotations plugin does not work with MapLibre Native. https://central.sonatype.com/artifact/org.maplibre.gl/android-plugin-annotation-v9
> > Sorry for the confusion.
> 
> What exactly is to be tried here? What should I do with this XML code?

choose what you are using (maven, gradle, gradle kotlin) in the “snippets” tab, copy the line of code that adds this dependency, and paste it into the build file to add it

**Comment by turcandan** [comment]
@mvnh Thanks for the fast reply. Unfortunately it didn't help me, I'm not having issues with the accounts library, but with the search autocomplete one. The library is added successfully, I can use it's basic functionality, but when I'm trying to send in some more parameters, for example a **PlaceAutocompleteOptions** object, I can't instantiate it because "_Cannot access class com.mapbox.search.common.IsoLanguageCode. Check your module classpath for missing or conflicting dependencies_". 
Seems like I need to add some more dependencies for it, but I can't figure out which ones.

**Comment by mvnh** [comment]
> @mvnh Thanks for the fast reply. Unfortunately it didn't help me, I'm not having issues with the accounts library, but with the search autocomplete one. The library is added successfully, I can use it's basic functionality, but when I'm trying to send in some more parameters, for example a **PlaceAutocompleteOptions** object, I can't instantiate it because "_Cannot access class com.mapbox.search.common.IsoLanguageCode. Check your module classpath for missing or conflicting dependencies_". Seems like I need to add some more dependencies for it, but I can't figure out which ones.

seems like it is mapbox problem: https://github.com/mapbox/mapbox-search-android/issues/177
have no idea what to do with it, sorry

**Comment by louwers** [comment]
MapLibre Native Android does not have a plugin for that as far as I am aware. There is not likely to be any compatibility with old open source or recent proprietary Mapbox plugins.

**Comment by turcandan** [comment]
> MapLibre Native Android does not have a plugin for that as far as I am aware. There is not likely to be any compatibility with old open source or recent proprietary Mapbox plugins.

How do I know if I'm using MapLibre Native Android?  I'm using a library for maps, as far as I know it's using c++ and open GL(not mapbox library). 
I don't really get it, why is a compatibility needed? I'm just trying to use their SDK for Search according with the instructions published on their web site.
