### ISSUE TITLE
Node.js Windows CI Broken

### ISSUE THREAD

**Issue by louwers** [maplibre/maplibre-native#2256]
I updated the Node.js packages, it silently broke the Linux and macOS builds. I fixed those, but now the Windows Node.js build is failing.

https://github.com/maplibre/maplibre-native/actions/runs/8638457928/job/23682950776

I think @acalcutt ran into this one as well.

**Comment by acalcutt** [comment]
Just an FYI, I think this is a different issue I started to encounter last night when I was testing.

I had determined my issue was related to the macos cmake fix I did, which removed the default shell, it cause windows configure to run as powershell (which broke it). After a lot of tweaking I had figured out how to get the cmake fix to run without changing the default shell. Right as I figured that out last night, I started getting a new windows error which I think is what you are getting now.

**Comment by acalcutt** [comment]
It looks like it worked for me in this commit anyway 
https://github.com/maplibre/maplibre-native/pull/2252/commits/8238c791b4f3c431009a49b5c1ad3af51e76b3b9

I think that might be the last I saw it work though.

**Comment by louwers** [comment]
@acalcutt https://github.com/microsoft/vcpkg/issues/38116 👀

**Comment by acalcutt** [comment]
Looking in the comments in some link threads it seems like maybe this is cause y something that will be reverted in 3.26.2 , so I wonder when that will be in the github runners
