### ISSUE TITLE
`fill-extrude` layer is drawn above the next-above symbol layer

### ISSUE THREAD

**Issue by westnordost** [maplibre/maplibre-native#2259]
**Describe the bug**
The icons shown in a `symbol` layer are drawn behind the geometries in a `fill-extrude` layer if the latter is immediately below the former in the layer list.

**To Reproduce**
1. Put a `symbol` layer directly above (i.e. after, in the layer list) a `fill-extrude` layer in a style json
2. Notice that the symbols are drawn behind the geometry in the `fill-extrude` layer

**Expected behavior**
`fill-extrude` should respect the layer order **or** the documentation should be updated to explain this.

**Screenshots**
![Screenshot_20240412_142612](https://github.com/maplibre/maplibre-native/assets/4661658/2364917e-fe2b-448e-abfc-bbcf8e3162e3)

**Platform information (please complete the following information):**
 - OS: Android 13
 - Version 11-pre04

(Only tested with v11-pre04)

**Comment by westnordost** [comment]
It looks like this is fixed with `org.maplibre.gl:android-sdk:11.3.0-vulkan-pre0`.

**Comment by louwers** [comment]
https://github.com/maplibre/maplibre-native/issues/2894 contains a reproduction


---

From @Zverik:

Sometimes extruded buildings cover symbols and labels. Which never happens with MapLibre GL JS (on web) — and that made debugging this quite hard.

I was testing with Flutter package, which uses MapLibre Native for Android. We have also encountered this bug on a native Android application using the SDK.

After some experimenting, I narrowed styles to replicate this to those two:

* [style2.json](https://github.com/user-attachments/files/17234852/style2.json) — between zooms 15 and 15.5, `poi_r1` layer is covered by `building-3d` layer. There is no mention of zoom 15.5 in the style, so the reason buildings cover POI on on zoom and don't on others is unknown.
* [style2_old.json](https://github.com/user-attachments/files/17234853/style2_old.json) — same style without `building` and `poi_r7` layers. While it should not have affected the outcome, instead extruded buildings cover POI on all zooms 15+.

When you remove any layers from the `label` group, suddenly extruded buildings stop covering POI symbols. That is the most baffling: why labels affect this, and why not "all labels".

Versions:

* maplibre_gl flutter package: ^0.20.0
* maplibre-native for android: v11.0.0
* android 14 on sony xperia 10 vi

A screenshot:

![extruded-fail](https://github.com/user-attachments/assets/9e08cac0-0314-47b7-9afe-479ee5e91530)

See also #2776.

**Comment by Zverik** [comment]
We have been testing, and the bug does not seem to completely go away with the Vulcan build. For POI — yes, it is fixed. But instead, landuse labels (e.g. park and pond names) get obscured by extruded buldings. Even on non-adjusted styles: [osm-liberty](https://github.com/maputnik/osm-liberty) shows this between zooms 14 and 15.

I'm doing more tests (using modified flutter library, so not sure it does use vulkan), but our Android developer reports this.

![black-pearl-vulcan-bug](https://github.com/user-attachments/assets/07cb5921-fe4f-4453-bca7-4f9c124784d0)

**Comment by alexcristici** [comment]
From what I tested so far it seems that this issue is happening only on OpenGL, not on Vulkan or Metal. 
I'm looking into it.
