### ISSUE TITLE
Publish Current updates as 11.0.0-pre5

### ISSUE THREAD

**Issue by kocheick** [maplibre/maplibre-native#2261]
The current version of Maplibre  11.0.0-pre4 still uses mapbox under the wood.
I start working on updating the android plugins to be used with Maplibre instead of Mapbox.
I would need the android-geojson plugin 6.0.0 which has the correct imports/updates but current version( 11.0.0-pre4) uses 5.9.0 which still uses Mapbox under the wood.

Upon checking source code, I can see that maplibre android has been correctly updated to reflect these changes, however they have not been published hence I diont have access to them in order to work on the plugins.
I'm simply requesting to publish current state as 11.0.0-pre5 so we can move on. 
Thanks

**Comment by louwers** [comment]
Sure.

**Comment by kocheick** [comment]
Version 11.0.0-pre4 still uses con.mapbox.geojson instead of org.maplibre.geojson.

Upon checking the repository code, I can see it's been updated to use org.maplibre... but the published version on Maven Central doesn't include that update.

I'm looking to update all the android plugins to use org.maplibre, however most of them will depends on mapLibre.android and its dependencies but current version 11.0.0-pre4 still uses mapbox instead of maplibre when it comes to package naming.

**Comment by louwers** [comment]
It's released! 👍  https://github.com/maplibre/maplibre-native/releases/tag/android-v11.0.0-pre5

**Comment by kocheick** [comment]
Beautiful! 
It looks good on my end as well, thank you !
