### ISSUE TITLE
icon halo is not scaled with screen density

### ISSUE THREAD

**Issue by westnordost** [maplibre/maplibre-native#2281]
**Describe the bug**
The halo as specified by `text-halo-width` is scaled by display density, or in other words, the value specified is in <abbr title="device independent pixel">**dp**</abbr> rather than **px**.

The halo as specified by `icon-halo-width` however does not take into account display density, or in other words, the value is specified in  **px**.

**To Reproduce**

Have a style that defines both an icon halo and a text halo with the same width. Observe that the icon halo width is only 1/3rd or so on smartphone devices with extra high dpi.

**Expected behavior**
`icon-halo-width` should be in dp.

**Screenshots**
In the following screenshot from a smartphone with high display density, for both icon halo and text halo, the value of `3` was set.
![image](https://github.com/maplibre/maplibre-native/assets/4661658/f483ff96-d207-4baa-a713-816680559a11)

The SDF icon used in the screenshot above is this one:

![icon](https://github.com/maplibre/maplibre-native/assets/4661658/d9f82681-9898-4e02-bb8c-76ad3b9e1908)

**Platform information (please complete the following information):**
 - OS: Android 13
 - Version v11-pre4

**Comment by louwers** [comment]
According to the style spec, they should both be px.

@HarelM Do you know what the behavior of MapLibre GL JS is?

I think it's going to be hard to change this in a backwards compatible manner.

**Comment by westnordost** [comment]
Oh, are you sure? As far as I know, other widths such as e.g. `line-width` are all in dp, or "CSS pixels", which are dp as far as I know.

**Comment by HarelM** [comment]
I honestly have no clue, sorry, but I guess the same style.json can be used in a jsbin to see what the behavior in GL JS is.
I've seen a lot of code related to device pixel ratio in the GL JS code, so it might be more polished there.
I think the same approach can be taken for `geometry-type` in this aspect - if there's a need to align the code with the spec then we can do it in a breaking change version.

**Comment by westnordost** [comment]
I've checked with how it looks like on maplibre-gl-js. This is definitely a bug in maplibre-native.

Using the [MapTiler streets-v2 style](https://www.maptiler.com/maps/#style=streets-v2&mode=2d&position=20.39/53.5769841/9.9487442):

![image](https://github.com/maplibre/maplibre-native/assets/4661658/c65fff40-b518-454e-bff6-2766911ac651)

The style sets `icon-halo-width` and `text-halo-width` both to 2.

**Comment by louwers** [comment]
Sounds like the style spec needs to be updated.

Did you also observe this with 10.x.x by any chance?

**Comment by westnordost** [comment]
No, I only started testing (this) with 11.

**Comment by louwers** [comment]
Related issue https://github.com/mapbox/mapbox-gl-style-spec/issues/66

**Comment by mtpdog** [comment]
Could you please post the code how your icon halo is set?
For some reason on 11-pre5 icon color is not displayed while text color works. I think it's some stupid mistake on my side.

**Comment by westnordost** [comment]
As far as I understand the linked issue, given how halos (on fonts) apparently work on the technical level, I guess specifically for **icon** halos, a guarantee about their displayed pixel size can only be made on a given blur radius used for the icon. I.e. if the spec is updated, it should mention the "standard" blur radius that would need to be used for a value of `1` to actually match 1 pixel.

**Comment by westnordost** [comment]
@mtpdog this is offtopic here, maybe you want to join the chat on slack? Anyway, icon halo only works on SDF icons. These are monochrome icons with alpha channel which basically have been blurred a lot (maybe using a specific blurring algorithm, not sure). When adding such images programmatically, you need to specify that the image(s) you add are actually SDFs. (And if via style, there is a property somewhere.) MapLibre does not prepare your icons as SDFs itself.

**Comment by westnordost** [comment]
My assumption in the starter post may be wrong. Currently investigating.

**Comment by westnordost** [comment]
The following screenshot was made from a smartphone with a display density that results in a scaling of x1.5 **after the icon halo width has been scaled programmatically by that factor in reference to this bug report**

![image](https://github.com/maplibre/maplibre-native/assets/4661658/372b2835-1a91-4c6c-8460-e39f2a1a0984)

In other words, if the assumption for the source of this bug 

>  The halo as specified by text-halo-width is scaled by display density, or in other words, the value specified is in dp rather than px.

was true, it should have been rendered with the same width.

**Instead, the halo width of the icon(s) is always half of independent of display density.**

After having read how the SDF stuff works on the technical side, this could just be very much related to with which blur radius the icons were blurred. See also https://github.com/maplibre/maplibre-native/issues/2281#issuecomment-2063517533

Can you tell with which radius font glyphs are blurred for MapLibre?

**Comment by wipfli** [comment]
> Can you tell with which radius font glyphs are blurred for MapLibre?

Not sure I understand the question correctly, but in MapLibre, signed distance fields for glyphs go at most to a distance of 8 outside the glyph. 

See https://github.com/maplibre/maplibre-gl-js/blob/8e74a6b0e9a76e75379a184fbc8b94cdf41de4e9/src/shaders/symbol_sdf.fragment.glsl#L1

and 

https://github.com/mapbox/sdf-glyph-foundry/blob/6ed4f2099009fc8a1a324626345ceb29dcd5277c/include/mapbox/glyph_foundry_impl.hpp#L314

**Comment by westnordost** [comment]
I tested it and indeed if I create the signed distance field for icons also with a radius of 8, the halo width of icons is shown at the same width as for the text (when both `text-halo-width` and `icon-halo-width`), regardless of display density.

So, this issue is invalid. I will look into creating a PR to mention the magic number 8 in the documentation for `icon-halo-width` :-)
