### ISSUE TITLE
Include debug symbols with Android releases

### ISSUE THREAD

**Issue by louwers** [maplibre/maplibre-native#2282]
Include debug symbols with Android releases so developers can symbolicate crash logs, similar to how we are doing for iOS now.

**Comment by stefankarschti** [comment]
I think it's controlled via `CMAKE_INSTALL_DO_STRIP` variable. `llvm-strip` is called based on it.

**Comment by louwers** [comment]
Sounds like CMake should include debug symbols when called via Gradle https://github.com/android/ndk/issues/243

**Comment by louwers** [comment]
I think they are here after a build:

```
% ls -lh MapLibreAndroid/build/intermediates/library_jni/drawableRelease/jni/arm64-v8a/libmaplibre.so 
-rw-r--r--@ 1 bart  staff   191M Apr 17 15:50 MapLibreAndroid/build/intermediates/library_jni/drawableRelease/jni/arm64-v8a/libmaplibre.so
```

There is no `build/intermediates/cmake` directory anymore.

**Comment by stefankarschti** [comment]
yes, the file size indicates there's contained debug information
