### ISSUE TITLE
Symbol with text fails on Android-11-pre5 ("text-field" issue)

### ISSUE THREAD

**Issue by mtpdog** [maplibre/maplibre-native#2285]
**Describe the bug**
If Symbol **without** text is added to the map then it shows fine.
If the text property is set for Symbol - then the whole layer fails to display.

I've traced the issue to this line in the SymbolManager:
`layer.setProperties(textField(get(SymbolOptions.PROPERTY_TEXT_FIELD)));`
So probably this is some issue with displaying "text-field" parameter in the native map.

**To Reproduce**
1. Add Symbol with text
2. Do not see it on the map

**Platform information (please complete the following information):**
 - OS: Android-11-pre5 (was the same on pre4)

**Comment by louwers** [comment]
Could you share a more detailed reproduction steps?

**Comment by westnordost** [comment]
FWIW I can't reproduce it with my setup, neither on pre4 nor pre5. A layer with text + icons renders just fine.

**Comment by mtpdog** [comment]
Sorry. I've found the issue. Text font was not set properly.
