### ISSUE TITLE
[Android] Add shared object files with symbols attached to GitHub releases page

### ISSUE THREAD

**Issue by mattlogan** [maplibre/maplibre-native#232]
In addition to publishing Android library `.aar` files, Mapbox provides `.so` files for each release that have debug symbols attached. These shared object files allow library users to desymbolicate native crashes using the `objdump` tool from the Android NDK. It seems that MapLibre does not make these shared object files public.

Please consider adding these files to the public releases page as part of the release process.

The debuggable shared object files can be found in `platform/android/MapboxGLAndroidSDK/build/intermediates/cmake/release` after building the library.

This is what the Mapbox releases page looks like: https://github.com/mapbox/mapbox-gl-native-android/releases

And here are the docs for desymbolicating native crashes: https://github.com/mapbox/mapbox-gl-native-android/wiki/Getting-line-numbers-from-an-Android-crash-with-ndk-stack#extracting-source-files-and-line-numbers

**Comment by louwers** [comment]
@mattlogan We have this now.
