### ISSUE TITLE
Validate Location Services on iOS getting stuck

### ISSUE THREAD

**Issue by sjg-wdw** [maplibre/maplibre-native#2336]
When the app first comes into the foreground the MLNView will make a call to validateLocationServices which will eventually ask the the user permission.  In some obscure cases this will lock up and then get the app killed by the watchdog.  Can't duplicate it at the moment, only showing up in deployment.

0   libsystem_kernel.dylib              0x0000000001e93bd178 mach_msg2_trap + 8
1   libsystem_kernel.dylib              0x0000000001e93bcf10 mach_msg2_internal + 80
2   libsystem_kernel.dylib              0x0000000001e93bce28 mach_msg_overwrite + 436
3   libsystem_kernel.dylib              0x0000000001e93bcc68 mach_msg + 24
4   libdispatch.dylib                   0x0000000001a9c97f00 _dispatch_mach_send_and_wait_for_reply + 540
5   libdispatch.dylib                   0x0000000001a9c982a0 dispatch_mach_send_with_result_and_wait_for_reply + 60
6   libxpc.dylib                        0x00000000020bcc16d4 xpc_connection_send_message_with_reply_sync + 264
7   Foundation                          0x0000000001a0c5bc70 __NSXPCCONNECTION_IS_WAITING_FOR_A_SYNCHRONOUS_REPLY__ + 16
8   Foundation                          0x0000000001a0c44388 -[NSXPCConnection _sendInvocation:orArguments:count:methodSignature:selector:withProxy:] + 2160
9   Foundation                          0x0000000001a0c43adc -[NSXPCConnection _sendSelector:withProxy:arg1:arg2:arg3:] + 136
10  Foundation                          0x0000000001a0caf8a0 _NSXPCDistantObjectSimpleMessageSend3 + 76
11  CoreLocation                        0x0000000001aeec6014 0x1aee0d000 + 757780
12  CoreLocation                        0x0000000001aeecdcec 0x1aee0d000 + 789740
13  CoreLocation                        0x0000000001aee3f300 0x1aee0d000 + 205568
[Two levels of the user's app deleted here.  They do have their own navigation logic which kicks off CoreLocation]
16  MapLibre                            0x00000000010918fb5c -[MLNMapView validateLocationServices] (MLNMapView.mm:0)
17  MapLibre                            0x00000000010917e2e8 -[MLNMapView willEnterForeground:] (MLNMapView.mm:1918)

Their question is if we can delay kicking that off until the view actually appears.  I'm not sure we should, but let's discuss what might be going on.

**Comment by sjg-wdw** [comment]
Do a quick web search and let us know what you find.

**Comment by sjg-wdw** [comment]
Those missing functions are in their stack, which is why I redacted them.  So they have their own location services shim which then calls out to Core Location later on.  I think they probably use this to spoof the location if they need to.

**Comment by stefankarschti** [comment]
Then Initially I suggest trying not to call `validateLocationServices` from `willEnterForeground` to check if it still happens.
I'd also check in their code if there are any operations that are incompatible with `willEnterForeground`. Blocking the main thread for extensive periods of time would be such example.

**Comment by sjg-wdw** [comment]
I think it's just the iOS permission check that somehow ends up blocking.
But if we don't call validateLocationServices from the MapLibre view is that likely to break things?

**Comment by sjg-wdw** [comment]
They don't modify the MapLibre code itself, so it should be unchanged.  But they do appear in the stack trace since they've got their own shim for the location module.
