### ISSUE TITLE
When will the ScaleBarPlugin compatible with android-v11.0.0 Maplibre version be updated?

### ISSUE THREAD

**Issue by EULUSOY** [maplibre/maplibre-native#2381]
How do we add scalebar in the latest version of Maplibre Android SDK? Tutorials are old; Not compatible with Mapbox.

**Comment by louwers** [comment]
Thanks for reporting this. 

I created an issue here: https://github.com/maplibre/maplibre-plugins-android/issues/54

**Comment by louwers** [comment]
![image](https://github.com/maplibre/maplibre-native/assets/649392/0bfc1e4a-fe00-4960-87bf-860cea33b902)

PR here: https://github.com/maplibre/maplibre-plugins-android/pull/50
