### ISSUE TITLE
Compile for Android with support for 16 KB page sizes

### ISSUE THREAD

**Issue by louwers** [maplibre/maplibre-native#2429]
> Beginning with Android 15, Android supports devices that are configured to use a page size of 16 KB (16 KB devices). If your app uses any [NDK](https://developer.android.com/ndk) libraries, either directly or indirectly through an SDK, then you will need to rebuild your app for it to work on these 16 KB devices.

https://developer.android.com/about/versions/15/behavior-changes-all#16-kb

We need to push out a new 11.x.x release and probably also 10.x.x since some people still on the 10.x.x series will want support.

**Comment by louwers** [comment]
> If your app dynamically links to the C++ standard library (libc++_shared.so) from Android NDK r26 or lower, then it is recommended to move to Android NDK r27 or higher to update to the 16 KB ELF aligned version of the C++ standard library. Otherwise, your app will fail to install on 16 KB devices.

Do we dynamically link to the C++ standard library on Android?

**Comment by tylerjroach** [comment]
Has this effort started yet? Android 15 has now been released, and although its unlikely that manufacturers immediately default to 16 KB page sizes, Pixel devices will be able to easily switch to 16KB page sizes with a developer options setting. Tracking this change as we have a library that will rely on maplibre 16KB page size support.
