### ISSUE TITLE
Spelling mistake in Website

### ISSUE THREAD

**Issue by dpakprajul** [maplibre/maplibre-native#2439]
**Describe the bug**
I might be a little dumb to put this thing as an issue, I wanted to report it to the community anyway. There is a spelling mistake in the landing page of maplibre website

**To Reproduce**
1. Go to https://maplibre.org/
2. In the section Maplibre Native, there is a spelling mistake.

**Screenshots**
![grafik](https://github.com/maplibre/maplibre-native/assets/38970123/5936733f-14dc-40ba-91f2-e3ce08e8d642)

**Comment by louwers** [comment]
Thanks.
