### ISSUE TITLE
[iOS] Zoom issue in release version 5.13.0-pre.1

### ISSUE THREAD

**Issue by davidmtamas** [maplibre/maplibre-native#245]
We noticed that there is a weird zoom-in glitch on the map whenever the app enters background state, please see the attached video of the issue.

https://user-images.githubusercontent.com/13013774/156368946-f22288d5-2859-4cdf-a0cd-399a5cec17dc.mp4

We tried to reproduce the problem on versions 5.12.0 and 5.12.2 but it doesn't occur. From our testing we also found that the issue is independent of camera settings (altitude, pitch etc) or map styles.

We've attached a [demo project](https://github.com/maplibre/maplibre-gl-native/files/8169797/MapLibreZoomDemo.zip) where the issue is 100% reproducible.

**Comment by louwers** [comment]
Metal is now being implemented using an alternate approach, namely using a rendering backend that uses Metal-cpp directly.

Progress can be tracked here: https://github.com/orgs/maplibre/projects/8
