### ISSUE TITLE
Missing `com.mapbox` replacement on annotation layer ID

### ISSUE THREAD

**Issue by Fabi755** [maplibre/maplibre-native#2498]
Is there a reason why the [MapLibreConstants.LAYER_ID_ANNOTATIONS](https://github.com/maplibre/maplibre-native/blob/e755646eae8e248756db8a8a207635f03fe043ca/platform/android/MapLibreAndroid/src/main/java/org/maplibre/android/constants/MapLibreConstants.java#L200) is always `com.mapbox.annotation.points` and not migrated to `org.maplibre.annotations.points`.

Is see that the native code has already migrated to MapLibre naming. For example the [AnnotationManager](https://github.com/maplibre/maplibre-native/blob/e755646eae8e248756db8a8a207635f03fe043ca/src/mbgl/annotation/annotation_manager.cpp#L36)

By [migrating the navigation SDK to v11](https://github.com/maplibre/maplibre-navigation-android/pull/110), I have some issue with the layer order, and I'm not sure if this is the cause of this.

**Comment by Fabi755** [comment]
I see there are still a lot of other constant values that contains the *mapbox* naming. Is this not converted yet in the full Java code?

**Comment by louwers** [comment]
Looks like it could be problematic. Thanks for reporting.
