### ISSUE TITLE
[iOS - SwiftUI] MLNAnnotationView delay with map panning

### ISSUE THREAD

**Issue by Max-Leopold** [maplibre/maplibre-native#2522]
This is a follow up from https://github.com/maplibre/maplibre-native/issues/2053

**Describe the bug**

MLNAnnotationViews sometimes have a delay when panning the map when using SwiftUI. 

**To Reproduce**

It's a bit inconsistent to reproduce the bug. The way that worked for me most of the time is to zoom in on the map with a flick and then interrupt the zoom and pan the map. 
Generally if you play around with panning the map right after a zoom you will eventually encounter the bug.

I made a demo app which can be used to test: [TestMap.zip](https://github.com/user-attachments/files/15919848/TestMap.zip)

**Expected behavior**

The MLNAnnotationView should not have a delay when panning the map.

**Screenshots**
In the video you can see that in the beginning the annotation doesn't "wobble" but sticks to it's coordinates. However later you see a delay when panning the map.

https://github.com/maplibre/maplibre-native/assets/26352108/4d1d257b-6293-4fa0-97fe-5b9386e92737

**Platform information (please complete the following information):**
 - OS: iOS
 - Version: 6.5.0

**Comment by nnhubbard** [comment]
I have this same issue as seen in my app testing:


https://github.com/maplibre/maplibre-native/assets/30858/b194055d-e998-42b2-a83a-e59b66d4d124



It happens in the same way as described by @Max-Leopold where you sort of flick the map and it pans animated and the custom annotations do not stay in place during the pan animation.

**Comment by alexcristici** [comment]
I applied the workaround (https://github.com/maplibre/maplibre-native/pull/2148) that was removed, but this issue seems a different one.

**Comment by nnhubbard** [comment]
@alexcristici Do we have an ETA for when this might be worked on?

**Comment by nnhubbard** [comment]
That seems to have fixed the issue! Thank you!

**Comment by jorgealegre** [comment]
Same here! Thank you very much!! I wonder what the downsides might be of keeping that flag enabled permanently

**Comment by louwers** [comment]
Nice to hear this fixes the problem.

https://github.com/maplibre/maplibre-native/issues/2522#issuecomment-2312846604
