### ISSUE TITLE
Android Documentation: Clarify using `MapLibreMapOptions`

### ISSUE THREAD

**Issue by louwers** [maplibre/maplibre-native#2526]
> In the documentation, I have been able to found that we can apply map options (https://maplibre.org/maplibre-native/android/api/-map-libre%20-native%20-android/org.maplibre.android.maps/-map-libre-map-options/index.html).
 
> From the documentation: Defines configuration MapLibreMapOptions for a MapLibreMap. These options can be used when adding a map to your application programmatically (as opposed to via XML). If you are using a MapFragment, you can pass these options in using the static factory method newInstance(MapLibreMapOptions). If you are using a MapView, you can pass these options in using the constructor MapView(Context, MapLibreMapOptions). If you add a map using XML, then you can apply these options using custom XML tags.

> Great, but without a few sample code (XML, programmatically, etc) this is not really usefull. If I want to use XML, is it another tag included in the tag <org.maplibre.android.maps.MapView ... /> or an attribute or something else? Because I'm a Kotlin/Android Platform beginner, I have no idea on how to add a map programmatically to an Activity! Moreover, I have not been able to found the factory method mentioned. We don't need a full app to show these cases, just a sample app using map options. Using XML declaration and code commented method to use the programmatic method. Of course, the same app can be used to demonstrate something more complicated! Like what comes next... ;-)

Suggestion from @lepigocher

Bounty direction: https://github.com/maplibre/maplibre/issues/191

**Comment by jDilshodbek** [comment]
I would like to work on this ticket

**Comment by jDilshodbek** [comment]
![2024-07-23 11 56 06](https://github.com/user-attachments/assets/1749e7aa-e836-4ccd-8777-bd6994395e25)

**Comment by jDilshodbek** [comment]
![2024-07-24 15 29 09](https://github.com/user-attachments/assets/dd85f496-3e6f-4788-933e-4ec3d5999935)

**Comment by louwers** [comment]
This bounty can be paid out.

**Comment by jDilshodbek** [comment]
invoice link : [https://opencollective.com/maplibre/expenses/213230](url)
