### ISSUE TITLE
Android Documentation: Using a GeoJSON source

### ISSUE THREAD

**Issue by louwers** [maplibre/maplibre-native#2527]
Suggestion from @lepigocher

The example should show how to work with GeoJSON sources and common usage patterns.

Bounty direction: https://github.com/maplibre/maplibre/issues/191

**Comment by jDilshodbek** [comment]
I want to work on this ticket

**Comment by louwers** [comment]
This bounty can be paid out.

**Comment by jDilshodbek** [comment]
Thanks. Invoice link: https://opencollective.com/maplibre/expenses/229718
