### ISSUE TITLE
 CameraPosition not found in Android SDK when devloping with using Java

### ISSUE THREAD

**Issue by cc-shifo** [maplibre/maplibre-native#2573]
**Describe the bug**
CameraPosition not found in Android SDK when devloping with using Java

**To Reproduce**
1. Go to org.maplibre.android.camera.CameraPosition;
2. Click on 'CameraPosition'
3. See CameraPosition.class

**Screenshots**
![CameraPosition_20240703095933](https://github.com/maplibre/maplibre-native/assets/9163362/4aa0f4e7-db8f-40d9-90b0-bf2f064e2efa)

**Comment by louwers** [comment]
Could you clarify your reproduction steps?

**Comment by westnordost** [comment]
This very much looks like an Android studio IDE issue. Try syncing the project with gradle files or otherwise invalidate caches and restart. Android Studio also has this "Repair IDE" option in the menu, not sure what it does.
