### ISSUE TITLE
attribution button action sheet links do not work

### ISSUE THREAD

**Issue by baubrey91** [maplibre/maplibre-native#2574]
**Describe the bug**
Links in attributionButton action sheet do not take users to webview link, they just dismiss the action sheet. 

**To Reproduce**
1. Go to mapview configured with a urlstyle json or hardcoded attribution style 
2. Click on attribution button on bottom right
3. Click on copyright link
4. User is not taken to website of copyrighted library

**Expected behavior**
User is taken to webview

|ScreenShot|
|--------|
|![Simulator Screenshot - iPhone 15 Pro - 2024-07-03 at 16 47 49](https://github.com/maplibre/maplibre-native/assets/5482416/1b0bba5d-4dc3-4a81-bbc8-0af0d249c69f)|

**Video**
https://github.com/maplibre/maplibre-native/assets/5482416/c74e3099-5a32-4f32-a278-2eaa6ae6f382

**Platform information (please complete the following information):**
 - OS: iOS
 - Platform: all iOS versions
 - Version 5.12+

**Additional context**
It looks like this issue started in 5.12 as a pr was made that removed the assignment of calling the webview in the callback when creating the action sheet. See [PR](https://github.com/maplibre/maplibre-native/commit/d62ff400c6f75750d71b563344b1ca1e07b9b576#diff-00a062c3870157cb87ebec8d21fc095026431d01902cac9e273e5def3875edbe) Additionally it looks like there was another pr that re-added the logic to show the text but not have the link action see [PR](https://github.com/maplibre/maplibre-native/issues/183)

**Comment by louwers** [comment]
Thanks a lot for the report. Is this something you would be comfortable fixing? A PR would be highly welcomed.

**Comment by baubrey91** [comment]
> Thanks a lot for the report. Is this something you would be comfortable fixing? A PR would be highly welcomed.
> 
> We're not updating the 5.x.x release series for iOS anymore, so I hope updating to 6.x.x (with Metal support) is an option for you.

PR made https://github.com/maplibre/maplibre-native/pull/2587

**Comment by louwers** [comment]
This will be included in the next version.
