### ISSUE TITLE
Road layers are misaligned in Vulkan mode

### ISSUE THREAD

**Issue by alasram** [maplibre/maplibre-native#2681]
**Describe the bug**
The road network is misplaced when rendered in Vulkan mode
Observed with mbgl-glfw on Linux

**Screenshots**
![misplaced_roadnetwork](https://github.com/user-attachments/assets/e0f68998-cd49-433c-9dbd-48965fe168e7)

**Platform information (please complete the following information):**
Ubuntu 22.04.4 LTS

**Comment by sjg-wdw** [comment]
@adrian-cojocaru were we able to figure this one out?

**Comment by adrian-cojocaru** [comment]
I never had a repro for it. It might have been fixed with the latest Android PR but I have no way to confirm it.

**Comment by alasram** [comment]
Issue not observed anymore on the latest main
