### ISSUE TITLE
Use Kotlin instead of Groovy for Android build configuration

### ISSUE THREAD

**Issue by louwers** [maplibre/maplibre-native#2699]
There is a migration guide here: https://developer.android.com/build/migrate-to-kotlin-dsl

Bounty possible (negotiable).

**Comment by shricastic** [comment]
hey, shall we discuss, if issue is still open.

**Comment by louwers** [comment]
@shricastic Please contact me on Slack if you want to work on this, but you need to be very familiar with Android build tooling.

**Comment by shricastic** [comment]
couldn't find your slack. but i hit up on LinkedIn.  I am recent CS grad and am trying to kick off some code in open source, am familiar with android, i will do my best to make contributions

**Comment by louwers** [comment]
Apologies for deleting your comment, the LinkedIn link on your profile is broken so I mistakenly thought you were not a real person.

I recommend trying to build an app with a map to get familiar with the library.  Our Slack is in the README, but LinkedIn works too.

**Comment by shricastic** [comment]
no issues Bart. sure ill try to connect on slack. Thanks!

**Comment by louwers** [comment]
This bounty can be paid out. Thanks for your contribution @kaushalbx!

If you want to work on another bounty, refer to the [step-by-step guide](https://maplibre.org/roadmap/step-by-step-bounties-guide/), note that you can suggest an issues as well.

**Comment by kaushalbx** [comment]
Thank you @louwers, sure I will keep looking for new issues to contribute to.

**Comment by kaushalbx** [comment]
Hi @louwers Here is the invoice link,
https://opencollective.com/maplibre/expenses/223914
