### ISSUE TITLE
macOS Metal Render Test Failures

### ISSUE THREAD

**Issue by louwers** [maplibre/maplibre-native#2741]
On macOS + Metal there are some render test failures.

After https://github.com/maplibre/maplibre-native/pull/2729 is merged you can run the render tests on macOS with:

```
cmake . -B build \
  -G Ninja \
  -DCMAKE_BUILD_TYPE=Debug \
  -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
  -DMLN_WITH_NODE=ON \
  -DMLN_WITH_OPENGL=OFF \
  -DMLN_WITH_METAL=ON \
  -DMLN_DRAWABLE_RENDERER=ON \
  -DMLN_LEGACY_RENDERER=OFF \
  -DMLN_DRAWABLE_RENDERER=ON \
  -DMLN_WITH_WERROR=OFF
cmake --build build --target mbgl-render-test-runner
 ./build/mbgl-render-test-runner --manifestPath metrics/macos-xcode11-release-style.json
```

See here for the current failures:

[macos-xcode11-release-style (1).html.zip](https://github.com/user-attachments/files/16698220/macos-xcode11-release-style.1.html.zip)

**Comment by sjg-wdw** [comment]
@alexcristici see if you can reproduce these.
