### ISSUE TITLE
Unused index buffers

### ISSUE THREAD

**Issue by alasram** [maplibre/maplibre-native#2760]
**Describe the bug**
I noticed that many index buffers are created when tiles are loaded but they are never used in an actual draw which means creating and uploading these buffers is a waste.
The reason for the creation of these buffers needs to be investigated and once the cause is understood we need to avoid creating these buffers.

**Comment by sjg-wdw** [comment]
Can you take a look at this one @alexcristici
First question would be how we tell these buffers are being created and then not used.

**Comment by alasram** [comment]
[This commit](https://github.com/alasram/maplibre-native-experimental/commit/f53653418933847f2031f906627121c7a7a2577d) prints to the log index buffers that aren't used in any draw
