### ISSUE TITLE
[Build Binary Android] - Error build my app with issue duplicate class (Execution failed for task ':app:checkDebugDuplicateClasses')

### ISSUE THREAD

**Issue by hmtriit** [maplibre/maplibre-native#278]
hi Master,
I have build binary maplibre-gl-native for android and add file (MapboxGLAndroidSDK-release.aar) in to project, 
I am trying to run my application a device but i keep getting this error, kindly help me with this error:
The error description is as follows:
FAILURE: Build failed with an exception.

What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
.....
Duplicate class com.mapbox.mapboxsdk.*** found in modules jetified-android-sdk-9.4.2-runtime (org.maplibre.gl:android-sdk:9.4.2) and jetified-mapbox-runtime (MapboxGLAndroidSDK-release.aar)
.......

Thanks

**Comment by Lbreid** [comment]
I ran into this also. I added android.enableJetifier=true and android.useAndroidX=true to gradle.properties which sorted all the errors.
