### ISSUE TITLE
Vulkan Early Access Testing (Android)

### ISSUE THREAD

**Issue by louwers** [maplibre/maplibre-native#2787]
<img src="https://github.com/user-attachments/assets/109b43b0-8b61-4980-9cd2-1b91d8dfad1e" width="50%">

---

We are looking for users interested in the upcoming Vulkan support for Android.

We will be releasing an 'early access' MapLibre Android version (a.k.a. pre-release) that will _just_ support Vulkan in **September 2024**. This will give people an opportunity to test the new Vulkan backend on Android. Joining this effort will help the rendering team to ensure there are no regressions as well as with optimizing performance.

Edit: the first [pre-release has been released](https://github.com/maplibre/maplibre-native/releases/tag/android-v11.3.0-vulkan-pre0)!

## Reporting Issues

When [reporting an issue](https://github.com/maplibre/maplibre-native/issues/new) (here or in a separate issue), the following are required:

- Style: If your style is public or can be made available, that will help a lot.
- Lat / Long / Zoom: Where exactly does the issue occur?
- Screenshot
- Android version
- MapLibre Native version
- Device

When available:

- Stack Trace / Vulkan Error / Core Dump
- Minimal style: Can you provide a minimal style that reproduces the issue?

**Comment by westnordost** [comment]
I could create some alpha releases alongside the stable ones for StreetComplete (once the MapLibre migration has been stabilized in the first place) for people to try out. 

Beyond detecting simple rendering issues, this only makes sense if there's a straightforward way _for these users_ to make useful reports for crashes in native / Vulkan code. I understand that the logged crash trace is not that useful for you and digging out the tombstone seems to require root privileges on the phone and/or usage of developer tools (adb), plus some special build configuration (we haven't fully figured out yet) beforehand.

Also, how would you sell it to users so they want to be the first people to try it out? Is there anything to gain from that?

**Comment by louwers** [comment]
> I could create some alpha releases alongside the stable ones for StreetComplete (once the MapLibre migration has been stabilized in the first place) for people to try out.

That would be amazing!

> Also, how would you sell it to users so they want to be the first people to try it out? Is there anything to gain from that?

Being an early tester and testing it with your style and app means that any bugs you report will have the attention of the rendering team, and will probably be fixed by the time we make an official release.

**Comment by mtpdog** [comment]
I can take part too to test in complex environment with many raster, vector and extruded layers.
Btw, the latest 2 version (11.1.0 and 11.2.0) have a regression with rendering vector layers. There are many distortions in label rendering. 11.0.2-pre0 is the latest stable version for now.

**Comment by louwers** [comment]
@mtpdog Please create a separate issue for the regressions you are seeing.

**Comment by mtpdog** [comment]
> @mtpdog Please create a separate issue for the regressions you are seeing.

Sure. It is already described here: https://github.com/maplibre/maplibre-native/issues/2788

**Comment by louwers** [comment]
Labels are jittery with this style.

![image](https://github.com/user-attachments/assets/c14312ee-3fcf-41ec-b3bf-df12315d3cf3)

Style -  https://tiles.versatiles.org/assets/styles/colorful.json
Lat / Long / Zoom -  Try London
Android version - 11
MapLibre Native version - android-v11.3.0-vulkan-pre0
Device - Samsung S10

**Comment by mtpdog** [comment]
According to my tests, this version (android-v11.3.0-vulkan-pre0) works mostly fine except for:
- It currently works not so great in terms of speed/micro-lags compared to OpenGL version
- There is an issue with some tiles not rendered until zoom-in / zoom-out action (probably this issue exists in OpenGL versions as well starting from 11.2.0):
![Screenshot_vulkan](https://github.com/user-attachments/assets/3430cf89-893b-40fb-bda9-5621d8e45e86)

On the positive side it seems that this issue is fixed: https://github.com/maplibre/maplibre-native/issues/2788

**Comment by louwers** [comment]
@mtpdog I think the issue you are seeing may be fixed by #2842

**Comment by louwers** [comment]
I ran some benchmarks on AWS Device Farm with various devices. The results can be found [here](https://docs.google.com/spreadsheets/d/1gIYlQziOMbnXvi7zPyc8h9g8ficq0lgYJHqvHVPX3ws/edit) and in the diagram below.

![image](https://github.com/user-attachments/assets/3260933c-fc85-45ac-a38d-29856b32d07e)

We are a bit suspicious that the Pixel 7 Pro is comparable to the Pixel 4a in terms of performance. The results look promising though.

**Comment by louwers** [comment]
We did a new run last week which moved slower from location to location. This is too prevent the situation where no data is loaded and the map is not rendering anything (resulting in very high but meaningless FPS in some runs). I think we can improve the benchmark by running it completely offline and starting the benchmark with a pre-loaded cache. 

I have made a PR with some scripts to automate running the benchmarks, as well as for collecting and plotting the results. https://github.com/maplibre/maplibre-native/pull/2991

The results of the last run:

[benchmark.csv](https://github.com/user-attachments/files/17693168/benchmark.csv)

Plot:

![image](https://github.com/user-attachments/assets/4ff47faa-2c5a-4786-bace-8df5ee560028)

**Comment by louwers** [comment]
We now have a new version up with the name `11.6.1-vulkan-pre0`. Please give it a spin!

We're very eager to know if your feedback, also if it just works. We can include your name in the official release post (if you want).

**Comment by westnordost** [comment]
Still reproducible with pre1.

Also, I get these error messages on each rotate (always):

```
2024-11-20 19:33:22.247 10509-10698 GraphicBufferAllocator  de.westnordost.streetcomplete.debug  E  Failed to allocate (4 x 4) layerCount 1 format 56 usage b00: 5
2024-11-20 19:33:22.247 10509-10698 AHardwareBuffer         de.westnordost.streetcomplete.debug  E  GraphicBuffer(w=4, h=4, lc=1) failed (Unknown error -5), handle=0x0
2024-11-20 19:33:22.247 10509-10698 GraphicBufferAllocator  de.westnordost.streetcomplete.debug  E  Failed to allocate (4 x 4) layerCount 1 format 56 usage b00: 5
2024-11-20 19:33:22.248 10509-10698 AHardwareBuffer         de.westnordost.streetcomplete.debug  E  GraphicBuffer(w=4, h=4, lc=1) failed (Unknown error -5), handle=0x0
2024-11-20 19:33:22.306 10509-10644 OpenGLRenderer          de.westnordost.streetcomplete.debug  E  Unable to match the desired swap behavior.
2024-11-20 19:33:22.309 10509-10698 GraphicBufferAllocator  de.westnordost.streetcomplete.debug  E  Failed to allocate (4 x 4) layerCount 1 format 56 usage b00: 5
2024-11-20 19:33:22.309 10509-10698 AHardwareBuffer         de.westnordost.streetcomplete.debug  E  GraphicBuffer(w=4, h=4, lc=1) failed (Unknown error -5), handle=0x0
2024-11-20 19:33:22.309 10509-10698 GraphicBufferAllocator  de.westnordost.streetcomplete.debug  E  Failed to allocate (4 x 4) layerCount 1 format 56 usage b00: 5
2024-11-20 19:33:22.309 10509-10698 AHardwareBuffer         de.westnordost.streetcomplete.debug  E  GraphicBuffer(w=4, h=4, lc=1) failed (Unknown error -5), handle=0x0
```

**Comment by mtpdog** [comment]
11.6.1-vulkan-pre1 works very well in our case! Now it definitely works faster than OpenGL. Great job!

P.S. Can we try to increase map tilt limits on this new engine? https://github.com/maplibre/maplibre-native/issues/1909

**Comment by louwers** [comment]
@mtpdog That has nothing to do with Vulkan.

**Comment by mtpdog** [comment]
The only small issue I've noticed so far with 11.6.1-vulkan-pre1 is that all vector elements (vector maps, annotations) do not "stick" firmly to the raster background on quick camera movements. They kind of floating around their normal position. Probably the vector part and raster parts of rendering are not synchronized perfectly. Would be great if this is fixed as well.

**Comment by mtpdog** [comment]
Another possible issue  (need further analysis). The vulkan map does not scale properly. Put it into a composable surface and try to change the bounds - the map content is not scaled.

**Comment by louwers** [comment]
@mtpdog Oh that sounds like something that needs fixing. Could you open separate issues for these problems, ideally with some screenshots to show the problem?

**Comment by sargunv** [comment]
Seeing some odd shaking with labels on pre1:

https://github.com/user-attachments/assets/9c185b4a-624c-4dbb-8b4f-613d87714a39

Also some white artifacts (noticeable in the water) when zooming in and out very quickly:

https://github.com/user-attachments/assets/8201d0a8-9b6e-4d40-b373-c35523203e50

Otherwise, looks good! This is with the OpenFreeMap "bright" style.

**Comment by ianthetechie** [comment]
Somewhat similar to the white artifact reported above, there seem to be some issues with the emulator. I've reproduced it with the MapLibre demo tiles:

![Image](https://github.com/user-attachments/assets/25be4936-b1c5-4893-b397-bf9ac30736c8)

To repro, check out the `maplibre-11` branch here: https://github.com/Rallista/maplibre-compose-playground/tree/maplibre-11. Then run the demo app. The Map Callback example is the most trivially reproducible, but most examples exhibit the behavior in the initial viewport; for others it will invariably show up with some zooming or panning and doesn't go away until you move the map.

**Comment by louwers** [comment]
@ianthetechie Did you mean to upload a video?

cc @adrian-cojocaru

**Comment by ianthetechie** [comment]
No, I just uploaded a screenshot on purpose, but I can upload a video too if it's helpful ;) (Yes, it's an ugly demo, but its sole function was to show how to manipulate the camera haha).

https://github.com/user-attachments/assets/327df7c1-d643-4b52-9e23-d78d50ea2d13

**Comment by louwers** [comment]
@ianthetechie Ahh I thought the two lines were part of the UI. Understood!

**Comment by louwers** [comment]
Thanks for testing everyone! Please open a new issue if you encounter any other problems.
