### ISSUE TITLE
Support fill-opacity-per-geometry for fill type layer

### ISSUE THREAD

**Issue by tongust** [maplibre/maplibre-native#281]
We are working on adding new paint property fill-opacity-per-geometry to fill type layer in the PR of maplibre-gl-js (https://github.com/maplibre/maplibre-gl-js/pull/1191). To make draw fill consistent, create this open issue to track it.

**Comment by wipfli** [comment]
#293

**Comment by louwers** [comment]
I am closing this since it was never merged. Feel free to re-open if it was merged into MapLibre GL JS.
