### ISSUE TITLE
Mapbox error Exception in onDidFinishRenderingMap {"level": "error", "message": "Exception in onDidFinishRenderingMap", "tag": "Mbgl-MapChangeReceiver"}

### ISSUE THREAD

**Issue by BubbleTrouble14** [maplibre/maplibre-native#283]
I just created a clean new react native app running react-native 0.68.2 and each time I open the map I get "Mapbox error Exception in onDidFinishRenderingMap {"level": "error", "message": "Exception in onDidFinishRenderingMap", "tag": "Mbgl-MapChangeReceiver"}" its also a little a random as on my pc emulator it will sometimes not occur. I switched to Maps SDK v10 to see if it has the same issue. But this was not the case as it didn't crash at all.

**Comment by BubbleTrouble14** [comment]
Even the example project on rnmapbox/maps crashes when setting the RNMapboxMapsImpl = "maplibre" in the build.gradle. Note the issue is probably only for android, haven't tried ios yet.

**Comment by karimelsaidy** [comment]
i face the same problem !!

**Comment by goodryanboy** [comment]
Also facing the same problem

**Comment by goodryanboy** [comment]
Current work around is to comment out the code onDidFinishRenderingMap

### node_modules/@rnmapbox/maps/android/rctmgl/src/main/java-mapboxgl/common/com/mapbox/rctmgl/components/mapview/RCTMGLMapView.java

```
@Override
    public void onDidFinishRenderingMap(boolean fully) {
        // if (fully) {
        //     for (Pair<Integer, ReadableArray> preRenderMethod : mPreRenderMethods) {
        //         Integer methodID = preRenderMethod.first;
        //         ReadableArray args = preRenderMethod.second;
        //         mManager.receiveCommand(this, methodID, args);
        //     }
        //     mPreRenderMethods.clear();
        //     handleMapChangedEvent(EventTypes.DID_FINISH_RENDERING_MAP_FULLY);
        // } else {
        //     // handleMapChangedEvent(EventTypes.DID_FINISH_RENDERING_MAP);
        // }
    }
```

**Comment by BubbleTrouble14** [comment]
Okay great thx. Atm I am just using mapbox instead of maplibre.

**Comment by ahmedyasin21** [comment]
I'm facing the same issue

**Comment by guidoabelleira** [comment]
Also facing the same problem

**Comment by mmarganski** [comment]
There is a type casting error.
In the `node_modules/@rnmapbox/maps/android/rctmgl/src/main/java-mapboxgl/common/com/mapbox/rctmgl/components/mapview/RCTMGLMapViewManager.java` file in the body of `receiveCommand` function should be used `args.getArray(i).getString()` instead of `args.getString(i)`

**Comment by joshua-smith4** [comment]
Same issue

**Comment by wipfli** [comment]
The project react native project seems to have had a discussion about its future in https://github.com/rnmapbox/maps/discussions/1680 and the community was asked if the focus should be on supporting Mapbox v10 or MapLibre or both. 

I did not understand the conclusion but if you feel like you depend on a react native wrapper for MapLibre then it might make sense to coordinate your efforts and have a discussion probably under this thread: https://github.com/rnmapbox/maps/discussions/1680#discussioncomment-1883127

**Comment by rayansys** [comment]
Same issue

**Comment by mawrukh** [comment]
Did anyone resolve this?

**Comment by louwers** [comment]
Please open this issue in the React Native repo.

If it can be reproduced with only the Objective-C library, feel free to open an issue here.
