### ISSUE TITLE
hillshade rendering artifacts, regression in iOS 6.6.0

### ISSUE THREAD

**Issue by JesseCrocker** [maplibre/maplibre-native#2838]
**Describe the bug**
The iOS 6.6.0 release seems to have introduced a bug related to hillshade rendering, while the map is moving there are sometimes lots of flashing, and line artifacts. But once all data is loaded, it renders correctly. There are several examples of this happening in the attached video. This was not happening in 6.5.4

**Expected behavior**

**Screenshots**

https://github.com/user-attachments/assets/99ebc3e8-5f53-43ee-a72c-d7addb229ce1

**Platform information (please complete the following information):**
 - OS: iOS 17.x
 - Platform iOS
 - Version 6.6.0

**Comment by louwers** [comment]
Also happens with MapTiler Outdoors.

**Comment by louwers** [comment]
I did a `git bisect`, seems like https://github.com/maplibre/maplibre-native/pull/2629 started to introduce issues with hillshading. @TimSylvester could you have a look at this?
