### ISSUE TITLE
User Puck getting displaced after panning/swiping on map

### ISSUE THREAD

**Issue by vijaykharage7** [maplibre/maplibre-native#2847]
Upon panning or swiping the map while in navigation mode, the user puck gets displaced from it's original position along with the map.

**Steps to reproduce**
1. Launch navigation
2. Pan/swipe the map up/down/sideways
3. see the behaviour of user puck

**Expected behavior**
The user puck should be on the user location no matter panning/swiping of the map.

**Screenshots**
<img width="295" alt="Screenshot 2024-09-18 at 3 53 46 PM" src="https://github.com/user-attachments/assets/cd4b3b1c-2733-465e-96e4-1e110c3645ba">

**Video**
https://github.com/user-attachments/assets/0810a88d-d27a-48a3-abe8-08a492f29eb2

**Platform information (please complete the following information):**
 - OS: iOS 17.5
 - Platform: iOS
 - SDK Version: 6.5.0

**Additional context**
Tried upgrading the SDK version to latest one, still facing the same issue.

**Comment by louwers** [comment]
Are you using https://github.com/maplibre/maplibre-navigation-ios ?

**Comment by vijaykharage7** [comment]
Yes @louwers

**Comment by vijaykharage7** [comment]
@louwers We are using our own SDK solution based on MapLibre Native version 6.5.0

**Comment by louwers** [comment]
OK, can you be more specific what 'launch navigation' means?

**Comment by vijaykharage7** [comment]
Hello @louwers, Thank you so much for helping me in this issue.

Launch Navigation: User started the turn by turn navigation. User puck traverse over the user's desired path. But while the map is being moved by swiping/panning, the user puck position gets moved as the map moves, and gets restored after user location gets updated.

**Comment by louwers** [comment]
This library does not implement turn-by-turn navigation.

Could you provide sample code that reproduces the issue?

**Comment by vijaykharage7** [comment]
@louwers, Our custom SDK solution helps to provide turn-by-turn navigation.

We were previously using [MapLibre 5.12.1](https://github.com/maplibre/maplibre-native/releases/tag/ios-v5.12.1) and everything was working fine. We recently updated the MapLibre to [6.5.0](https://github.com/maplibre/maplibre-native/releases/tag/ios-v6.5.0) as it now supports Metal for rendering. Since then we are facing this behaviour.
Hope this information is useful

**Comment by louwers** [comment]
> Hope this information is useful

@vijaykharage7  Unfortunately it is not.

In order for us to diagnose the problem, we need to be able to recreate it in our own development setup.

**Comment by vijaykharage7** [comment]
I have resolved this issue by adjusting center of the user puck in MLNMapViewDelegate method
`mapView(_ mapView: MLNMapView, regionIsChangingWith reason: MLNCameraChangeReason)`

Thanks for your kind attention so far on this issue @louwers! It means a lot!!

**Comment by louwers** [comment]
Thanks for sharing your solution, that may help someone else facing this problem.
