### ISSUE TITLE
An option to directly show all items on a map instead of having cluster items

### ISSUE THREAD

**Issue by prototyperspective** [maplibre/maplibre-native#2864]
**Is your feature request related to a problem? Please describe.**
MapLibre is used for the Wikipedia app's restored Nearby places features by which one can view nearby places that have Wikipedia articles with coordinates. One of the two main problems with it that currently still makes this barely usable in practice (like when using it to explore a place/city new to you on the go) is that it can't be made to show all article items directly on the map and instead combines them into clusters that one has to tap to see the individual items.

**Describe the solution you'd like**
A way to have all dots directly displayed on the map at their locations at whatever current zoom one is at. This seems to be an issue with MapLibre, not the Wikipedia app for which I filed an issue [here](https://phabricator.wikimedia.org/T360213).

**Describe alternatives you've considered**
If there's too many dots next to each other the user could still reenable to cluster view or zoom in further. This could be done in the preferences and/or a small toggle button somewhere on the map (or in the context menu of the config button in a corner). There could also be a next and previous button that goes through all the items on the map so you don't have to tap items close to each other.

**Additional context**
Having these cluster dots instead of lots of dots prevents just moving around the map and quickly looking up many items one after another or quickly moving to another location in the map and back. I don't think most people use maps on the smartphone at home in advance with lots of time instead of on the go to for example find some interesting place among many dots nearby or see where to go next with public transport. Having this cluster view (especially if one can't filter items which is the other main problem) makes this nearly impossible as one constantly has to change zoomlevel making it hard to navigate around or quickly go through many items and so on.

Other apps can also show dots directly or similar, for example the Tripadvisor app shows many individual items as long as one is zoomed in close enough.

In the video below you can see the clusters that I mean at time 0:42. This requested feature is a way to have the dots-directly-on-the-map view as shown at 0:39 in the video (from [here](https://commons.wikimedia.org/wiki/File:Places_Android_Feature.webm)) at whatever zoomlevel one is at without having to select any dots (even if that means lots of dots right next to each other where one could simply zoom in).
[Places_Android_Feature.webm](https://github.com/user-attachments/assets/021d24da-961d-4962-8c2c-1dbf06b09b3b)

**Comment by westnordost** [comment]
> A way to have all dots directly displayed on the map at their locations at whatever current zoom one is at. This seems to be an issue with MapLibre, not the Wikipedia app for which I filed an issue [here](https://phabricator.wikimedia.org/T360213).

This assumption is not correct, clustering is an optional feature, you don't need to use clustering at all. I.e., it is already possible to show all dots at once, regardless of the current zoom. It is also possible to for example only have clusters appear on certain zoom levels.

Closing as "already implemented".

**Comment by prototyperspective** [comment]
Thanks for this info! It wasn't assumption as I said it seems like that is the case partly because I could not find anything suggesting to the contrary and there was no reply at the wikimedia phabricator issue. I will relay this info to linked issue. A link on how to e.g. only have clusters appear on certain zoom levels would be helpful.

**Comment by westnordost** [comment]
There's some documentation on source layer properties here: https://maplibre.org/maplibre-style-spec/sources/#clusterMaxZoom

**Comment by prototyperspective** [comment]
> Max zoom on which to cluster points if clustering is enabled.

I could not find any info where clustering can be disabled. Something seems to be missing in the docs.

**Comment by westnordost** [comment]
It's not missing. https://maplibre.org/maplibre-style-spec/sources/#cluster
