### ISSUE TITLE
Android: Location puck switch icon on rotating camera

### ISSUE THREAD

**Issue by Fabi755** [maplibre/maplibre-native#2879]
**Describe the bug**
We have a really strange behavior of the location icon. And I am at the end of my ideas.

I'm currently working on upgrading the MapLibre navigation to v11. After upgrade (from v11.0.2-pre0) to v11.1.0 (and above) the location puck gets flickering by rotating. After more research we found out that the icon goes to the `maplibre_user_stroke_icon` drawable. The puck is going back to the right drawable, when zoom in/out, or update the location.

The `maplibre_user_stroke_icon` is used by two styles (`maplibre_backgroundDrawable` & `maplibre_backgroundDrawableStale`). Changing the styles has no effect to displayed icon in my tests.

I can't see this issue on the sample app (build from source). But I see this issue also in a new project from scratch. I can't see this issue on my Emulator running on a Mac.

**To Reproduce**

1. Clone [my sample repository](https://github.com/Fabi755/maplibre-puck-issue/tree/main)
2. Run app on a real device
3. Allow using location, to make things work
4. Rotate map
5. Puck is flickering between GPS puck and red dot (`maplibre_user_stroke_icon`)

(Use the enable/disable) button to see the stroke-icon state, without location updates. If disabled, only zoom in/out goes back to the GPS puck.

**Expected behavior**
Icon should not changed to the stroke icon, and the GPS puck should always showed.

**Screenshots**

https://github.com/user-attachments/assets/0c5f889e-e8fd-4f68-87b1-6079ec1fb8b3

**Platform information (please complete the following information):**
- OS: Android
- Platform: Android
- Version: MapLibre 11.1.0 - 11.5.0

**Additional context**

**Comment by alasram** [comment]
I'm having the exact same problem but it's only reported in 11.5. (11.1 seems to not have this issue)

**Comment by alasram** [comment]
The VAO of the Drawable is changing which means we're running vertex input commands outside the drawable that are affecting the bound VAO.
A solution is to unbind the VAO after drawing but a correct solution would ensure we never run commands that affect VAO outside a Drawable object.
This code works for me:
https://github.com/alasram/maplibre-native-experimental/commit/473fdfa784f73e337c9b7edee93bc95eb3815237

**Comment by louwers** [comment]
@alasram Could you make a PR?

**Comment by alasram** [comment]
@boldtrn @Fabi755 Can you confirm the issue is fixed in Android v11.6.1? We can then close the issue

**Comment by boldtrn** [comment]
I could not repro the issue with 11.6.1. Let's wait for confirmation of @Fabi755 as well.

**Comment by Fabi755** [comment]
Is fixed. Works well with `11.6.1`. Thank you!! 💙
