### ISSUE TITLE
Upgrading Android SDK > 11.1.0 not possible

### ISSUE THREAD

**Issue by nijs9** [maplibre/maplibre-native#2903]
**Describe the bug**
When upgrading the Android MapLibre SDK from 11.1.0 to a higher version (11.2.0 or above), I keep encountering the following build error:

ERROR:/Users/nmp/.gradle/caches/transforms-3/71ce20248901683ffb4c858fd7efd1a9/transformed/fragment-1.8.2-runtime.jar: D8: java.lang.NullPointerException: Cannot invoke "String.length()" because "<parameter1>" is null

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeExtDexBikeDebug'.
> Could not resolve all files for configuration ':app:bikeDebugRuntimeClasspath'.
   > Failed to transform fragment-1.8.2.aar (androidx.fragment:fragment:1.8.2) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=21, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for DexingWithClasspathTransform: /Users/nmp/.gradle/caches/transforms-3/71ce20248901683ffb4c858fd7efd1a9/transformed/fragment-1.8.2-runtime.jar.
         > Error while dexing.

**To Reproduce**
1. Create Android app with MapLibre 11.1.0
2. Upgrade tot 11.2.0 or higher
3. Build

**Expected behavior**
I can use version 11.2.0 or higher

**Platform information (please complete the following information):**
 - OS: Android
 - Platform Android
 - Version 13

**Comment by westnordost** [comment]
This might be a caching issue in gradle. Did you try `gradle clean` and/or in Android Studio Menu -> Invalidate Caches?

**Comment by nijs9** [comment]
> > ERROR:/Users/nmp/.gradle/caches/transforms-3/71ce20248901683ffb4c858fd7efd1a9/transformed/fragment-1.8.2-runtime.jar: D8: java.lang.NullPointerException: Cannot invoke "String.length()" because "" is null
> 
> This might be a caching issue in gradle. Did you try `gradle clean` and/or in Android Studio Menu -> Invalidate Caches?

Yes, I tried all of this. Error is coming back again after gradle clean or invalidating caches.

**Comment by nijs9** [comment]
@westnordost Thank you. I've created a fresh project en the error is gone now...
