### ISSUE TITLE
Performance Metric Run

### ISSUE THREAD

**Issue by sjg-wdw** [maplibre/maplibre-native#2914]
I'd like to get a new run of the performance metrics.  Would be good to have one soon and then another one after @adrian-cojocaru's next set of performance changes.

Would like to include the following variants:
- Legacy OpenGL (@alexcristici which branch is this?)
- Current OpenGL Drawable
- Current Vulkan Drawable

I'd like to get a dozen devices.  Let's try to distribute more or less evenly over time.  How about 6 before 2020 and 6 after?
The idea of running on everything is good.  We can see what succeeds and then pick our devices from that.  In that case, I'd probably distribute over vendors as much as we could as well.

The other part of this is I'd like someone to run flat out on a modern Android device and calculate a frame rate using the simplest formula possible:  Frames / Time
Let's make sure it's one of the devices we have on the device farm too.  Then we compare those numbers to make sure they're plausible.

**Comment by alexcristici** [comment]
Branch for Legacy OpenGL tests: https://github.com/maplibre/maplibre-native/tree/android-benchmark-14dec

**Comment by sjg-wdw** [comment]
How does that measure, though?
I want to get a measurement with a different path that does not use the same low level measurements we have in place. Just something that divides time by frames.

**Comment by alexcristici** [comment]
Yes, it uses different path, activates standard rendering: encoding in parallel with rendering.

**Comment by sjg-wdw** [comment]
Got 'em. Thanks!
