### ISSUE TITLE
Update MapLibre GL JS Shaders after the TypeScript Migration

### ISSUE THREAD

**Issue by wipfli** [maplibre/maplibre-native#293]
MapLibre GL Native is using the shaders from MapLibre GL JS before the TypeScript migration. I am worried about changing the shaders in GL JS if we cannot test the consequences in native.

@birkskyum created a branch to use the shaders after the TypeScript migration: https://github.com/maplibre/maplibre-gl-native/tree/generate-shaders-using-typescript

Since we forked GL JS, there have been only a hand full of updates to the shaders, see https://github.com/maplibre/maplibre-gl-js/commits/main/src/shaders for a complete list. Notable changes were:

* https://github.com/maplibre/maplibre-gl-js/pull/209
* https://github.com/maplibre/maplibre-gl-js/pull/416
* https://github.com/maplibre/maplibre-gl-js/pull/928
* https://github.com/maplibre/maplibre-gl-js/pull/1022

**Comment by wipfli** [comment]
@louwers should this be closed?

**Comment by louwers** [comment]
@wipfli Yes we have copied them over and they are being refactored to take advantage of OpenGL ES 3.0.

I think WebGL 2 has some of the same functionality of OpenGL ES 3.0, but GL JS does not use WebGL 2 yet. In any case, keeping them in sync will need to happen manually going forward.

**Comment by birkskyum** [comment]
@louwers , it could very soon allow for some webgl2 though, so I have a hope that we might be able to copy some of these changes to the shaders back to GL JS.

https://github.com/maplibre/maplibre-gl-js/pull/2497
https://github.com/maplibre/maplibre-gl-js/pull/1891
