### ISSUE TITLE
Dependency license tracking with FOSSA

### ISSUE THREAD

**Issue by wipfli** [maplibre/maplibre-native#296]
I saw that the iOS platform has some dependency license tracking using FOSSA. At least the README says:

>The licenses of its dependencies are tracked via [FOSSA](https://app.fossa.io/projects/git%2Bhttps%3A%2F%2Fgithub.com%2Fmapbox%2Fmapbox-gl-native):

>[![FOSSA Status](https://app.fossa.io/api/projects/git%2Bhttps%3A%2F%2Fgithub.com%2Fmapbox%2Fmapbox-gl-native.svg?type=large)](https://app.fossa.io/projects/git%2Bhttps%3A%2F%2Fgithub.com%2Fmapbox%2Fmapbox-gl-native)

Should we implement something like that again?

**Comment by wipfli** [comment]
We might get enough with the free tier at https://fossa.com/pricing

**Comment by wipfli** [comment]
The number of licenses in Native is a bit confusing for me:

```
./platform/android/LICENSE.md
./platform/android/vendor/maplibre-java/LICENSE
./platform/android/vendor/mapbox-gestures-android/LICENSE.md
./platform/ios/LICENSE.md
./LICENSE.md
./LICENSE.mbgl-core.md
```

**Comment by louwers** [comment]
Maximum of 100 contributors (free tier) seems limiting.

I updated the license files manually in https://github.com/maplibre/maplibre-native/pull/2491
