### ISSUE TITLE
Windows CMake VS build fails in vendor/icu 

### ISSUE THREAD

**Issue by clinthidinger** [maplibre/maplibre-native#2961]
**Describe the bug**
Windows CMake build with Visual Studio fails with unresolved external symbol errors for UnicodeString:

```
`Building Custom Rule C:/Users/xxx/Documents/code/maplibre-native/CMakeLists.txt
mbgl-vendor-icu.lib(uinvchar.obj) : error LNK2019: unresolved external symbol "__declspec(dllimport) public: int __cdecl icu_61::UnicodeString::length(void)const " (__imp_?l
ength@UnicodeString@icu_61@@QEBAHXZ) referenced in function uprv_isInvariantUnicodeString [C:\Users\xxx\maplibre-native\
build\bin\mbgl-cache.vcxproj]
mbgl-vendor-icu.lib(uinvchar.obj) : error LNK2019: unresolved external symbol "__declspec(dllimport) public: char16_t const * __cdecl icu_61::UnicodeString::getBuffer(void)c
onst " (__imp_?getBuffer@UnicodeString@icu_61@@QEBAPEB_SXZ) referenced in function uprv_isInvariantUnicodeString [C:\Users\xxx\maplibre-native\build\bin\mbgl-cache.vcxproj]
C:\Users\xxx\Documents\code\maplibre-native\build\bin\Release\mbgl-cache.exe : fatal error LNK1120: 2 unresolved externals [C:\Users\xxx\Documents\code\maplibre-native\build\bin\mbgl-cache.vcxproj]`
```

**To Reproduce**
1. Run Cmake on windows for the project
2. cmake --build . --config Release 

**Expected behavior**
A successful build.

**Explanation**
UnicodeString::length() is defined here: https://github.com/maplibre/maplibre-native/blob/main/vendor/icu/include/unicode/unistr.h#L3906

unistr.h is being included in univchar.h here: https://github.com/maplibre/maplibre-native/blob/main/vendor/icu/src/uinvchar.h#L27

I have not looked into a proper fix.

I hacked the problem by commenting out uprv_isInvariantUnicodeString() in maplibre-native/vendor/icu/src/uinvchar.h since it is not used.  It successfully built after I did that.

**Platform information (please complete the following information):**
 - OS: Windows 11 Win64
 - Platform GLFW
 - Version c098a12c37c39fe39dea7ab25016a1bfd77c6969

MBGL_USE_BUILTIN_ICU was not explicitly set.

**Comment by louwers** [comment]
Maybe @tdcosta100 knows how to resolve this

**Comment by tdcosta100** [comment]
I need to check the `vcpkg` repository. I updated it some days ago, but it was reversed by someone by mistake. Could you go to `vcpkg` directory:

```
cd platform\windows\vendor\vcpkg
```

And then do the commands:

```
git fetch --all
git checkout 2024.09.30
```

Then try to build again. If it works, the problem is the `vcpkg` version.

**Comment by clinthidinger** [comment]
MINGW64 ~/Documents/code/maplibre_test/maplibre-native/platform/windows/vendor/vcpkg (main)
$ git checkout 2024.09.30
error: pathspec '2024.09.30' did not match any file(s) known to git


I did the fetch.  Am I missing a step?

**Comment by acalcutt** [comment]
did you run the 'git fetch'  command first?

**Comment by tdcosta100** [comment]
No, my instruction was wrong, sorry. Please try again with this:

```
git checkout tags/2024.09.30
```

**Comment by louwers** [comment]
Should be fixed now: https://github.com/maplibre/maplibre-native/pull/2966

**Comment by tdcosta100** [comment]
Thanks!

**Comment by clinthidinger** [comment]
I'm using CMake and Visual Studio:

cmake \
    -DCURL_INCLUDE_DIR="$WIN_LIB_DIR/curl/install/include" \
    -DCURL_LIBRARY="$WIN_LIB_DIR/curl/install/lib/libcurl.lib;Wldap32.lib" \
    -Ddlfcn-win32_DIR="$WIN_LIB_DIR/dlfcn-win32/install/share/dlfcn-win32" \
    -DDLFCN_INCLUDE_DIRS"=$WIN_LIB_DIR/dlfcn-win32/install/include" \
    -DJPEG_LIBRARY="$WIN_LIB_DIR/libjpeg/install/lib/libjpeg_a.lib" \
    -DJPEG_INCLUDE_DIR="$WIN_LIB_DIR/libjpeg/install/include"  \
    -Dlibuv_DIR="$WIN_LIB_DIR/libuv/install/lib/cmake/libuv" \
    -DLIBUV_INCLUDE_DIRS="$WIN_LIB_DIR/libuv/install/include" \
    -DZLIB_LIBRARY="$WIN_LIB_DIR/zlib/build/Release/zlibstatic.lib" \
    -DZLIB_INCLUDE_DIR="$WIN_LIB_DIR/zlib" \
    -DPNG_LIBRARY="$WIN_LIB_DIR/libpng/install_dir/lib/libpng16_static.lib" \
    -DPNG_PNG_INCLUDE_DIR="$WIN_LIB_DIR/libpng/install_dir/include" \
    -DWebP_DIR="$WIN_LIB_DIR/libwebp/install/share/WebP/cmake" \
    -Dglfw3_DIR="$WIN_LIB_DIR/glfw/install/lib/cmake/glfw3"  \
    ..
cmake --build . --config Release --parallel $PARALLEL_LEVEL

**Comment by tdcosta100** [comment]
Okay, but why are you using all these switches? Are using cmd/PowerShell, or another shell?

**Comment by tdcosta100** [comment]
Okay, this explains the errors. You have to resolve your dependencies manually, since in the original build the dependencies are all resolved using the vcpkg builds. You have to fix your ICU library build, unless you are building it with vcpkg. But I'm curious, why are you building the libraries externally?

**Comment by clinthidinger** [comment]
I was hoping for a CMake-only build process after I updated the submodules.

**Comment by tdcosta100** [comment]
Okay, I understand. Maybe you should take a look in the [vcpkg's ICU build process](https://github.com/microsoft/vcpkg/tree/master/ports/icu), so you can track what are you missing.

**Comment by clinthidinger** [comment]
Thanks!
