### ISSUE TITLE
Change HttpRequestImpl client to Call.Factory

### ISSUE THREAD

**Issue by yschimke** [maplibre/maplibre-native#2986]
OkHttpClient is a concrete instance of Call.Factory (https://square.github.io/okhttp/3.x/okhttp/okhttp3/Call.Factory.html)

This is typically the right API for SDKs to require as it allows more flexibility in call creation such as

- Switching to a non OkHttp implementation (https://github.com/google/cronet-transport-for-okhttp)
- Switching between different clients
- adding logging tracing before call creation

As an example, see the coil image loader https://github.com/coil-kt/coil/blob/0582d7587e946c1d19340aee15227bf6aefc7770/coil-network-okhttp/src/commonMain/kotlin/coil3/network/okhttp/OkHttpNetworkFetcher.kt#L21

But in maplibre it's specifically OkHttpClient at

https://github.com/maplibre/maplibre-native/blob/b58c0c24cc311225770618158a8f6ab16edd7b4d/platform/android/MapLibreAndroid/src/main/java/org/maplibre/android/module/http/HttpRequestImpl.java#L108

**Comment by louwers** [comment]
Note: another way to override HTTP request behavior is using the module provider added as part of https://github.com/maplibre/maplibre-native/pull/2231 You can them provide your own [HttpRequestIml](https://github.com/maplibre/maplibre-native/blob/main/platform/android/MapLibreAndroid/src/main/java/org/maplibre/android/module/http/HttpRequestImpl.java).
