### ISSUE TITLE
MLNMapViewDelegate on 6.8.0 doesn't work

### ISSUE THREAD

**Issue by seraph3b** [maplibre/maplibre-native#2993]
**Describe the bug**

on 6.8.0 mapViewWillStartLoadingMap, mapViewDidFinishRenderingMap and mapView(_ mapView: MLNMapView, didFinishLoading style: MLNStyle) did not be fired even map appears (guess also mapViewDidFailLoadingMap and so on don't work)

**To Reproduce**
After loaded a style, map appears but app get stucked waiting for didfinishrenderingmap to continue 

**Expected behavior**
delegate fired

**Platform information (please complete the following information):**
 - OS: ios 18.1
 - iOS
 - map libre 6.8.0

**Comment by louwers** [comment]
Please provide a minimal reproduction.

**Comment by louwers** [comment]
I tried to reproduce this, but I was unable.

**Comment by seraph3b** [comment]
we have 5 different maps and this issue happens with every maps.
only "func mapView(_ mapView: MLNMapView, didFinishLoading style: MLNStyle) {" is fired (tryed on simulator and phisical devices with ios 18+ or ios 15+)

currently using xcode 16.1, swift package manager -> maplibre 6.8.0 

with 6.7.1 it works as expected after setting style (self.mapView.styleURL = URL(string:"our map url")), map is loaded and fired:
- func mapView(_ mapView: MLNMapView, didFinishLoading style: MLNStyle) {
- func mapViewDidFinishRenderingMap(_ mapView: MLNMapView, fullyRendered: Bool) {

**Comment by louwers** [comment]
Thanks.

I'm investigating the issue.

**Comment by louwers** [comment]
I added these delegate methods to the AnimatedLineExample.swift and used AWS Open Data Standard Light and they fired as expected.

Could you share your style (can be private on Slack) so I can give it a try?

**Comment by seraph3b** [comment]
here you are @louwers  https://tiler.3bmeteo.com/api/maps/bright_v2/style.json

**Comment by seraph3b** [comment]
on viewdidload:
self.mapView.styleURL = URL(string:"https://tiler.3bmeteo.com/api/maps/bright_v2/style.json")
 self.mapView.clearsContextBeforeDrawing = true
            self.mapView.maximumZoomLevel = maximumZoomLevel
            self.mapView.minimumZoomLevel = minimumZoomLevel
            
            // se CurrentRadar == swiss_radar limita al nord!
            let sw = CLLocationCoordinate2D(latitude: 35.07638, longitude: 6.402696)
            let ne = CLLocationCoordinate2D(latitude: 47.10169, longitude: 18.5499)
            self.bounds = MLNCoordinateBounds(sw: sw, ne: ne)

            self.mapView.cameraThatFitsCoordinateBounds(self.bounds, edgePadding: UIEdgeInsets(top: 20.0, left: 20.0, bottom: 20.0, right: 20.0))
            
            self.mapView.delegate = self
// other stuff not related to maps

then I wait for
func mapView(_ mapView: MLNMapView, didFinishLoading style: MLNStyle) {
and
func mapViewDidFinishRenderingMap(_ mapView: MLNMapView, fullyRendered: Bool) {

**Comment by louwers** [comment]
Could you try passing the style to MLNMapView to see if that makes a difference?

```
        mapView = MLNMapView(frame: view.bounds, styleURL: URL(string: "https://tiler.3bmeteo.com/api/maps/bright_v2/style.json"))
```

**Comment by seraph3b** [comment]
I have a mapView object inside a xib, so self.mapView is a weak outlet to that, I can't set as you suggested

**Comment by seraph3b** [comment]
It's not an option even I change a lot of code because I need to change style at runtime

**Comment by seraph3b** [comment]
maybe it's something useful, I set style inside this:
  MLNOfflineStorage.shared.setMaximumAmbientCacheSize(102400) { error in
// style set here
}

**Comment by louwers** [comment]
Please try if 6.8.1 fixes the problem.

**Comment by louwers** [comment]
Reported as fixed, please share if anyone still experiences problems.

**Comment by seraph3b** [comment]
6.8.1 it's ok, thanks for your support
