### ISSUE TITLE
MapLibre crashes on Android 15 page size 16 from version 11.5.2 and above

### ISSUE THREAD

**Issue by IkeaOlof** [maplibre/maplibre-native#2995]
**Describe the bug**
When running maplibre on Android 15 with page size 16 it crashes.
It works for version 11.5.0 and 11.5.1, but I can see that you changed "Use Kotlin instead of Groovy for Android build configuration" in 11.5.2 which might be the reason for why it doesn't work anymore on that version and above.

**To Reproduce**
1. Use an emulator with android 15 page size 16.
2. Open maplibre
3. Crash happens.

**Expected behavior**
The maplibre should work as expected for version 11.5.2 and above on Android 15 with page size 16.

**Platform information (please complete the following information):**
 - OS: Android 15, page size 16
 - Platform Android
 - Version 15 (API 35) with page size 16

**Comment by louwers** [comment]
Oof thanks for the report, I'll look into this.

**Comment by louwers** [comment]
The issues is that the NDK version is not set to 27 anymore so it uses an older version from the environment.

I will push a fix and release a new version today.

**Comment by IkeaOlof** [comment]
> The issues is that the NDK version is not set to 27 anymore so it uses an older version from the environment.
> 
> I will push a fix and release a new version today.

Awesome, thanks for quick investigation and fix 💪

**Comment by louwers** [comment]
@IkeaOlof [11.6.1](https://github.com/maplibre/maplibre-native/releases/tag/android-v11.6.1
) is out which should fix this.

Please let me know if it solves the issue!

Also we're interested to know who is using MapLibre Native. Feel free to drop a comment [here](https://github.com/maplibre/maplibre-native/discussions/690).

**Comment by IkeaOlof** [comment]
> @IkeaOlof [11.6.1](https://github.com/maplibre/maplibre-native/releases/tag/android-v11.6.1) is out which should fix this.
> 
> Please let me know if it solves the issue!
> 
> Also we're interested to know who is using MapLibre Native. Feel free to drop a comment [here](https://github.com/maplibre/maplibre-native/discussions/690).

@louwers It seems to work like a charm. Thanks :)
