### ISSUE TITLE
In Windows 11, build error when i run ```cmake . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release```

### ISSUE THREAD

**Issue by WuMianzhi** [maplibre/maplibre-native#3008]
**Describe the bug**
When i trying to build the version of windows, shows below error 
```
D:\Project\rio-map\maplibre-native\platform\windows\Get-VendorPackages.ps1 : 缺少参数
“Triplet”的某个参数。请指定一个类型为“System.String”的参数，然后再试一次。
    + CategoryInfo          : InvalidArgument: (:) [Get-VendorPackages.ps1]，ParentCon 
    tainsErrorRecordException
    + FullyQualifiedErrorId : MissingArgument,Get-VendorPackages.ps1

CMake Error at C:/Program Files/CMake/share/cmake-3.29/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find CURL (missing: CURL_LIBRARY CURL_INCLUDE_DIR)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.29/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.29/Modules/FindCURL.cmake:196 (find_package_handle_standard_args)
  platform/windows/windows.cmake:22 (find_package)
  CMakeLists.txt:1570 (include)


-- Configuring incomplete, errors occurred! 
```

Just follow the step in [document](https://github.com/maplibre/maplibre-native/tree/main/platform/windows)

**Comment by File5** [comment]
I've got the same error for cmake 3.31 configuring for VS 2022, Windows 11. Doesn't seem to be connected with recent changes in 35ec290 and d5642a8.

**Comment by tdcosta100** [comment]
If you are running from the `x64 Native Tools Command Prompt for VS 2022`, could you please post the output of the `set` command?

**Comment by tdcosta100** [comment]
Please also check if this option is enabled under `Desktop Development with C++` in `Visual Studio Installer`:

![image](https://github.com/user-attachments/assets/37e45318-c9cb-4737-9154-50f652fc3d5e)

**Comment by tdcosta100** [comment]
Nice! Currently the build is intended to be run inside `x64 Native Tools Command Prompt for VS 2022`, so if the environment variables inside it are missing, it doesn't work.

**Comment by WuMianzhi** [comment]
one more step should notice, when i git clone  this repo use the command  'git clone --recurse-submodules -j8 https://github.com/maplibre/maplibre-native.git'  it will show the below issuse:
```
error: unable to create file output/nested-multi-polygon-outer-counter-clockwise-inner-counter-clockwise-hole-counter-clockwise/-9.83276,39.4012,-4.37805,41.8614,simplify_distance=8,strictly_simple=1,fill_type=3,mpu=1,par=1.geojson: Filename too long
fatal: Unable to checkout 'a623c19a91947a9d29f9ec5625ce620ab42325dc' in submodule path 'vendor/wagyu
```

then you could set `git config --system core.longpaths true` after this i could build successfully

**Comment by tdcosta100** [comment]
Yes, this is a common problem and the solution is exactly what you did. Maybe I will put a tip in the Windows instructions to help someone who faces this problem.

**Comment by tdcosta100** [comment]
I never did something like this before, but just changing your main project from DLL to EXE should work. Of course, building a shared library would require you to add the mbgl-core.lib and everything else you would add as dependency to the EXE. It should work well, specially if you export the mbgl-core symbols in the DLL, so you can use them in any executable loading the DLL.
