### ISSUE TITLE
Flickering and disappearing lanes on iOS

### ISSUE THREAD

**Issue by saifalharthi** [maplibre/maplibre-native#3009]
**Describe the bug**
The lane markings on the road disappear when zooming in and start flickering as it continues to zoom. This works fine on Android and web. The issue is only on iOS
**Expected behavior**
The lane markings should be entact at any zoom level and not flicker or disappear

**Screenshots**
This is before zooming in
![output_0008](https://github.com/user-attachments/assets/7c8e688e-6139-479e-9e23-b56bb533cc44)
This is after, and it flickers in between while only showing up when starting to perform zoom in/out gesture.
![output_0009](https://github.com/user-attachments/assets/cb8b8b63-f45a-4a25-9ea7-2a758f49aa68)

**Platform information (please complete the following information):**
 - OS: iOS

**Comment by louwers** [comment]
@saifalharthi Thanks for the bug report. Please provide MapLibre iOS version used as well as a minimal reproduction if possible, otherwise it's really hard to debug this.

**Comment by louwers** [comment]
Removing the 'more info needed', because Malcolm will probably take a look at this and he has the details.

**Comment by saifalharthi** [comment]
Closing as this was fixed in 6.8.1.
