### ISSUE TITLE
Dokka API docs missing docstrings

### ISSUE THREAD

**Issue by louwers** [maplibre/maplibre-native#3021]
@sargunv observed that a lot of API documentation is missing all the documentation that is part of the docstrings.

https://maplibre.org/maplibre-native/android/api/-map-libre%20-native%20-android/org.maplibre.android.maps/-map-libre-map/add-on-map-click-listener.html?query=open%20fun%20addOnMapClickListener(listener:%20MapLibreMap.OnMapClickListener)

```kt
  /**
   * Interface definition for a callback to be invoked when the user clicks on the map view.
   *
   * @see MapLibreMap#addOnMapClickListener(OnMapClickListener)
   */
  public interface OnMapClickListener {
    /**
     * Called when the user clicks on the map view.
     *
     * @param point The projected map coordinate the user clicked on.
     * @return True if this click should be consumed and not passed further to other listeners registered afterwards,
     * false otherwise.
     */
    boolean onMapClick(@NonNull LatLng point);
  }
```

**Comment by louwers** [comment]
Oh it's there.

You just have to click a few times. https://maplibre.org/maplibre-native/android/api/-map-libre%20-native%20-android/org.maplibre.android.maps/-map-libre-map/-on-map-click-listener/on-map-click.html

**Comment by sargunv** [comment]
Ah, nice, I didn't click into it far enough!
