### ISSUE TITLE
6.8.0 fails to load/render tiles, 6.7.1 succeeds

### ISSUE THREAD

**Issue by hactar** [maplibre/maplibre-native#3023]
**Describe the bug**
I have a map style I've been using for many maplibre versions thats always worked so far. But, in 6.8.0, when this map style is clean loaded (ie not upgraded from from an app that previously downloaded as 6.7.1), MapLibre does not display the map. I have included a sample project. If you change the dependency to use 6.7.1 in the example project, all works and you see Vienna. If you change the dependency back to 6.8.0, the map continues to appear. Delete the app and build and run again and the map no longer appears.

**To Reproduce**
1. Download the attached sample project.
2. Build and run for iPhone 16 pro 18.1 simulator (I also tried with my 18.1 device).
3. **You will see a "View Loaded" text but nothing else.**
4. In the package dependencies, change from 6.8.0 to 6.7.1.
5. Build and run again.
6. **Now you will see the map.**
7. Change the package dependency back to 6.8.0.
8.  build and run again.
9. **Map continues working.**

**Expected result**
The map should load fine on a clean install under 6.8.0.

**Screenshots**
<table>
  <tr>
    <td style="text-align: center;">
      <img src="https://github.com/user-attachments/assets/b57950d9-d1f4-4afb-87bb-db91665d7fd8" alt="6.8.0" style="width: 50%;">
      <p>6.8.0</p>
    </td>
    <td style="text-align: center;">
      <img src="https://github.com/user-attachments/assets/2c56e908-9985-4fcb-a059-702ccd71f4e7" alt="6.7.1" style="width: 50%;">
      <p>6.7.1</p>
    </td>
  </tr>
</table>

**Platform information (please complete the following information):**
 - OS: iOS 18.1, Xcode 16.1
 - Platform: iOS Simulator and device, though in the actual app it sometimes does work on device.
 - Version: 6.8.0

**Additional context**
Example project: 
[MapSixEightIssue.zip](https://github.com/user-attachments/files/17787012/MapSixEightIssue.zip)

**Comment by louwers** [comment]
Thanks, I will have a look at it.

I see this in the console:

> fopen failed for data file: errno = 2 (No such file or directory)

**Comment by louwers** [comment]
Also doesn't load for me on older versions...

**Comment by louwers** [comment]
I did git bisect and I think d140d5e1659b3804f90f2e2f7f1b8e304a66decc caused a regression.

#2965

**Comment by sargunv** [comment]
> fopen failed for data file: errno = 2 (No such file or directory)

I also saw this, it stopped logging the warning after a clean build in XCode but the map still failed to load.

**Comment by louwers** [comment]
I tried 6.8.1, seems to resolve the issue.
