### ISSUE TITLE
Filters applied to fill extrusion layers are not rendered unless a manual zoom is applied to the map

### ISSUE THREAD

**Issue by elican-doenyas** [maplibre/maplibre-native#3039]
I am setting filters to layers using the layer.setFilter(<expression>) method dynamically from code. The filters take effect for all layers immediately except the fill and fill-extrusion layers(from what I observe, maybe other layers are not rendered properly that I missed). For the fill layers, the filter is applied only if a manual zoom is applied to the map. Otherwise, the filter takes effect after another filter is applied. 

To explain further;

- The user changes to level 1 on the map, a filter is applied on all layers for level 1 using expression programmatically.
- All of the layers filter the features correctly except the fill and fill-extrusion layers.
- User changes to level 2, filter is applied to all layers, all show correct features except the fill and fill-extrusion layers. The fill and fill-extrusion layers still show level 1 features.
- User changes to level 3, the filtering on the fill layer shows the previous filter. So, on the fill and fill-extrusion layers, features with level 2 are drawn.
- User changes to level 1, the features on level 3 are drawn.
- The only way to refresh this layer filter and show the correct features is to manually change the zoom of the map via gestures.

1. Set a filter to all layers programmatically. 
2. Observe filtering takes effect immediately for only certain layers. Not fill and fill-extrusion layers to be precise.
3. Zoom in/out manually, observe features are correctly rendered for all layers.

The filtering on the layers should take effect immediately.

 - Platform: Android
 - Version: Maplibre(11.5.1)
 - Devices: Samsung Galaxy S23(Android 14) - Pixel 8 Pro Emulator (Android 35, 16KB page size)

This issue started happening after I upgraded from 10.2.0 to 11.5.1 for the 16kb device support on the new version. Using the same style, and the same filtering logic, I get the expected behavior on version 10.2.0. 

There are no logs indicating any issue with rendering or filtering.

**Comment by louwers** [comment]
Thanks for the report, let me see if I can reproduce it.

**Comment by elican-doenyas** [comment]
@louwers any update on this issue? we need to migrate to the new version in order to accommodate for the Android 15 16KB page size and this is a blocker for us.

**Comment by elican-doenyas** [comment]
@louwers  I was able to reproduce the issue again in the sample project with the style you provided for ease of debugging.

You can access the codebase from here: https://github.com/elicandoenyas/maplibre-test-2/tree/bugfix/Issue-3039-reproduction

- There is a layer in the style.json named "countries-fill-copy", of type "fill-extrusion" which has its source as "test-tiles", a source we created.
- There is a layer in the style.json named "countries-label-copy", of type "symbol", which has its source as "test-tiles", a source we created.
- In the source "test-tiles", there are two polygons "pika" and "behlul". They have properties "name" and "lvl", each having different values for them to allow filtering.
- In the app, there are 3 buttons, "pika", "behlul" and "Remove Filters". The "Pika" button, adds "lvl" filter as 3 to the test layers, expecting to only show Pika polygon and its label. "Behlul" button add "lvl" filter as 4 to the test layers, expecting to only show Behlul polygon and its label. "Remove Filter" button removes all filters from the test layers.
- When "Pika" button is clicked, the "behlul" polygon related to the "countries-fill-copy" layer does not get hidden right away, only after zoom level changes. (as explained in the issue) Same behavior can be observed for the other buttons. However, the "countries-label-copy" layer applies the filters immediately after clicking the buttons.

Note: This is not happening on version 10.2.0 of MapLibre.
Note 2: This is not happening when the style layer "countries-fill-copy" is of type "fill" instead of "fill-extrusion". This error is ONLY reproducible when the style layer is of type "fill-extrusion".

**Comment by louwers** [comment]
Thanks for the repro, confirmed for both OpenGL and Vulkan now.

**Comment by louwers** [comment]
https://github.com/user-attachments/assets/47fb7185-1008-47a5-b4ef-a7a286e051bd

I will ask the rendering engineers if they can have a look.

Also available in the MapLibre Android Test App on the `repro-3039` branch.

**Comment by louwers** [comment]
Will be part of the 11.7.1 release.

**Comment by elican-doenyas** [comment]
@louwers thanks for the quick action! Is there a timeline for when the 11.7.1 release will be available for use?

**Comment by louwers** [comment]
@elican-doenyas I can make a release today if you need it.

**Comment by elican-doenyas** [comment]
@louwers I see that you released the new iOS but I could not see the Andorid v11.7.1. Was it released 2 days ago?

**Comment by louwers** [comment]
@elican-doenyas Thanks for the reminder, it should be out now.
