### ISSUE TITLE
Android API reference duplicated section

### ISSUE THREAD

**Issue by sargunv** [maplibre/maplibre-native#3049]
**Describe the bug**

At https://maplibre.org/maplibre-native/android/api/, the "See Also" section is duplicated four times for some reason. I only see it once in https://github.com/sargunv/maplibre-native/blob/main/platform/android/MapLibreAndroid/Module.md, so I have no idea why it's there three extra times.

![Image](https://github.com/user-attachments/assets/cad48e75-e26e-4c5b-86ae-6f6f7c64e418)

**Comment by louwers** [comment]
Fixed, thank you!
