### ISSUE TITLE
Cocoapod library newest version missing in the cocoapod trunk

### ISSUE THREAD

**Issue by smaesodev** [maplibre/maplibre-native#3078]
### MapLibre iOS Version

5.12.1

### iOS Version

12

### Device

iPhone Xs

### What happened?

I'm trying to use the cocoapods library because I'll need to create a cocoapods library out of my project, in my podspec I want to reference the MapLibre library but the only version available in the cocoapods trunk is the 5.12.1, at least that's what I'm able to get, thing is, if you check the podspecs uploaded to cocoapods, in theory, 6.8.1 should be available too, but it isn't, any idea why?

### Steps to reproduce

Check the cocoapods spec files

### Relevant log output

```shell

```

**Comment by louwers** [comment]
Ah yes, I see there was an authentication issue during deployment.

I will make a new release today. Thank you!

**Comment by louwers** [comment]
@smaesodev There is an error with Cocoapods.

The newest version is 6.8.1 https://github.com/CocoaPods/Specs/tree/master/Specs/b/0/0/MapLibre
