### ISSUE TITLE
Secrets documentation

### ISSUE THREAD

**Issue by wipfli** [maplibre/maplibre-native#312]
MapLibre GL Native has 14 GitHub secrets. Are these documented somewhere?

**Comment by wipfli** [comment]
Who is CR? I see that we use their personal access token in the android ci workflow...

https://github.com/maplibre/maplibre-gl-native/blob/ca5810f61fde26d0fbccbe4d48d4c771d02e460f/.github/workflows/android-ci.yml#L43-L45

**Comment by wipfli** [comment]
The graddle config might be related to

https://github.com/maplibre/maplibre-gl-native/blob/5b3d936521040149e343f81ed4bd2ce24b75e690/platform/android/scripts/create-signing-key.sh#L13-L17

**Comment by wipfli** [comment]
At the moment we have these github secrets:
![image](https://user-images.githubusercontent.com/53421382/178566955-1cfbf7d9-a499-40e3-8b87-976b08f48d79.png)

**Comment by wipfli** [comment]
Lets store all the secrets as clear text in our password manager...

Is in password manager?

* [ ] BINTRAY_API_KEY
* [ ] BINTRAY_USER
* [ ] CR_PAT
* [ ] DIST_GITHUB_TOKEN
* [ ] GLCLOUD_SERVICE_JSON
* [ ] GPG_KEY_CONTENTS
* [ ] GPG_PASSPHRASE
* [ ] MAPBOX_DEVELOPER_CONFIG_XML
* [ ] MAPLIBRE_DEVELOPER_CONFIG_XML
* [ ] NODE_PRE_GYP_GITHUB_TOKEN
* [ ] OSSRH_PASSWORD
* [ ] OSSRH_USERNAME
* [ ] SIGNING_KEY_ID
* [ ] SIGNING_PASSWORD
* [ ] SONATYPE_STAGING_PROFILE_ID

**Comment by wipfli** [comment]
Since `CR_PAT` is used in the container section here:

https://github.com/maplibre/maplibre-gl-native/blob/73973703426ebf11c3c6bea60857644c44d7b5e5/.github/workflows/android-release.yml#L12-L16

It might be that the abbreviation stands for "Container Registry Personal Access Token"...

**Comment by louwers** [comment]
It's also possible to get the plain text of a secret with a hack: https://stackoverflow.com/questions/63003669/how-can-i-see-my-git-secrets-unencrypted

**Comment by ovivoda** [comment]
Indeed we should have a strategy for this. We should decide where we store the secrets and how do we make them available. If there is anyone that has an overview about this I'd love to setup a short call with.

**Comment by wipfli** [comment]
We store the secrets in a password manager where the Governing Board has access. What the secrets are doing or used for should be documented in the places close to where they are used, i.e., in MapLibre GL JS and Native for the things related to CI. And in maplibre/maplibre for the things unrelated to a repo. Some things in the password manager like the zoom password are also self-explaining...

**Comment by ovivoda** [comment]
@wipfli alright then we need to understand how can we automate this. IE: How can we can ensure security while trying to still access those secrets, for the ones that are really needed. So my suggestion is to make a list of all secrets used in codebase + CI then tackle each one individually. cc @louwers

**Comment by louwers** [comment]
I have cleared up unused secrets and added documentation for the secrets here: https://github.com/maplibre/maplibre-native/wiki/Repository-secrets
