### ISSUE TITLE
Refactor CMake build to be more modular for Linux / MacOS targets

### ISSUE THREAD

**Issue by brendan-ward** [maplibre/maplibre-native#364]
Right now, the Linux (`platform/linux/linux.cmake`) / MacOS builds (`platform/macos/macos.cmake`) also build `bin`, `expression-test`, `glfw`, and `node` targets, which may not be necessary depending on the goal of the build (e.g., building core lib, render tests, etc).

The easiest path foward may be to add additional CMake options to the top-level `CMakeLists.txt` to enable building those additional platform-specific targets.  I'd suggest that those targest are opt-in rather than opt-out, but that might be a breaking change for some folks.

Something like

```
option(MBGL_WITH_GLFW "Build with GLFW for Linux / MacOS platforms" OFF)
option(MBGL_WITH_NODE "Build NodeJS bindings for Linux / MacOS platforms" OFF)
```

**Comment by louwers** [comment]
`MLN_WITH_NODE` is now present.
