### ISSUE TITLE
`render-tests/icon-image/icon-sdf-non-sdf-one-layer` fails on macOS in CI

### ISSUE THREAD

**Issue by wipfli** [maplibre/maplibre-native#377]
On macOS GitHub runners, `render-tests/icon-image/icon-sdf-non-sdf-one-layer` fails and produces this output:

![image](https://user-images.githubusercontent.com/53421382/180618264-1764e4de-0a59-460f-8249-76bbd6a4184c.png)

**Comment by wipfli** [comment]
Let's disable it for now...

**Comment by louwers** [comment]
We're not running any render tests for macOS right now.
