### ISSUE TITLE
Improve documentation and explanation of implementation

### ISSUE THREAD

**Issue by jay-cohen** [maplibre/maplibre-native#516]
**Describe the bug**

As the title mentions there is a lack of quality documentation regarding MapLibre's installation and use that isn't bloated with third party services. There a no links other than towards the API reference which isn't 100% helpful when familiarising with the SDK.

For example, how would a user convert from an existing service such as MapKit or Google/Bing Maps SDK to MapLibre with applying a custom style that doesn't require an API key or account to a third party such as MapTiler or MapBox.

**Expected behavior**
A clear and concise description of what is needed to get MapLibre working on a platform that isn't over bloated with third party services pitching their product.

**Comment by wipfli** [comment]
Good point, improving the documentation is indeed a low hanging fruit. What helps a lot is if people new to the project can share difficulties getting started. So if you have some specific improvement for a paragraph in a README or so, please share it in a pull request.

**Comment by wipfli** [comment]
With your permission I will change the title to "Improve..."  and we can use this as a tracking issue to make the docs better...

**Comment by jay-cohen** [comment]
@wipfli - The main difficulties faced were around the customisation stages. For example, using custom styles dependant upon either MapBox or a custom tile/sprite provider. Also, there's a heap of documentation online regarding installation and api reference for Web, but none for Mobile which isn't transferrable as the api method calling is inherently different.

Finally, unsure if the community is aware but MapBox has changed its installation process which doesn't tie in with MapLibre's installation process to [get a working map on the device](https://docs.mapbox.com/ios/maps/guides/install/#add-a-map)

**Comment by louwers** [comment]
I am closing this issue because it is too broad.

We now have examples for Android and we have several open issued with bounties to create example documentation for iOS.

Please add your ideas to #814 or if you have an idea for a specific actionable task to improve the documentation, feel free to create an issue.
