### ISSUE TITLE
Vulkan Backend Support

### ISSUE THREAD

**Issue by jwinarske** [maplibre/maplibre-native#525]
Supporting a Vulkan backend would be preferred over GL.

**Comment by wipfli** [comment]
Thanks for the input, @jwinarske. Vulkan is related to the ongoing proposal of @mousebird and Stamen I guess. You can read more about this at https://github.com/maplibre/maplibre-gl-native/discussions/317

**Comment by mousebird** [comment]
There's a lot going on with the proposal we're making.  But it's focused on Metal at the moment, with some bits that would facilitate Vulkan in the future..... if there's funding.  Funding is the #1 issue for something like Vulkan.

**Comment by jwinarske** [comment]
I can participate in development of a Vulkan backend.

**Comment by wipfli** [comment]
Nice, do you have experience with Vulkan? Is there maybe an open-source project you are working on @jwinarske?

**Comment by jwinarske** [comment]
https://github.com/toyota-connected/ivi-homescreen
It supports GLESv2 and Vulkan backends.

My Vulkan Wayland support was merged into Filament.

I'm also interested in supporting OpenStreet.

I also have experience in Yocto:
https://github.com/jwinarske/meta-vulkan/tree/dunfell-no-mesa

**Comment by jwinarske** [comment]
This framework could be adopted to render vector tiles.  It's a replacement to Skia, supports multiple backends, and is license friendly:
https://github.com/flutter/engine/tree/main/impeller

**Comment by mousebird** [comment]
We've discussed this a fair bit at the last two Technical meetings, which the community was kind enough to invite me to.
There's a fair bit of background there, but Stamen Design and myself are in the processing of getting a company to fund the planning phase of an upgrade to MapLibre Native to support Metal and do some general graphics restructure to support other toolkits in the future.

There will be more discussion and I'd suggest getting in on it.  Would be great to have a Vulkan expert in the mix.

**Comment by jwinarske** [comment]
Happy to participate.  I would be the advocate for an agnostic backend interface.  Impeller backends supported are GLES, Metal, and Vulkan.  A great example of an agnostic backend interface.

**Comment by louwers** [comment]
This year work will be done on renderer modularization (& Metal will be implemented as a backend), which will make Vulkan as a backend possible too.

Please see: https://github.com/maplibre/maplibre-gl-native#renderer-modularization--metal

**Comment by birkskyum** [comment]
An early vulkan backend has been merged to main
- https://github.com/maplibre/maplibre-native/pull/2564

It's not complete enough to close this ticket, but it's a great start.

**Comment by louwers** [comment]
An initial implementation landed with https://github.com/maplibre/maplibre-native/pull/2564. Let's track future improvements and integration of the Vulkan backend in specific issues. See issues and PRs labeled with the [Vulkan](https://github.com/maplibre/maplibre-native/issues?q=is%3Aissue+is%3Aopen+label%3AVulkan) label for outstanding issues. cc @sjg-wdw @adrian-cojocaru
