### ISSUE TITLE
Check that build steps in release are also executed in pull request CI

### ISSUE THREAD

**Issue by wipfli** [maplibre/maplibre-native#605]
I have noticed that `make android-javadoc` only runs in the `android-release.yml` workflow but not in the `android-ci-pull.yml` workflow. This step seems to be broken now and blocks us from making a release.

I would like to check if the steps we run in the release workflow are also running the pull request CI...

**Comment by wipfli** [comment]
Firebase device tests currently do not pass with java 8 on the android-release.yml workflow. They are present in the android-ci.yml workflow here:

https://github.com/maplibre/maplibre-gl-native/blob/1bdeb6e260b7f10be09964637f50b4932f24190e/.github/workflows/android-ci.yml#L135-L161

We should make sure that the firebase test either run on every pull request or we should remove them completely...

**Comment by louwers** [comment]
Once the new CI is meged I will look into this.

**Comment by louwers** [comment]
They are no longer separate.
