### ISSUE TITLE
Too many (700)  warning when building MapboxGLAndroidSDKTestApp

### ISSUE THREAD

**Issue by artakka** [maplibre/maplibre-native#610]
**Describe the bug**
We have a lot of warning when building MapboxGLAndroidSDKTestApp. The list is attached.

**Expected behavior**
Some will be trivial to fix, others, like deprecated APIs are more involved. We can fix the easy ones and enter more tasks for more difficult ones. Some I am sure also can be safely ignored.

**Platform information (please complete the following information):**
 - OS: Android

[MapboxGLAndroidSDKTestAppWarnings.txt](https://github.com/maplibre/maplibre-gl-native/files/10248100/MapboxGLAndroidSDKTestAppWarnings.txt)

**Comment by birkskyum** [comment]
With recent changes, it would be interesting to get an updated log.
