### ISSUE TITLE
 Strange carplay map behavior after app installation

### ISSUE THREAD

**Issue by Bonusik** [maplibre/maplibre-native#628]
**Describe the bug**

After reinstalling the application to a newer version, the carplay map looks like on the screenshots. Supposedly helps turning off bluetooth and wifi, and turning both back.

**To Reproduce**
1. Connect phone to carplay
2. Click on app
3. See error

**Expected behavior**
Map with loaded style.

**Screenshots**

![adda](https://user-images.githubusercontent.com/9887189/208919352-aab7f7bd-899e-44e3-bb6c-84e45df96d99.png)

**Platform information (please complete the following information):**
 - OS: 16.2
 - Platform iOS
 - Version 5.13.0-pre.1

**Additional context**

**Comment by louwers** [comment]
Which app are you refering to @Bonusik?

**Comment by Bonusik** [comment]
It's my own project that is not on app store yet.
