### ISSUE TITLE
Design version declaration for all MapLibre projects.

### ISSUE THREAD

**Issue by thehoneymad** [maplibre/maplibre-native#660]
Detecting versions for a release right now is done through git tags. This has its benefits. But it also has its pitfalls. We want to consider alternatives of using git tags for version management.

Because:
1. Git tag version management requires reading the full git history in automated builds to deduce version.
2. Version deduction on Makefiles or any other orchestration mechanism relies on Git tagging. The version is inconsistent across branches.

This task is about writing a design document that proposes a version deduction for all MapLibre projects.

**Comment by louwers** [comment]
For iOS we use a VERSION file now. But we still create a tag, because the GitHub release process requires it.
