### ISSUE TITLE
Release Swift package to maplibre-gl-native-distribution with CI

### ISSUE THREAD

**Issue by louwers** [maplibre/maplibre-native#662]
@petr-pokorny-1 made manual releases to https://github.com/maplibre/maplibre-gl-native-distribution in the past.

It would be helpful if this is automated and done during an iOS release automatically.

**Comment by louwers** [comment]
I made a manual release now and even duplicated the release notes so they will show up on the Swift Package Index. I guess it makes most sense to fix this once a descision has been made to [split by platform](https://github.com/maplibre/maplibre-gl-native/discussions/321). Then the [maplibre-gl-native-distribution](https://github.com/maplibre/maplibre-gl-native-distribution) repo won't be needed anymore.

**Comment by roblabs** [comment]
@louwers  — thank you for making the Swift Package release.

The distribution repo has Swift Playground called *MapLibre Test*, and I was able to give your manual release a test using that Playground in Xcode 14.2.

See https://github.com/maplibre/maplibre-gl-native-distribution/issues/8

---
*Screenshot of Playground for the MapLibre Swift Package*
![image](https://user-images.githubusercontent.com/118112/211564643-13302860-e973-4128-8a48-62d8892d7ba8.jpeg)

**Comment by roblabs** [comment]
@louwers  — yes, it worked as expected in the very basic Playground test.  I recommend keeping the `maplibre-gl-native-distribution` as is until the main Native has fully gone through it's _split repo_ state.
