### ISSUE TITLE
Create a CI/CD process for Android with a reusable workflow

### ISSUE THREAD

**Issue by thehoneymad** [maplibre/maplibre-native#693]
Currently, we have the following workflow files:
1. `android-ci-pull.yml`: Triggers on pull request only.
2. `android-ci.yml`: Near complete copy and paste of 1. Additionally, builds the test app APK and publishes it to GCP.
3. `android-docker-base.yml`: Pushes a docker image to Github packages with Android NDK to be reused in builds.
4. `android-docker-ndk-r21b-docker-image.yml`: Nearly the same thing as the previous one. Uses Android NDK r21b image.
5. `android-release.yml`: This takes care of the publishing Maven artifact of Android SDK of MapLibre to maven central.

The goal of this task is to define a CI/CD workflow that:
1. Reuses workflow steps that are common across all the workflows.
2. Builds MapLibre GL Native, Android SDK separately and sequentially.
3. Removes unnecessary workflows.
4. Documents why the docker images are necessary.

**Comment by louwers** [comment]
Related #622

**Comment by ovivoda** [comment]
Related [#714](https://github.com/maplibre/maplibre-gl-native/discussions/714)

**Comment by louwers** [comment]
The docker images are gone now.

The instrumentation tests likely need to be disabled until we move them to AWS. So we can get rid of `android-ci.yml` for now as well.

That leaves us with two workflows for Android:

```mermaid
  graph TD;
      androidtest[android-test]
      androidrelease[android-release]
      androidtest --> androidrelease
```

**Comment by ovivoda** [comment]
@louwers can you elaborate a bit more on: `The instrumentation tests likely need to be disabled until we move them to AWS`. Tx!
