### ISSUE TITLE
Monthly Usage Report for Android

### ISSUE THREAD

**Issue by thehoneymad** [maplibre/maplibre-native#695]
Monthly usage report for MapLibre Android helps understand adoption of MapLibre. Ideally, this should be done for all MapLibre. But the goal is to start with something small.

#### Requirements
A bot/workflow MUST be written that:
1. Runs on a monthly cadence.
2. Collects usage report and publishes it.

This could also be a running dashboard that does not require a bot. This I have not looked into and investigated.

**Comment by louwers** [comment]
Related:  [#181](https://github.com/maplibre/maplibre/issues/181)

**Comment by wipfli** [comment]
Sonatype has download statistics:

![image](https://user-images.githubusercontent.com/53421382/213211860-fb67ce43-a2be-4e3a-a625-0e6a0c437e8b.png)
