### ISSUE TITLE
Investigate configuring Xcode with pure CMake

### ISSUE THREAD

**Issue by louwers** [maplibre/maplibre-native#737]
Investigate if CMake's iOS support is now good enough to configure Xcode with CMake.

Right now we run CMake, but also copy hardcoded xcsettings files and xcconfig around. It's quite hairy and not very transparant for newcomers to the project. See this [Makefile](https://github.com/maplibre/maplibre-gl-native/blob/main/platform/ios/Makefile).

Maybe we can get rid of all the checked in configuration files like [this one](
https://github.com/maplibre/maplibre-gl-native/blob/main/platform/ios/platform/macos/macos.xcodeproj/project.xcworkspace/contents.xcworkspacedata#L5).

References:

- [Comment from @hallahan](https://github.com/maplibre/maplibre-gl-native/discussions/699#discussioncomment-4791544) on this
- [Inveresting thread on Slack about this topic](https://osmus.slack.com/archives/C04K0NBUEEM/p1674662156251219)

**Comment by ntadej** [comment]
Note that I do that for my project, but it is Qt-based, so maybe it's simpler in that sense.

**Comment by louwers** [comment]
First potential blocker https://gitlab.kitware.com/cmake/cmake/-/issues/20160

**Comment by louwers** [comment]
> we need to figure out what are the actual limitations of CMake

@ntadej As an example, setting up the iosapp target: https://github.com/maplibre/maplibre-gl-native/tree/main/platform/ios/platform/ios/app

I don't think it is possible with CMake. Even the [ios-cmake](https://github.com/leetal/ios-cmake/tree/master/example/example-app) project has a checked in `.xcodeproj` directory alongside their example app.

**Comment by louwers** [comment]
Closing because #840 is implemented.
