### ISSUE TITLE
Unable to build on Debian 11

### ISSUE THREAD

**Issue by hallahan** [maplibre/maplibre-native#747]
I'm on Debian 11 on a Google Cloud Compute instance, and I'm trying to build maplibre-gl-native. I can access a desktop session via Chrome Remote Desktop.

When I run the following command, I get the following error:

```
$ cmake . -B build -G Ninja -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_C_COMPILER=gcc-10 -DCMAKE_CXX_COMPILER=g++-10
-- Configuring GL-Native with OpenGL renderer backend
-- Found the following ICU libraries:
--   i18n (optional)
-- Found ICU: /usr/include (found version "67.1") 
-- Found the following ICU libraries:
--   uc (optional)
-- Found ICU: /usr/include (found version "67.1") 
CMake Error at /usr/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
  Could NOT find JPEG (missing: JPEG_LIBRARY JPEG_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.18/Modules/FindJPEG.cmake:100 (find_package_handle_standard_args)
  platform/linux/linux.cmake:4 (find_package)
  CMakeLists.txt:1097 (include)
```

The [instructions](https://github.com/maplibre/maplibre-gl-native/blob/main/platform/linux/README.md) do not say anything about adding a `JPEG_LIBRARY JPEG_INCLUDE_DIR` env var. Do I need to do this? What am I doing wrong? Note that I did indeed install all of the apt packages instructed.  

Also, because I am on a Remote Desktop session, I would actually like to launch the interactive app. I do not need the JPEG functionality. How do I do this?

```
Distributor ID:	Debian
Description:	Debian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye
```

**Comment by wipfli** [comment]
I remember there were some difficulties when I built the linux platform. Have a look at https://github.com/maplibre/maplibre-gl-native/tree/main/platform/linux#prerequisites

**Comment by hallahan** [comment]
Yes, these are the instructions I am following.

**Comment by wipfli** [comment]
Anyway, I remember also having issues with jpeg on a new machine. I think I installed the apt stuff 3 times and then it worked...

**Comment by wipfli** [comment]
https://github.com/maplibre/maplibre-gl-native/pull/295#issuecomment-1146317817

**Comment by wipfli** [comment]
If you figure out how to get this to compile on first try on a clean new machine, feel free to update the docs...

**Comment by acalcutt** [comment]
When I built it inside Ubuntu 20.04 for the node workflow I install these packages, https://github.com/maplibre/maplibre-gl-native/blob/main/platform/node/scripts/Dockerfile_Build#L7-L23 > One of those packages installed is 'libjpeg-turbo8'...I think installing that.

The linux instructions were based on the packages needed in the github workflow, but I think some packages are already installed in the github runners.

**Comment by breunigs** [comment]
I'm fairly certain the error message is generated when `libjpeg-turbo8-dev` is not installed. This package is also not listed in the instructions. Below is a Dockerfile that sets up things more or less from scratch and does a basic check to ensure the resulting binary works properly. 

```Dockerfile
# specify which branch or commit sha to build
ARG MLGLN_COMMIT=master

FROM debian:bullseye-slim AS runner-base
RUN apt-get -y update \
  && apt-get -y install --no-install-recommends \
  ca-certificates \
  curl \
  && curl \
  -O http://archive.ubuntu.com/ubuntu/pool/main/libj/libjpeg-turbo/libjpeg-turbo8_2.0.3-0ubuntu1_amd64.deb \
  -O http://archive.ubuntu.com/ubuntu/pool/main/i/icu/libicu66_66.1-2ubuntu2_amd64.deb \
  && echo "1995dec9707f7e0d827ae49301d2ab20 libjpeg-turbo8_2.0.3-0ubuntu1_amd64.deb" | md5sum --check - \
  && echo "9c4963f572de577f425bdfcb0e7c4c7f libicu66_66.1-2ubuntu2_amd64.deb" | md5sum --check - \
  && apt-get -y install --no-install-recommends \
  ./*.deb \
  libcurl4 \
  libglx0 \
  libopengl0 \
  libpng16-16 \
  libuv1 \
  xauth \
  xvfb \
  && rm -rf /var/lib/apt/lists/* \
  && rm *.deb

FROM runner-base as cloner
RUN apt-get -y update \
  && apt-get -y install --no-install-recommends \
  git \
  && rm -rf /var/lib/apt/lists/*
ENV MLGLN_COMMIT=$MLGLN_COMMIT
RUN git clone --recurse-submodules -j8 https://github.com/maplibre/maplibre-gl-native.git /build \
  && cd /build \
  && git reset --hard ${MLGLN_COMMIT}

FROM runner-base as builder
RUN apt-get -y update \
  && curl \
  -O http://archive.ubuntu.com/ubuntu/pool/main/libj/libjpeg-turbo/libjpeg-turbo8-dev_2.0.3-0ubuntu1_amd64.deb \
  && echo c19e6747893f44eec34abe40b29d7aca libjpeg-turbo8-dev_2.0.3-0ubuntu1_amd64.deb | md5sum --check - \
  && apt-get -y install --no-install-recommends \
  ./*.deb \
  ccache \
  cmake \
  g++-10 \
  libc++-dev \
  libc++abi-dev \
  libcurl4-openssl-dev \
  libgl1-mesa-dev \
  libgl1-mesa-dri \
  libglfw3-dev \
  libpng-dev \
  libuv1-dev \
  ninja-build \
  pkg-config \
  && rm -rf /var/lib/apt/lists/*
COPY --from=cloner /build/ /build/
WORKDIR /build/
RUN cmake . -B build -G Ninja -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_C_COMPILER=gcc-10 -DCMAKE_CXX_COMPILER=g++-10 \
  && cmake --build build -j $(nproc 2>/dev/null)

FROM runner-base as runner
ENTRYPOINT [ "/workdir/mbgl-render" ]
WORKDIR /workdir
COPY --from=builder /build/build/bin/mbgl-render /workdir/mbgl-render

RUN ldd ./mbgl-render \
  && /usr/bin/xvfb-run -a \
  /workdir/mbgl-render --style https://raw.githubusercontent.com/maplibre/demotiles/gh-pages/style.json --output /tmp/out.png \
  && echo d44ec9382869ceaee21de6ae10ae78f3 /tmp/out.png | md5sum --check - \
  && rm /tmp/out.png
```

**Comment by louwers** [comment]
> This package is also not listed in the instructions. 

Thanks for sharing! We should update the Debian build instructions.
