### ISSUE TITLE
Investigate current setup of iOS UI tests

### ISSUE THREAD

**Issue by louwers** [maplibre/maplibre-native#769]
- Do we need to run them on AWS Device farm?
- Do we update the iOS version or disable old iOS versions?
- Is the output of the tests on CI right now actually used?

**Comment by roblabs** [comment]
Notes on the how & why of iOS UI Tests, specifically designed for automated testing on AWS Device Farm:

https://github.com/maplibre/maplibre-gl-native/issues/39

**Comment by louwers** [comment]
They run fine in the simulator and are running on CI now.

https://github.com/maplibre/maplibre-native/blob/c1ba70ec00367f29f448f78d338263ef4f35616f/.github/workflows/ios-ci.yml#L140
