### ISSUE TITLE
Drop code related to iOS 11 or below

### ISSUE THREAD

**Issue by louwers** [maplibre/maplibre-native#776]
Based on the discussion #689 we will only support iOS 12 or above going forward.

---

- [ ] Remove simulators old iOS version in Makefile

https://github.com/maplibre/maplibre-gl-native/blob/95f41105e83746b28cc75886151be2aafbf2da0d/platform/ios/Makefile#L96

- [ ] Set iOS deployment target to 12.0 (the current deployment target of iOS 9.0 is not even supported by the newest version of XCode).

https://github.com/maplibre/maplibre-gl-native/blob/main/platform/ios/ios.cmake#L4

- [ ] Add note to README that only iOS 12 or above is supported

... If you know other places that need to be updated, let me know.

**Comment by roblabs** [comment]
Based on this comment, we should make a mention of supported Xcode versions.

---

> @louwers — "*(the current deployment target of iOS 9.0 is not even supported by the newest version of XCode).*"

---

Big Sur only supports up to Xcode 13.2.1.  So maybe we can expect developers to use at least Xcode 13.  The only mention (that I can recall) of Xcode requirements is in the badges/shields for [maplibre/maplibre-gl-native-distribution](https://github.com/maplibre/maplibre-gl-native-distribution#maplibre-gl-native-sdk-for-ios).
