### ISSUE TITLE
Continuous Integration is failing on `metal-support` branch

### ISSUE THREAD

**Issue by roblabs** [maplibre/maplibre-native#78]
* The build step `make ios-test` fails on GitHub Actions at [step 12, Line 1318](https://github.com/maplibre/maplibre-gl-native/runs/2469339813?check_suite_focus=true#step:12:1318)
* `make ios-test` builds fine on a local dev machine.  
  * Need to be able to replicate on GitHub Actions either in the cloud build or a `self-hosted` build.  
  * [Reference for _hosting own runners_](https://docs.github.com/en/actions/hosting-your-own-runners).
  * [Reference for _Self-hosted runners for GitHub Actions_](https://github.blog/2019-11-05-self-hosted-runners-for-github-actions-is-now-in-beta/)
  * Recommend:  make a new branch called `gh-actions` and touch files to change there. 
  * See https://github.com/maplibre/maplibre-gl-native/compare/master...roblabs:gh-actions as an example of a separate branch that will not be checked in, but can facilitate testing of `self-hosted` builds.
* The error in the logs _"Failed To call eglInitialize()"_ is a reference in the MetalANGLE code, and basically is saying that the eglDisplay failed.  Link to [Display.mm#L28,L37](https://github.com/kakashidinho/metalangle/blob/f3ab2c261fb9dcfa98a7294fe54bae814b817632/ios/xcode/MGLKit/MGLDisplay.mm#L28,L37)
  * The GitHub Actions build machine builds on an iPhone 8:  Log entries `SimDevice: iPhone 8, iOS 14.4`

**Comment by roblabs** [comment]
I opened a support ticket with GitHub regarding Metal Unit Tests failing on GitHub Action.  I

* https://support.github.com/ticket/personal/0/1156697 (may only be viewable by me)

---

Hello,

Our Open Source project, [maplibre/maplibre-gl-native](https://github.com/maplibre/maplibre-gl-native), has GitHub Actions up and running for iOS and Android builds.  And it works famously.

For the iOS project, we have a new feature that is now failing on the GitHub Actions, but _not_ failing on local self-hosted runners.  Please see https://github.com/maplibre/maplibre-gl-native/issues/78.  The new feature we are implementing for MapLibre is based on [Metal](https://developer.apple.com/metal) which gives direct access to the GPUs.

Research Questions from the MapLibre team for the GitHub Actions Team:

* Can you verify the specs & configuration of the macOS images that are used by GitHub Actions?
* Do they support Metal GPU rendering?
  * There is a discussion, (https://github.com/kakashidinho/metalangle/issues/55#issuecomment-831018912, where there is mention about how the GPUs are configured on GitHub Actions.
* Is there a way to configure the macOS image for Metal?  Does an Enterprise account allow Metal GPU access?

Any light you can shed on this issue would be useful.

Best regards,

Rob

**Comment by roblabs** [comment]
#### Response from GitHub Support.  

> *As far as I know, the hosted runners can't be customized, the recommendation is usually to use self-hosted runners in the case where there are specific hardware needs.*

> *But the best place for these types of questions is https://github.com/actions/virtual-environments -- the maintainers there are great about clarifying details about the hosted runners as well as information about the host machines (the most information we can share here in Support is what's publicly documented: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#cloud-hosts-for-github-hosted-runners).*

> *As an example, someone recently asked about a particular feature of the host machines (https://github.com/actions/virtual-environments/issues/3389) and the team was able to address that question -- the other benefit is that once the question is answered, the information will be publicly available in case anyone else has a similar question.*

**Comment by roblabs** [comment]
- [ ] Review AWS EC2 Mac to see if it can fill our CI needs with Metal
- [x] Review open tickets at the repo [actions/virtual-environments](https://github.com/actions/virtual-environments) mentioning Metal:  https://github.com/actions/virtual-environments/search?q=metal&type=issues

#### Statement on GPU Passthrough
Src:  https://github.com/actions/virtual-environments/issues/1779#issuecomment-707071183
> *our current virtualization approach for macOS doesn't allow us to provide GPU passthrough due to several hardware and software limitations. Moreover, I'm afraid there are no plans to make GPU functions available for macOS runners in the nearest future.*

**Comment by roblabs** [comment]
An update on the Action Item:
> - [x] Review [AWS EC2 Mac](https://aws.amazon.com/ec2/instance-types/mac/) for our CI needs with Metal

---

I was able to verify that the [Metal](https://developer.apple.com/metal) GPU Unit & UI tests do indeed work on an AWS EC2 Mac instance.  This gives the MapLibre Native community an option while looking for a replacement for Metal tests currently running on GitHub Actions

#### Items for MapLibre Native team to review

* A potential solution for Metal testing; we still need a way to run some tests on GitHub Actions.
* Testing makes use of the [GitHub Self Runners](https://docs.github.com/en/actions/hosting-your-own-runners) + AWS EC2 Mac
* MapLibre community will have to manage an AWS account auth, device auth, and secrets.  GitHub Actions handled all of this through the GitHub auth.
* [AWS Pricing](https://aws.amazon.com/ec2/instance-types/mac): 
  * > *"Billing for EC2 Mac instances is per second with a 24-hour minimum allocation period to comply with the Apple macOS Software License Agreement."*
* MapLibre community will need to build and manage a Mac AMI that has the proper version of Xcode & storage.
* The `aws` CLI can be useful for some of the DevOp tasks.
  * Potential to make use of AWS Device Farm for GPU testing

---

##### Specs on the May 2021 Device
* Mac mini with Big Sur + Command Line Tools for Xcode & Homebrew
  * Catalina & Mojave also available
* Six physical cores, 12 virtual CPUs
* 32 GB of Memory
* 60 GB + configurable with [Amazon EBS](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/AmazonEBS.html)
* Access is via SSH & VNC ports (22 & 5900)

---

*MapLibre with Metal in the Cloud, a potential workaround for VMs with no GPU support*
![image](https://user-images.githubusercontent.com/118112/119194546-164cd100-ba38-11eb-9c6d-b623e1f9ad60.png)

---

<details> <summary>Useful Dev Op tips for running MapLibre builds on AWS</summary>

* Add Amazon EBS storage of 100 GB
* Some of these steps will be done once, after a custom MapLibre AMI (with Xcode 12.4 & GitHub Actions is installed)

```bash
# Run these commands from the SSH so you can copy/paste from this doc

# Disk Utility
open -a Disk\ Utility

# open a web page in Safari
open https://maplibre.org

# Inspect which Xcode tools are available
xcode-select -print-path
open /Library/Developer/CommandLineTools
xcodebuild -version
man xcodebuild

# brew
brew list --versions awscli

# The build tool chain for MapLibre should be installed via the GitHub Actions

# Install Xcode
# open Safari in Apple Developer
open https://developer.apple.com/downloads
# search for Xcode 12.4.  When MapLibre supports Xcode 12.5, then you can use App Store
# After downloading move to EBS Storage
HUH=/Volumes/huh
mkdir ${HUH}/Xcode_12.4

mv ${HUH}/Xcode_12.4.xip ${HUH}/Xcode_12.4
cd ${HUH}/Xcode_12.4
# Open and launch the `.xip` from Finder, as this fails
open ${HUH}/Xcode_12.4/Xcode_12.4.xip

# Setup Xcode when in a custom path
sudo xcode-select --switch ${HUH}/Xcode.app/Contents/Developer/

# manual build
cd ${HUH}/maplibre-gl-native/platform/ios

# open folder where build logs live
open ${HUH}/maplibre-gl-native/platform/ios/build

# Manually Running ios unit tests
make ios-test

# Manually Running ios UI tests
make ios-uitest
```
</details>

**Comment by wipfli** [comment]
@roblabs was CI on the metalANGLE branch implemented since your last post?

**Comment by wcandillon** [comment]
Hi 🙋🏼‍♂️ I'm a maintainer of react-native-skia and we would be interested in running metal in our e2e tests. You guys are using your own custom github action runner? Is that an approach you would recommend? We would be interested to learn more about this.

**Comment by wcandillon** [comment]
Thanks a lot! And it integrates with the github action API? would you have some pointers I could follow to learn about this topic?

**Comment by louwers** [comment]
The setup of the macOS runners is documented in a separate repo https://github.com/maplibre/maplibre-ci-runners

@birkskyum Can we make this repo public? The only somewhat sensitive information contained in it are the hostnames, which are probably OK to be public. [Should a hostname ever be considered a secret?](https://security.stackexchange.com/questions/43315/should-a-hostname-ever-be-considered-a-secret)

**Comment by birkskyum** [comment]
Let's do that. Ansible is not active yet right?

**Comment by louwers** [comment]
They are already Ansible-managed servers in the sense that I already ran the `macos.yaml` playbook. Ansible does not run on the target machines! It is just executing SSH commands.

More on topic: can this ticket be closed? The `metal-support` branch seems stale and started before the two design proposals for Metals support where accepted. I think it is unlikely that @sjg-wdw will use it as a starting point.

**Comment by wipfli** [comment]
If I remember correctly a previous technical steering committee meeting, the decision was to keep the MetalANGLE implementation alive such that we can offer and immediate solution if Apple should deprecate OpenGL one day.

**Comment by ntadej** [comment]
Yes, but the idea was also to integrate it into main. I guess we need to find a candidate for that 😊

**Comment by louwers** [comment]
> if Apple should deprecate OpenGL one day

I assume you mean if Apple ever kills off OpenGL completely, they have already deprecated it. :see_no_evil: In any case, makes sense! Whoever picks up #94 can change the workflows to run on the new self-hosted runners instead.

**Comment by louwers** [comment]
I don't see this being picked up anytime soon. With the Metal rendering backend well underway, I am closing this until someone is actively work on MetalANGLE. That said, I don't think it would make sense when we have a rendering backend that uses Metal-cpp directly.

Progress can be tracked here: https://github.com/orgs/maplibre/projects/8
