### ISSUE TITLE
Define plan for test coverage for Core, Android, iOS

### ISSUE THREAD

**Issue by louwers** [maplibre/maplibre-native#784]
For each platform we should answer the questions:

- Do we want to have a report of test coverage?
- If yes, what tools can we use to use to generate the report?
- How will we use the coverage reports help us in making decisions?

I want to bring this topic up during tonights TSC meeting.

My personal opinion on the matter is that actually running all tests (including instrumentation tests and all render tests) has first priority.

**Comment by ovivoda** [comment]
@louwers I think this is useful to have. Maybe not a top priority but if we want to have a stable platform we will need to invest both in writing new features and writing tests to cover those features. 

Let's put this on the next TSC meeting to get the grasp of the feeling of urgency from the community.

**Comment by louwers** [comment]
For future reference: I am about to delete this file in a PR because we don't use it right now.

https://github.com/maplibre/maplibre-gl-native/blob/87337ddb66092e0d54e5ead84dcc04ac489e7e43/scripts/collect-coverage.sh

**Comment by louwers** [comment]
@wipfli Since Martin uses Codecov.io, I think it makes sense to use it too here.

Can you try logging in with "Public repos only":

<img width="566" alt="image" src="https://user-images.githubusercontent.com/649392/229089663-29f34013-a975-4f1f-961e-4d0a7e4f7eb2.png">

You might need to delete your cookies first:

https://community.codecov.com/t/cannot-login-codecov-asks-for-permissions-to-private-repos/4236/3

**Comment by louwers** [comment]
We have test coverage for the Core.

Closing this for now as it is not supported by AWS Device Farm for iOS and Android.

https://stackoverflow.com/questions/43008366/how-do-i-get-code-coverage-of-aws-device-farm-tests-with-android
