### ISSUE TITLE
Disable bitcode generation

### ISSUE THREAD

**Issue by louwers** [maplibre/maplibre-native#805]
Since Xcode 14 bitcode generation is deprecated:

https://stackoverflow.com/questions/72543728/xcode-14-deprecates-bitcode-but-why

We should disable it.

https://github.com/maplibre/maplibre-gl-native/blob/main/platform/ios/platform/ios/config.cmake#L5

**Comment by ovivoda** [comment]
@louwers is this more like a question? Or you think we should disable it?

**Comment by louwers** [comment]
It is a TODO. We should definitely disable it. Apple deprecated it.

**Comment by ntadej** [comment]
Yes, but it should not hurt (besides potentially making frameworks a bit larger).
