### ISSUE TITLE
Example: using LocationComponent to show the user's current location

### ISSUE THREAD

**Issue by louwers** [maplibre/maplibre-native#812]
Create a pull requests that includes a tutorial of how to show the user's current location. This issue has an associated bounty for the [documentation](https://github.com/maplibre/maplibre/issues/191) bounty direction.

## Deliverables

- The example should cover showing the user's current location with the [`LocationComponent`](https://maplibre.org/maplibre-gl-native/android/api/-mapbox-g-l-android-s-d-k/com.mapbox.mapboxsdk.location/-location-component/index.html).
- It should be added as an activity to MapboxGLAndroidSDKTestApp (you can use an existing one if it makes sense).
- Docs should be added to MdBook in `docs/mdbook`. Use an 'anchor comment' and regular expressions to include the Kotlin source code in the docs. Explained here: https://rust-lang.github.io/mdBook/format/mdbook.html#including-portions-of-a-file
- Explain that you can configure the LocationComponent with [`LocationComponentActivationOptions.Builder`](https://maplibre.org/maplibre-gl-native/android/api/-mapbox-g-l-android-s-d-k/com.mapbox.mapboxsdk.location/-location-component-activation-options/-builder/index.html).
- The example should cover how to [change the color of the puck](https://github.com/maplibre/maplibre-gl-native/blob/01729b9a49af9836686658a525ddae3cdc6698cb/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/location/CustomizedLocationPulsingCircleActivity.kt#L286).
- Code samples should use Kotlin
- Include at least two screenshots in your tutorial (you may want to provide a fake location to not expose your location). Drag and drop them to GitHub so we don't need to store them in the git tree.
- Please don't re-use any guides or tutorials that do not have a permissive license. [This](https://github.com/aws-samples/amazon-location-samples) might be helpful, which does have a permissive license (so can be used).

**Comment by typebrook** [comment]
Hi @louwers 
May I also work on this?

**Comment by louwers** [comment]
You may, but I want to set up a separate repository for the Android examples.


I also want to set up CI to ensure all the examples continue to compile. Source code in Markdown files is too brittle.

**Comment by typebrook** [comment]
> https://github.com/maplibre/maplibre-native-android-examples 

That would be great! Just curious, is this repo only used for build test, or it will become a demo app for many showcases (maybe publish on Google Play Store)? Like https://github.com/mapbox/mapbox-android-demo

**Comment by typebrook** [comment]
Does that means #1135 should continue #741, update all Activities in [com/mapbox/mapboxsdk/testapp/activity/annotation/][folder] ?

[folder]: https://github.com/maplibre/maplibre-native/tree/main/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation

**Comment by louwers** [comment]
@typebrook I modified the acceptance criteria for this bounty.

If you still would like to work on this, let me know and I can assign you!

**Comment by typebrook** [comment]
Yes, I'll take this.

**Comment by typebrook** [comment]
@louwers #1169 is made. Let's have further discussion there

**Comment by louwers** [comment]
This bounty can be paid out.

**Comment by typebrook** [comment]
Invoice link: https://opencollective.com/maplibre/expenses/138358

**Comment by fynngodau** [comment]
@typebrook Probably you have linked the wrong invoice, the correct one appears to be: https://opencollective.com/maplibre/expenses/143821
