### ISSUE TITLE
Embed MetalANGLE into MapLibre framework

### ISSUE THREAD

**Issue by sulewicz** [maplibre/maplibre-native#94]
We should consider embedding the MetalANGLE framework in the MapLibre project to:
1. Simplify the usage for the developer, by requiring only 1 framework (MapLibre) instead of 2 (MapLibre and MetalANGLE).
2. Strip the unnecessary code coming from the Google ANGLE project (MetalANGLE is a fork of that project) to reduce the binary size.
3. Optimize the startup time of the SDK.
4. Get rid of dependency on OpenGL headers which causes a build time warning.

**Comment by wipfli** [comment]
Was this completed, @atierian?

**Comment by atierian** [comment]
No, this hasn't been done, MetalANGLE still needs to be added manually.
This would be a net positive for developers using the `metal-support` branch, but I'm not sure how much effort it makes sense to put into MetalANGLE support at this point. I think we should have a broader discussion on MetalANGLE vs Metal in MapLibre GL Native.

**Comment by wipfli** [comment]
https://github.com/maplibre/maplibre-gl-native/discussions/317
