### ISSUE TITLE
Convert shaders to 3.0

### ISSUE THREAD

**Issue by sjg-wdw** [maplibre/maplibre-native#968]
Convert the existing 2.0 shaders to 3.0 shaders.
Questions include:
- Continue using the code generator?
- Can we eliminate the vertex array #ifdefs to replace them with defaults
- Can we eliminate the varying #ifdefs and just have everything available?

**Comment by sjg-wdw** [comment]
Are you ready to close this?

**Comment by mwilsnd** [comment]
We should keep the generator for now, if we remove the pragma mapbox support all at once we have to port all the render layers at once. Keeping the generator means we can port layers and their shaders one at a time. Once everything is ported we won't need the generator.
