### ISSUE TITLE
Vertex Array defaults instead of #ifdefs

### ISSUE THREAD

**Issue by sjg-wdw** [maplibre/maplibre-native#970]
Use vertex array defaults instead of the #ifdefs in the shaders for 2.0.

**Comment by wipfli** [comment]
What is 2.0?

**Comment by louwers** [comment]
@wipfli OpenGL ES 2.0

**Comment by sjg-wdw** [comment]
OpenGL ES 2.0

**Comment by sjg-wdw** [comment]
Giving this some more thought, I think we should do this for our own shaders, but not worry about it for the pure OpenGL ES 3.0 upgrade.

**Comment by sjg-wdw** [comment]
I believe the way this was resolved was halfway.  We still have the uniforms and the #ifdefs but we're using UBOs for the uniforms.
